services:
  postgres:
    image: postgres:16
    container_name: localgov-postgres
    environment:
      POSTGRES_DB: localgov_erp
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: erp_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: localgov-erp-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/localgov_erp
      DB_USERNAME: erp_admin
      DB_PASSWORD: erp_password
      JWT_SECRET: Q2hhbmdlVGhpc1RvQVN0cm9uZ0FuZExvbmdlckRldk9ubHlTZWNyZXRLZXlGb3JMb2NhbEdvdkVSUA==
      JWT_EXPIRATION_MILLIS: 3600000
      APP_LOG_LEVEL: INFO
      TRACING_SAMPLING_PROBABILITY: 1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.1
    container_name: localgov-otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./ops/otel-collector-config.yml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: localgov-prometheus
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:11.1.0
    container_name: localgov-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  pgdata:
