CREATE TABLE employees (
CREATE TABLE duplicates_archive(
CREATE TABLE audit_log (
CREATE TABLE leave_policy (
CREATE TABLE leave_requests (
CREATE TABLE holidays (
CREATE TABLE calendar (
CREATE TABLE leave_balances (
CREATE TABLE authority_codes (
CREATE TABLE employee_sequence (
CREATE TABLE vacation_allowances (
CREATE TABLE approval_chain (
CREATE TABLE departments (
CREATE TABLE position_attributes (
CREATE TABLE authorities (
CREATE TABLE position_supervisors (
CREATE TABLE ReportingLines (
CREATE TABLE LeaveApprovalChains (
CREATE TABLE Councils (
CREATE TABLE HRA_Positions (
CREATE TABLE HRA_ReportingLines (
CREATE TABLE HRA_LeaveApprovalChains (
CREATE TABLE hra_position_attributes (
CREATE TABLE hra_position_supervisors (
CREATE TABLE hra_leave_approval_chain (
CREATE TABLE sections (
CREATE TABLE positions (
CREATE TABLE leave_approval_chain (
CREATE TABLE eng_units (
CREATE TABLE eng_positions (
CREATE TABLE eng_leave_approval_chain (
CREATE TABLE planning_sections (
CREATE TABLE planning_units (
CREATE TABLE planning_positions (
CREATE TABLE planning_leave_approval_chain (
CREATE TABLE finance_sections (
CREATE TABLE finance_units (
CREATE TABLE finance_positions (
CREATE TABLE finance_leave_approval_chain (
CREATE TABLE legal_sections (
CREATE TABLE legal_units (
CREATE TABLE legal_positions (
CREATE TABLE legal_leave_approval_chain (
CREATE TABLE council_types (
CREATE TABLE salary_scales (
CREATE TABLE health_sections (
CREATE TABLE health_units (
CREATE TABLE health_positions (
CREATE TABLE health_leave_approval_chain (
CREATE TABLE leave_types (
CREATE TABLE hr_recipients (
CREATE TABLE mothers_day_notification_log (
CREATE TABLE mothers_day_acknowledgments (
CREATE TABLE notification_history (
CREATE TABLE sms_gateway_config (
CREATE TABLE sms_delivery_log (
CREATE TABLE sms_message_parts (
CREATE TABLE mothers_day_leave_tracking (
CREATE TABLE notification_queue (
CREATE TABLE eng_position_hierarchy (
CREATE TABLE position_standard_id_map(
CREATE TABLE position_role_codes (
CREATE TABLE position_supervision (
CREATE TABLE executive_positions (
CREATE TABLE jd_upload_queue (
CREATE TABLE job_description_documents (
CREATE TABLE jd_review_queue (
CREATE TABLE hra_supervision (
CREATE TABLE legal_supervision (
CREATE TABLE health_supervision (
CREATE TABLE community_positions (
CREATE TABLE community_sections (
CREATE TABLE community_units (
CREATE TABLE community_supervision (
CREATE TABLE procurement_sections (
CREATE TABLE procurement_units (
CREATE TABLE procurement_positions (
CREATE TABLE procurement_supervision (
CREATE TABLE audit_positions (
CREATE TABLE audit_units (
CREATE TABLE audit_supervision (
CREATE TABLE cos_units (
CREATE TABLE cos_positions (
CREATE TABLE cos_supervision (
CREATE TABLE toc_units (
CREATE TABLE toc_positions (
CREATE TABLE toc_supervision (
CREATE TABLE toc_city_units (
CREATE TABLE toc_city_positions (
CREATE TABLE toc_city_supervision (
CREATE TABLE ict_positions (
CREATE TABLE ict_units (
CREATE TABLE ict_supervision (
CREATE TABLE ict_city_positions (
CREATE TABLE ict_city_units (
CREATE TABLE ict_city_supervision (
CREATE TABLE commercial_positions (
CREATE TABLE commercial_units (
CREATE TABLE commercial_supervision (
CREATE TABLE commercial_city_positions (
CREATE TABLE commercial_city_units (
CREATE TABLE commercial_city_supervision (
CREATE TABLE valuation_city_positions (
CREATE TABLE valuation_city_supervision (
CREATE TABLE immutable_audit_log (
