#!/bin/bash
echo "Extracting ALL 137 tables from clean_data.sql..."

# Create a directory for extracted data
mkdir -p extracted_data

# Function to extract and clean table data
extract_table() {
    table_name=$1
    echo "Extracting $table_name..."
    
    # Extract INSERT statements for the table
    grep -i "INSERT INTO $table_name" clean_data.sql > "extracted_data/${table_name}.sql"
    
    # Replace 0/1 with FALSE/TRUE for boolean columns
    sed -i '' 's/,0,/,FALSE,/g' "extracted_data/${table_name}.sql"
    sed -i '' 's/,1,/,TRUE,/g' "extracted_data/${table_name}.sql"
    sed -i '' 's/,0)/,FALSE)/g' "extracted_data/${table_name}.sql"
    sed -i '' 's/,1)/,TRUE)/g' "extracted_data/${table_name}.sql"
    
    # Count lines
    if [ -f "extracted_data/${table_name}.sql" ]; then
        lines=$(wc -l < "extracted_data/${table_name}.sql")
        echo "  -> $lines records extracted"
    else
        echo "  -> No records found"
    fi
}

# Extract ALL tables (137 total)
echo "Extracting Level 1: Core Tables..."
extract_table "councils"
extract_table "council_types"
extract_table "departments"
extract_table "salary_scales"
extract_table "authority_codes"
extract_table "position_role_codes"
extract_table "calendar"
extract_table "holidays"
extract_table "leave_types"

echo "Extracting Level 2: Basic Structure..."
extract_table "sections"
extract_table "positions"
extract_table "employees"
extract_table "position_standard_id_map"

echo "Extracting Level 3: Department Positions..."
extract_table "hra_positions"
extract_table "finance_positions"
extract_table "legal_positions"
extract_table "health_positions"
extract_table "community_positions"
extract_table "eng_positions"
extract_table "planning_positions"
extract_table "ict_positions"
extract_table "audit_positions"
extract_table "procurement_positions"
extract_table "commercial_positions"
extract_table "cos_positions"
extract_table "toc_positions"
extract_table "valuation_city_positions"
extract_table "ict_city_positions"
extract_table "commercial_city_positions"
extract_table "toc_city_positions"
extract_table "executive_positions"

echo "Extracting Level 4: Department Units & Sections..."
extract_table "finance_sections"
extract_table "finance_units"
extract_table "legal_sections"
extract_table "legal_units"
extract_table "health_sections"
extract_table "health_units"
extract_table "community_sections"
extract_table "community_units"
extract_table "eng_units"
extract_table "planning_sections"
extract_table "planning_units"
extract_table "ict_units"
extract_table "ict_city_units"
extract_table "audit_units"
extract_table "procurement_sections"
extract_table "procurement_units"
extract_table "commercial_units"
extract_table "commercial_city_units"
extract_table "cos_units"
extract_table "toc_units"
extract_table "toc_city_units"

echo "Extracting Level 5: Department Details..."
extract_table "hra_position_attributes"
extract_table "hra_position_supervisors"
extract_table "hra_reportinglines"
extract_table "finance_positions_detailed"
extract_table "finance_salary_distribution"
extract_table "legal_positions_detailed"
extract_table "legal_salary_distribution"
extract_table "health_positions_detailed"
extract_table "health_salary_distribution"
extract_table "eng_positions_detailed"
extract_table "eng_salary_scale_distribution"
extract_table "eng_position_hierarchy"
extract_table "planning_positions_detailed"
extract_table "planning_salary_distribution"
extract_table "planning_management_structure"
extract_table "position_supervisors"
extract_table "position_attributes"
extract_table "duplicates_archive"
extract_table "employee_sequence"

echo "Extracting Level 6: Supervision Hierarchies..."
extract_table "position_supervision"
extract_table "hra_supervision"
extract_table "finance_supervision"
extract_table "legal_supervision"
extract_table "health_supervision"
extract_table "community_supervision"
extract_table "eng_supervision"
extract_table "planning_supervision"
extract_table "ict_supervision"
extract_table "audit_supervision"
extract_table "procurement_supervision"
extract_table "commercial_supervision"
extract_table "cos_supervision"
extract_table "toc_supervision"
extract_table "valuation_city_supervision"
extract_table "ict_city_supervision"
extract_table "commercial_city_supervision"
extract_table "toc_city_supervision"

echo "Extracting Level 7: Approval Chains..."
extract_table "leave_approval_chain"
extract_table "leaveapprovalchains"
extract_table "hra_leave_approval_chain"
extract_table "hra_leaveapprovalchains"
extract_table "finance_leave_approval_chain"
extract_table "legal_leave_approval_chain"
extract_table "health_leave_approval_chain"
extract_table "eng_leave_approval_chain"
extract_table "planning_leave_approval_chain"
extract_table "ict_leave_approval_chain"

echo "Extracting Level 8: Transactions..."
extract_table "leave_requests"
extract_table "leave_balances"
extract_table "leave_policy"
extract_table "leave_resumption"
extract_table "vacation_allowances"
extract_table "mothers_day_leave_tracking"
extract_table "mothers_day_acknowledgments"
extract_table "mothers_day_notification_log"
extract_table "notification_queue"
extract_table "notification_history"
extract_table "hr_recipients"
extract_table "sms_gateway_config"
extract_table "sms_message_parts"
extract_table "sms_delivery_log"
extract_table "job_description_documents"
extract_table "jd_upload_queue"
extract_table "jd_review_queue"

echo "Extracting Level 9: Verification & Flow..."
extract_table "finance_leave_flow_verification"
extract_table "legal_leave_flow_verification"
extract_table "health_leave_flow_verification"
extract_table "eng_leave_flow_verification"
extract_table "planning_leave_flow_verification"
extract_table "ict_leave_flow_verification"
extract_table "finance_org_chart"
extract_table "legal_org_chart"
extract_table "health_org_chart"
extract_table "eng_org_chart"
extract_table "eng_organization_chart"
extract_table "planning_org_chart"
extract_table "finance_staff_by_section"
extract_table "legal_staff_by_section"
extract_table "health_staff_by_unit"
extract_table "eng_staff_by_unit"
extract_table "planning_staff_by_unit"
extract_table "finance_summary_by_council"
extract_table "legal_summary_by_council"
extract_table "health_summary_by_council"
extract_table "eng_summary_by_council"
extract_table "planning_summary_by_council"

echo "Extracting Level 10: Audit & Logs..."
extract_table "audit_log"
extract_table "immutable_audit_log"

echo "Extracting Level 11: Views..."
extract_table "vw_city_leave_approval_flow"
extract_table "vw_city_organization_chart"
extract_table "vw_city_positions_summary"
extract_table "vw_council_community_services"
extract_table "vw_eligible_female_employees"
extract_table "vw_employee_eligibility"
extract_table "vw_employee_leave_history"
extract_table "vw_employee_mothers_day_history"
extract_table "vw_eng_hierarchy_by_council"
extract_table "vw_eng_org_chart"
extract_table "vw_eng_summary_by_council"
extract_table "vw_eng_supervisors"
extract_table "vw_establishment_by_council"
extract_table "vw_fire_service_hierarchy"
extract_table "vw_hr_notifications"
extract_table "vw_hr_recipients"
extract_table "vw_kitwe_community_complete"
extract_table "vw_mechanic_positions"
extract_table "vw_monthly_leave_taken"
extract_table "vw_monthly_mothers_day_report"
extract_table "vw_mothers_day_engineering"
extract_table "vw_mothers_day_engineering_approvers"
extract_table "vw_mothers_day_hr_summary"
extract_table "vw_mothers_day_monthly_report"
extract_table "vw_mothers_day_notification_log"
extract_table "vw_mothers_day_pending_acknowledgments"
extract_table "vw_mothers_day_position_approvers"
extract_table "vw_municipal_leave_approval_flow"
extract_table "vw_municipal_organization_chart"
extract_table "vw_municipal_positions_summary"
extract_table "vw_notification_preferences"
extract_table "vw_org_chart"
extract_table "vw_org_chart_data"
extract_table "vw_org_dna"
extract_table "vw_pending_sms_notifications"
extract_table "vw_pending_supervisor_approvals"
extract_table "vw_position_hierarchy"
extract_table "vw_position_migration_status"
extract_table "vw_sms_ready_notifications"
extract_table "vw_staff_by_level"
extract_table "vw_supervisor_assignments"
extract_table "vw_supervisor_workload"
extract_table "vw_town_organization_chart"

echo "========================================="
echo "Extraction Complete!"
echo "Total tables processed: 137"
echo "Total views processed: 43"
echo "All files saved in 'extracted_data/' directory"
echo "========================================="
