BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS provinces (
    province_code TEXT PRIMARY KEY,
    country_code TEXT NOT NULL DEFAULT 'ZM',
    province_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS authority_master (
    authority_id TEXT PRIMARY KEY,
    country_code TEXT NOT NULL,
    province_code TEXT NOT NULL,
    legacy_authority_code TEXT NOT NULL UNIQUE,
    display_code TEXT NOT NULL,
    authority_ref TEXT NOT NULL UNIQUE,
    authority_name TEXT NOT NULL UNIQUE,
    official_name TEXT NOT NULL UNIQUE,
    authority_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    valid_from DATE,
    valid_to DATE,
    FOREIGN KEY (province_code) REFERENCES provinces(province_code)
);

DELETE FROM authority_master;
DELETE FROM provinces;
DELETE FROM authorities;
DELETE FROM authority_codes;

INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-01', 'ZM', 'Western');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-02', 'ZM', 'Central');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-03', 'ZM', 'Eastern');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-04', 'ZM', 'Luapula');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-05', 'ZM', 'Northern');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-06', 'ZM', 'North-Western');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-07', 'ZM', 'Southern');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-08', 'ZM', 'Copperbelt');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-09', 'ZM', 'Lusaka');
INSERT INTO provinces (province_code, country_code, province_name) VALUES ('ZM-10', 'ZM', 'Muchinga');

INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('c6181a75-2d28-55ab-8f46-e38131896074', 'ZM', 'ZM-01', 'KLO', 'KLO', 'ZM-01-KLO', 'Kalabo', 'Kalabo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kalabo', 'KLO');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-KLO', 'Kalabo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('6b6cccae-4702-511b-8923-7f3ae99c24c3', 'ZM', 'ZM-01', 'KOM', 'KOM', 'ZM-01-KOM', 'Kaoma', 'Kaoma Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kaoma', 'KOM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-KOM', 'Kaoma Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('0038d4de-4879-590e-8449-9f65845d0e75', 'ZM', 'ZM-01', 'LML', 'LML', 'ZM-01-LML', 'Limulunga', 'Limulunga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Limulunga', 'LML');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-LML', 'Limulunga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('10c705b6-5b6f-528e-b0f4-b1337ddb9395', 'ZM', 'ZM-01', 'LPM', 'LPM', 'ZM-01-LPM', 'Luampa', 'Luampa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Luampa', 'LPM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-LPM', 'Luampa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('4a30bc72-17b6-5eb3-9c03-28577692961d', 'ZM', 'ZM-01', 'LKL', 'LKL', 'ZM-01-LKL', 'Lukulu', 'Lukulu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lukulu', 'LKL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-LKL', 'Lukulu Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('da43dcc1-917f-54a5-9fed-bcc6bdb17122', 'ZM', 'ZM-01', 'MTT', 'MTT', 'ZM-01-MTT', 'Mitete', 'Mitete Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mitete', 'MTT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-MTT', 'Mitete Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('36ee7de1-c055-50db-b0bc-02c41747fa50', 'ZM', 'ZM-01', 'MGU', 'MGU', 'ZM-01-MGU', 'Mongu', 'Mongu Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mongu', 'MGU');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-MGU', 'Mongu Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('257b8b3f-2de5-57a1-ac1f-7519d80bd068', 'ZM', 'ZM-01', 'MLB', 'MLB', 'ZM-01-MLB', 'Mulobezi', 'Mulobezi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mulobezi', 'MLB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-MLB', 'Mulobezi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5ffeee6a-1e28-59e9-b519-47eb5a7ff828', 'ZM', 'ZM-01', 'MWD', 'MWD', 'ZM-01-MWD', 'Mwandi', 'Mwandi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mwandi', 'MWD');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-MWD', 'Mwandi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('19edd1bc-de71-5240-8d08-d6ffd97a33e4', 'ZM', 'ZM-01', 'NLL', 'NLL', 'ZM-01-NLL', 'Nalolo', 'Nalolo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nalolo', 'NLL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-NLL', 'Nalolo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('eca13749-f222-5fca-900a-a36a3276aee3', 'ZM', 'ZM-01', 'NKY', 'NKY', 'ZM-01-NKY', 'Nkeyema', 'Nkeyema Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nkeyema', 'NKY');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-NKY', 'Nkeyema Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5add994b-44af-5707-9d73-b61c4b642517', 'ZM', 'ZM-01', 'SNG', 'SNG', 'ZM-01-SNG', 'Senanga', 'Senanga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Senanga', 'SNG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-SNG', 'Senanga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('79afd927-72e4-5fed-af4b-16eccad89741', 'ZM', 'ZM-01', 'SSH', 'SSH', 'ZM-01-SSH', 'Sesheke', 'Sesheke Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Sesheke', 'SSH');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-SSH', 'Sesheke Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('3117a05f-09bf-5e69-8d02-8778a9847e91', 'ZM', 'ZM-01', 'SGM', 'SGM', 'ZM-01-SGM', 'Shangombo', 'Shangombo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Shangombo', 'SGM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-SGM', 'Shangombo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('70b4156e-9de5-5fb1-91b4-36eb579f2246', 'ZM', 'ZM-01', 'SKG', 'SKG', 'ZM-01-SKG', 'Sikongo', 'Sikongo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Sikongo', 'SKG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-SKG', 'Sikongo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('47b6a60c-cb56-51ad-887a-5eda84de650d', 'ZM', 'ZM-01', 'SOM', 'SOM', 'ZM-01-SOM', 'Sioma', 'Sioma Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Sioma', 'SOM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-01-SOM', 'Sioma Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('057f3975-1c85-55eb-9fdf-25ddbdb968f4', 'ZM', 'ZM-02', 'CBB', 'CBB', 'ZM-02-CBB', 'Chibombo', 'Chibombo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chibombo', 'CBB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-CBB', 'Chibombo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('28fbb278-e7cb-5c29-b42f-98fa5ba0a4d3', 'ZM', 'ZM-02', 'CSM', 'CSM', 'ZM-02-CSM', 'Chisamba', 'Chisamba Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chisamba', 'CSM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-CSM', 'Chisamba Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('b590db67-9986-536d-9c75-8f1a3728b5ea', 'ZM', 'ZM-02', 'CTM', 'CTM', 'ZM-02-CTM', 'Chitambo', 'Chitambo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chitambo', 'CTM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-CTM', 'Chitambo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('48a18f75-5605-5418-9489-99c8052998dc', 'ZM', 'ZM-02', 'KBW', 'KBW', 'ZM-02-KBW', 'Kabwe', 'Kabwe Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kabwe', 'KBW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-KBW', 'Kabwe Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('dcfcf021-1f50-5ca6-9266-0599283c377d', 'ZM', 'ZM-02', 'KPM', 'KPM', 'ZM-02-KPM', 'Kapiri Mposhi', 'Kapiri Mposhi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kapiri Mposhi', 'KPM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-KPM', 'Kapiri Mposhi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('a23916c0-7d4d-5627-9734-dd341e2fcbb4', 'ZM', 'ZM-02', 'LNO', 'LNO', 'ZM-02-LNO', 'Luano', 'Luano Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Luano', 'LNO');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-LNO', 'Luano Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('275469af-dc8b-595c-96a8-25908730c24d', 'ZM', 'ZM-02', 'MKU', 'MKU', 'ZM-02-MKU', 'Mkushi', 'Mkushi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mkushi', 'MKU');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-MKU', 'Mkushi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5a8ab3e5-0f26-5e4d-b0ec-0d31229dc8cd', 'ZM', 'ZM-02', 'MBW', 'MBW', 'ZM-02-MBW', 'Mumbwa', 'Mumbwa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mumbwa', 'MBW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-MBW', 'Mumbwa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('23e14477-abf2-54d9-b255-7f1644f5e6d1', 'ZM', 'ZM-02', 'NGB', 'NGB', 'ZM-02-NGB', 'Ngabwe', 'Ngabwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Ngabwe', 'NGB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-NGB', 'Ngabwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('f8b760af-6af9-541e-9a4d-e810ecd221de', 'ZM', 'ZM-02', 'SRJ', 'SRJ', 'ZM-02-SRJ', 'Serenje', 'Serenje Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Serenje', 'SRJ');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-SRJ', 'Serenje Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('a24fdd30-b6fa-574c-a9d5-c8e3e8a90ed9', 'ZM', 'ZM-02', 'SBY', 'SBY', 'ZM-02-SBY', 'Shibuyunji', 'Shibuyunji Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Shibuyunji', 'SBY');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-02-SBY', 'Shibuyunji Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d4c33205-9312-5189-82ce-8cff24a1f6f9', 'ZM', 'ZM-03', 'CDZ', 'CDZ', 'ZM-03-CDZ', 'Chadiza', 'Chadiza Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chadiza', 'CDZ');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-CDZ', 'Chadiza Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('73e2e946-a2ce-5c3e-bdb9-78edb560534d', 'ZM', 'ZM-03', 'CMA', 'CMA', 'ZM-03-CMA', 'Chama', 'Chama Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chama', 'CMA');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-CMA', 'Chama Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('0552ae2a-1ed1-5865-ab23-48121078f419', 'ZM', 'ZM-03', 'CSF', 'CSF', 'ZM-03-CSF', 'Chasefu', 'Chasefu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chasefu', 'CSF');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-CSF', 'Chasefu Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('85ada063-afed-5086-a974-b6b4d78b133a', 'ZM', 'ZM-03', 'CPG', 'CPG', 'ZM-03-CPG', 'Chipangali', 'Chipangali Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chipangali', 'CPG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-CPG', 'Chipangali Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('67ffa471-f931-5815-a7d1-4d0c6ba0a015', 'ZM', 'ZM-03', 'CPT', 'CPT', 'ZM-03-CPT', 'Chipata', 'Chipata City Council', 'City Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chipata', 'CPT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-CPT', 'Chipata City Council', 'City');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('471ac084-a0cc-5fe6-b89e-04d0afc402ee', 'ZM', 'ZM-03', 'KSN', 'KSN', 'ZM-03-KSN', 'Kasenengwa', 'Kasenengwa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kasenengwa', 'KSN');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-KSN', 'Kasenengwa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('9a988145-8841-5ff2-9a35-1ac8134b086d', 'ZM', 'ZM-03', 'KTT', 'KTT', 'ZM-03-KTT', 'Katete', 'Katete Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Katete', 'KTT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-KTT', 'Katete Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('f1b84e0d-ac01-5c99-9ca1-62946fc00ec6', 'ZM', 'ZM-03', 'LMZ', 'LMZ', 'ZM-03-LMZ', 'Lumezi', 'Lumezi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lumezi', 'LMZ');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-LMZ', 'Lumezi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ab8ecefc-d5fb-5f1c-863c-b06ec1a414ba', 'ZM', 'ZM-03', 'LND', 'LND', 'ZM-03-LND', 'Lundazi', 'Lundazi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lundazi', 'LND');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-LND', 'Lundazi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('107d80f1-397b-5112-8037-b464a2b7354b', 'ZM', 'ZM-03', 'LSG', 'LSG', 'ZM-03-LSG', 'Lusangazi', 'Lusangazi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lusangazi', 'LSG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-LSG', 'Lusangazi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('fd4207ad-a839-51a1-b279-7c15baa80e8c', 'ZM', 'ZM-03', 'MMB', 'MMB', 'ZM-03-MMB', 'Mambwe', 'Mambwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mambwe', 'MMB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-MMB', 'Mambwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('11b2049d-0ef2-564d-a20c-481870b681e6', 'ZM', 'ZM-03', 'NYM', 'NYM', 'ZM-03-NYM', 'Nyimba', 'Nyimba Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nyimba', 'NYM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-NYM', 'Nyimba Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('8ffa74a6-0520-5485-ac54-2abe7b5e3fde', 'ZM', 'ZM-03', 'PTK', 'PTK', 'ZM-03-PTK', 'Petauke', 'Petauke Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Petauke', 'PTK');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-PTK', 'Petauke Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d7bf143c-8d6d-5bcb-890e-8b27bdc16da4', 'ZM', 'ZM-03', 'SND', 'SND', 'ZM-03-SND', 'Sinda', 'Sinda Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Sinda', 'SND');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-SND', 'Sinda Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('6dd71fa0-799f-5516-bb55-38541be6dc81', 'ZM', 'ZM-03', 'VBW', 'VBW', 'ZM-03-VBW', 'Vubwi', 'Vubwi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Vubwi', 'VBW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-03-VBW', 'Vubwi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('1f248d7f-69b8-55de-8bde-c8fc51857035', 'ZM', 'ZM-04', 'CHB', 'CHB', 'ZM-04-CHB', 'Chembe', 'Chembe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chembe', 'CHB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-CHB', 'Chembe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('a40b1e88-3431-517e-9387-34a117fc0bf5', 'ZM', 'ZM-04', 'CHG', 'CHG', 'ZM-04-CHG', 'Chiengi', 'Chiengi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chiengi', 'CHG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-CHG', 'Chiengi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('cdf9042e-95bd-5d9f-a4b7-373ade4a2708', 'ZM', 'ZM-04', 'CFB', 'CFB', 'ZM-04-CFB', 'Chifunabuli', 'Chifunabuli Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chifunabuli', 'CFB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-CFB', 'Chifunabuli Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('bd6ed6ec-4118-50cd-a501-03cea8da9c8c', 'ZM', 'ZM-04', 'CPL', 'CPL', 'ZM-04-CPL', 'Chipili', 'Chipili Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chipili', 'CPL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-CPL', 'Chipili Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('8b70dcc4-aa93-50a6-a278-e362143c0059', 'ZM', 'ZM-04', 'KWB', 'KWB', 'ZM-04-KWB', 'Kawambwa', 'Kawambwa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kawambwa', 'KWB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-KWB', 'Kawambwa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('9c7b56b4-8cfa-535f-8c8e-a6b2d9a12558', 'ZM', 'ZM-04', 'LNG', 'LNG', 'ZM-04-LNG', 'Lunga', 'Lunga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lunga', 'LNG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-LNG', 'Lunga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('00ae4447-a43b-5e27-9dd4-e2c53b90d5fc', 'ZM', 'ZM-04', 'MNS', 'MNS', 'ZM-04-MNS', 'Mansa', 'Mansa Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mansa', 'MNS');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-MNS', 'Mansa Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('7eb2abbd-37db-53f5-bcf1-e8f17101672d', 'ZM', 'ZM-04', 'MLG', 'MLG', 'ZM-04-MLG', 'Milenge', 'Milenge Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Milenge', 'MLG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-MLG', 'Milenge Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('64de9840-4a66-5728-912f-51ac7675c97a', 'ZM', 'ZM-04', 'MSB', 'MSB', 'ZM-04-MSB', 'Mwansabombwe', 'Mwansabombwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mwansabombwe', 'MSB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-MSB', 'Mwansabombwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('b8686f88-509e-5fe2-a1f2-cdd7b783a986', 'ZM', 'ZM-04', 'MWE', 'MWE', 'ZM-04-MWE', 'Mwense', 'Mwense Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mwense', 'MWE');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-MWE', 'Mwense Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5e6f8425-e82c-5b4b-8966-80f365b15d37', 'ZM', 'ZM-04', 'NCL', 'NCL', 'ZM-04-NCL', 'Nchelenge', 'Nchelenge Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nchelenge', 'NCL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-NCL', 'Nchelenge Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('0fab397f-70ce-5657-a05e-2a90b5edfe6c', 'ZM', 'ZM-04', 'SMF', 'SMF', 'ZM-04-SMF', 'Samfya', 'Samfya Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Samfya', 'SMF');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-04-SMF', 'Samfya Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('fa099192-91b8-54e8-b920-8522ff5274f9', 'ZM', 'ZM-05', 'CLB', 'CLB', 'ZM-05-CLB', 'Chilubi', 'Chilubi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chilubi', 'CLB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-CLB', 'Chilubi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('2b8d6e94-58e2-5c77-9e5e-5455bf11139a', 'ZM', 'ZM-05', 'KPT', 'KPT', 'ZM-05-KPT', 'Kaputa', 'Kaputa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kaputa', 'KPT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-KPT', 'Kaputa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('1a7d6157-9060-554b-b0d8-0062f487cc83', 'ZM', 'ZM-05', 'KSM', 'KSM', 'ZM-05-KSM', 'Kasama', 'Kasama Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kasama', 'KSM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-KSM', 'Kasama Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('a3b62aae-7bea-5e16-856d-92dd027bd766', 'ZM', 'ZM-05', 'LNT', 'LNT', 'ZM-05-LNT', 'Lunte', 'Lunte Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lunte', 'LNT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-LNT', 'Lunte Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('6523cf0b-a598-59e7-8476-e616ce0f2fd7', 'ZM', 'ZM-05', 'LPS', 'LPS', 'ZM-05-LPS', 'Lupososhi', 'Lupososhi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lupososhi', 'LPS');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-LPS', 'Lupososhi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('b36a6601-8966-5fce-9a74-c1793560400f', 'ZM', 'ZM-05', 'LWI', 'LWI', 'ZM-05-LWI', 'Luwingu', 'Luwingu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Luwingu', 'LWI');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-LWI', 'Luwingu Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('69b8dde6-5a13-56f9-a18c-0bd110e27ac4', 'ZM', 'ZM-05', 'MBL', 'MBL', 'ZM-05-MBL', 'Mbala', 'Mbala Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mbala', 'MBL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-MBL', 'Mbala Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ace745bc-5897-5410-8f2a-11c9ac36f473', 'ZM', 'ZM-05', 'MPR', 'MPR', 'ZM-05-MPR', 'Mporokoso', 'Mporokoso Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mporokoso', 'MPR');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-MPR', 'Mporokoso Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('32cf50b2-511f-586b-9a1e-4783cb74fc76', 'ZM', 'ZM-05', 'MPL', 'MPL', 'ZM-05-MPL', 'Mpulungu', 'Mpulungu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mpulungu', 'MPL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-MPL', 'Mpulungu Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('92045712-ea71-5454-a979-16c8a37c1571', 'ZM', 'ZM-05', 'MNG', 'MNG', 'ZM-05-MNG', 'Mungwi', 'Mungwi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mungwi', 'MNG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-MNG', 'Mungwi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('979a2f04-6b7d-50df-a4b6-eef0054aa996', 'ZM', 'ZM-05', 'NSM', 'NSM', 'ZM-05-NSM', 'Nsama', 'Nsama Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nsama', 'NSM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-NSM', 'Nsama Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('1a8ad9eb-a465-5af7-b368-ae5a8cc915ee', 'ZM', 'ZM-05', 'SGH', 'SGH', 'ZM-05-SGH', 'Senga Hill', 'Senga Hill Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Senga Hill', 'SGH');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-05-SGH', 'Senga Hill Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('79c79e92-6160-56f0-9809-023ce26ef2af', 'ZM', 'ZM-06', 'CVM', 'CVM', 'ZM-06-CVM', 'Chavuma', 'Chavuma Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chavuma', 'CVM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-CVM', 'Chavuma Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ccb138d6-b0b2-555c-8649-eb311e787282', 'ZM', 'ZM-06', 'IKG', 'IKG', 'ZM-06-IKG', 'Ikelenge', 'Ikelenge Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Ikelenge', 'IKG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-IKG', 'Ikelenge Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('9807a836-7f5d-506a-a4b5-ce303b64fb6a', 'ZM', 'ZM-06', 'KBP', 'KBP', 'ZM-06-KBP', 'Kabompo', 'Kabompo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kabompo', 'KBP');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-KBP', 'Kabompo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('f472a12f-535f-59ee-9664-cc6457db2fae', 'ZM', 'ZM-06', 'KLB', 'KLB', 'ZM-06-KLB', 'Kalumbila', 'Kalumbila Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kalumbila', 'KLB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-KLB', 'Kalumbila Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('cf903097-c70f-541e-92b7-0a3dde2719be', 'ZM', 'ZM-06', 'KSP', 'KSP', 'ZM-06-KSP', 'Kasempa', 'Kasempa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kasempa', 'KSP');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-KSP', 'Kasempa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('1a121918-380f-5114-8062-64ed9233fc6d', 'ZM', 'ZM-06', 'MYG', 'MYG', 'ZM-06-MYG', 'Manyinga', 'Manyinga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Manyinga', 'MYG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-MYG', 'Manyinga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('4309a5db-b794-507a-b98b-b4c604a2459a', 'ZM', 'ZM-06', 'MFB', 'MFB', 'ZM-06-MFB', 'Mufumbwe', 'Mufumbwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mufumbwe', 'MFB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-MFB', 'Mufumbwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('b323e4c6-3a33-5f20-8c9f-47f0d14ad64d', 'ZM', 'ZM-06', 'MSD', 'MSD', 'ZM-06-MSD', 'Mushindamo', 'Mushindamo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mushindamo', 'MSD');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-MSD', 'Mushindamo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('a974f076-132f-5711-965d-a8c38f989216', 'ZM', 'ZM-06', 'MWN', 'MWN', 'ZM-06-MWN', 'Mwinilunga', 'Mwinilunga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mwinilunga', 'MWN');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-MWN', 'Mwinilunga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('f0149d07-9897-5136-aa23-6e7f5bd2e00b', 'ZM', 'ZM-06', 'SLW', 'SLW', 'ZM-06-SLW', 'Solwezi', 'Solwezi Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Solwezi', 'SLW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-SLW', 'Solwezi Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5cff4dc3-20de-5ebc-a6f5-1ed1269d1ea7', 'ZM', 'ZM-06', 'ZMB', 'ZMB', 'ZM-06-ZMB', 'Zambezi', 'Zambezi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Zambezi', 'ZMB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-06-ZMB', 'Zambezi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('31bd1b0e-036a-5d5a-b850-5b86edb22e8d', 'ZM', 'ZM-07', 'CKT', 'CKT', 'ZM-07-CKT', 'Chikankata', 'Chikankata Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chikankata', 'CKT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-CKT', 'Chikankata Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('2a31c796-1fa8-50ba-a88a-83b54a078533', 'ZM', 'ZM-07', 'CRD', 'CRD', 'ZM-07-CRD', 'Chirundu', 'Chirundu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chirundu', 'CRD');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-CRD', 'Chirundu Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ea84f96c-b18b-517c-bc6b-64a276b7a751', 'ZM', 'ZM-07', 'CHM', 'CHM', 'ZM-07-CHM', 'Choma', 'Choma Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Choma', 'CHM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-CHM', 'Choma Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('9199cff0-017d-53a6-8ea9-57f74cf46c07', 'ZM', 'ZM-07', 'GWB', 'GWB', 'ZM-07-GWB', 'Gwembe', 'Gwembe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Gwembe', 'GWB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-GWB', 'Gwembe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5cadee49-6f64-5ea9-8505-3a54555c1aa0', 'ZM', 'ZM-07', 'ITT', 'ITT', 'ZM-07-ITT', 'Itezhi Tezhi', 'Itezhi Tezhi Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Itezhi Tezhi', 'ITT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-ITT', 'Itezhi Tezhi Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('158190c8-908a-5cdc-88d6-c8213a0bd017', 'ZM', 'ZM-07', 'KLM', 'KLM', 'ZM-07-KLM', 'Kalomo', 'Kalomo Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kalomo', 'KLM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-KLM', 'Kalomo Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('1c818383-9dd3-58b7-b69e-7e6b487652d3', 'ZM', 'ZM-07', 'KZG', 'KZG', 'ZM-07-KZG', 'Kazungula', 'Kazungula Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kazungula', 'KZG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-KZG', 'Kazungula Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d55353e3-76ad-5093-9b1a-e142b621c0bb', 'ZM', 'ZM-07', 'LIV', 'LCC', 'ZM-07-LCC', 'Livingstone', 'Livingstone City Council', 'City Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Livingstone', 'LIV');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-LCC', 'Livingstone City Council', 'City');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5f0b7b6a-45bc-5d5d-a07f-6f77cd6bd612', 'ZM', 'ZM-07', 'MZB', 'MZB', 'ZM-07-MZB', 'Mazabuka', 'Mazabuka Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mazabuka', 'MZB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-MZB', 'Mazabuka Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('cd075bb4-21af-5574-a117-fb1155e392c6', 'ZM', 'ZM-07', 'MNZ', 'MNZ', 'ZM-07-MNZ', 'Monze', 'Monze Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Monze', 'MNZ');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-MNZ', 'Monze Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('7d198ccc-bf3a-58b4-b6e3-94e85d308762', 'ZM', 'ZM-07', 'NMW', 'NMW', 'ZM-07-NMW', 'Namwala', 'Namwala Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Namwala', 'NMW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-NMW', 'Namwala Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d415ddcb-c973-5771-9f8a-1051c6e9b16a', 'ZM', 'ZM-07', 'PMB', 'PMB', 'ZM-07-PMB', 'Pemba', 'Pemba Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Pemba', 'PMB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-PMB', 'Pemba Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('fbb6f1eb-b2d5-589e-ad9b-48b137aa4065', 'ZM', 'ZM-07', 'SVG', 'SVG', 'ZM-07-SVG', 'Siavonga', 'Siavonga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Siavonga', 'SVG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-SVG', 'Siavonga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('3e46732e-0f52-544d-918b-0ea7301f2654', 'ZM', 'ZM-07', 'SNZ', 'SNZ', 'ZM-07-SNZ', 'Sinazongwe', 'Sinazongwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Sinazongwe', 'SNZ');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-SNZ', 'Sinazongwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('2d7f7e7a-c40f-56c3-b07e-5f21a64e871b', 'ZM', 'ZM-07', 'ZIM', 'ZIM', 'ZM-07-ZIM', 'Zimba', 'Zimba Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Zimba', 'ZIM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-07-ZIM', 'Zimba Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('c2b30ff8-e2f8-5e63-bd18-6f731e99eaf6', 'ZM', 'ZM-08', 'CLC', 'CLC', 'ZM-08-CLC', 'Chililabombwe', 'Chililabombwe Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chililabombwe', 'CLC');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-CLC', 'Chililabombwe Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('9e37ef0f-57df-5e3b-b8ab-28c7a55fa30d', 'ZM', 'ZM-08', 'CHN', 'CHN', 'ZM-08-CHN', 'Chingola', 'Chingola Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chingola', 'CHN');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-CHN', 'Chingola Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('4fc79fe3-c517-5cbb-8a62-46c8c1376118', 'ZM', 'ZM-08', 'KLS', 'KLS', 'ZM-08-KLS', 'Kalulushi', 'Kalulushi Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kalulushi', 'KLS');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-KLS', 'Kalulushi Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('47f871aa-10f1-52f8-9fc0-6be4c5592ea5', 'ZM', 'ZM-08', 'KIT', 'KCC', 'ZM-08-KCC', 'Kitwe', 'Kitwe City Council', 'City Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kitwe', 'KIT');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-KCC', 'Kitwe City Council', 'City');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('42cde67b-1412-565a-b04a-4a4eb988afef', 'ZM', 'ZM-08', 'LUN', 'LUN', 'ZM-08-LUN', 'Luanshya', 'Luanshya Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Luanshya', 'LUN');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-LUN', 'Luanshya Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('bba355b6-7bc4-5566-aaac-3d59a5598ff1', 'ZM', 'ZM-08', 'LFW', 'LFW', 'ZM-08-LFW', 'Lufwanyama', 'Lufwanyama Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lufwanyama', 'LFW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-LFW', 'Lufwanyama Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('db4a98fa-723f-5fd3-a60a-41173633f979', 'ZM', 'ZM-08', 'MST', 'MST', 'ZM-08-MST', 'Masaiti', 'Masaiti Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Masaiti', 'MST');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-MST', 'Masaiti Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('e258d4b2-ff10-5476-a1be-93e472f23e0c', 'ZM', 'ZM-08', 'MPG', 'MPG', 'ZM-08-MPG', 'Mpongwe', 'Mpongwe Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mpongwe', 'MPG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-MPG', 'Mpongwe Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ec24bff5-975c-5059-860a-e1219edccd0b', 'ZM', 'ZM-08', 'MUF', 'MUF', 'ZM-08-MUF', 'Mufulira', 'Mufulira Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mufulira', 'MUF');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-MUF', 'Mufulira Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d9dbd497-b72d-5e8c-a93e-9062829af3f7', 'ZM', 'ZM-08', 'NDL', 'NDL', 'ZM-08-NDL', 'Ndola', 'Ndola City Council', 'City Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Ndola', 'NDL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-08-NDL', 'Ndola City Council', 'City');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('555b0509-db30-5e7f-96d2-c39c20acd968', 'ZM', 'ZM-09', 'CHL', 'CHL', 'ZM-09-CHL', 'Chilanga', 'Chilanga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chilanga', 'CHL');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-CHL', 'Chilanga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('08ba2c88-7dea-53ea-b738-012ec810c180', 'ZM', 'ZM-09', 'CHW', 'CHW', 'ZM-09-CHW', 'Chongwe', 'Chongwe Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chongwe', 'CHW');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-CHW', 'Chongwe Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('20759bdd-b7ee-5181-90e0-a7d9578b4336', 'ZM', 'ZM-09', 'KAF', 'KAF', 'ZM-09-KAF', 'Kafue', 'Kafue Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kafue', 'KAF');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-KAF', 'Kafue Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('07109ef5-6d1d-518e-b795-d4c5c3364e28', 'ZM', 'ZM-09', 'LWG', 'LWG', 'ZM-09-LWG', 'Luangwa', 'Luangwa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Luangwa', 'LWG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-LWG', 'Luangwa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('aa3487a3-db51-57a0-bb23-2e50e4bb8141', 'ZM', 'ZM-09', 'LSK', 'LCC', 'ZM-09-LCC', 'Lusaka', 'Lusaka City Council', 'City Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lusaka', 'LSK');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-LCC', 'Lusaka City Council', 'City');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('5d1e2fba-4e20-5fb5-9605-a48da85aec48', 'ZM', 'ZM-09', 'RFN', 'RFN', 'ZM-09-RFN', 'Rufunsa', 'Rufunsa Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Rufunsa', 'RFN');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-09-RFN', 'Rufunsa Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('49bcf57c-6b62-56dd-bc7c-613bfa4283c6', 'ZM', 'ZM-10', 'CNS', 'CNS', 'ZM-10-CNS', 'Chinsali', 'Chinsali Municipal Council', 'Municipal Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Chinsali', 'CNS');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-CNS', 'Chinsali Municipal Council', 'Municipal');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('36456b12-aac3-5979-859b-fba3c46126dc', 'ZM', 'ZM-10', 'ISK', 'ISK', 'ZM-10-ISK', 'Isoka', 'Isoka Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Isoka', 'ISK');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-ISK', 'Isoka Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('117606af-25bc-5175-af97-272a1af39827', 'ZM', 'ZM-10', 'KCB', 'KCB', 'ZM-10-KCB', 'Kanchibiya', 'Kanchibiya Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Kanchibiya', 'KCB');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-KCB', 'Kanchibiya Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('ef561c9f-42eb-5f68-8b63-670a8e556200', 'ZM', 'ZM-10', 'LVM', 'LVM', 'ZM-10-LVM', 'Lavushimanda', 'Lavushimanda Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Lavushimanda', 'LVM');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-LVM', 'Lavushimanda Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('d931fa11-6ed4-5f63-9f97-89a2c3ed523d', 'ZM', 'ZM-10', 'MFG', 'MFG', 'ZM-10-MFG', 'Mafinga', 'Mafinga Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mafinga', 'MFG');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-MFG', 'Mafinga Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('cb82c600-0eeb-5db0-8d5b-57cb44c5a0bd', 'ZM', 'ZM-10', 'MPK', 'MPK', 'ZM-10-MPK', 'Mpika', 'Mpika Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Mpika', 'MPK');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-MPK', 'Mpika Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('afb9dddc-097e-56e2-9ae3-256ea6ffe6fe', 'ZM', 'ZM-10', 'NKD', 'NKD', 'ZM-10-NKD', 'Nakonde', 'Nakonde Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Nakonde', 'NKD');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-NKD', 'Nakonde Town Council', 'Town');
INSERT INTO authority_master (authority_id, country_code, province_code, legacy_authority_code, display_code, authority_ref, authority_name, official_name, authority_type, status, valid_from, valid_to) VALUES ('f66f622b-9116-511a-8a92-8cdbcfe3991a', 'ZM', 'ZM-10', 'SWA', 'SWA', 'ZM-10-SWA', 'Shiwang''andu', 'Shiwang''andu Town Council', 'Town Council', 'active', NULL, NULL);
INSERT INTO authority_codes (authority_name, authority_code) VALUES ('Shiwang''andu', 'SWA');
INSERT INTO authorities (authority_prefix, authority_name, authority_type) VALUES ('ZM-10-SWA', 'Shiwang''andu Town Council', 'Town');

DROP VIEW IF EXISTS authority_lookup;
CREATE VIEW authority_lookup AS
SELECT am.authority_id, am.country_code, am.province_code, p.province_name, am.legacy_authority_code, am.display_code, am.authority_ref, am.authority_name, am.official_name, am.authority_type, am.status, am.valid_from, am.valid_to
FROM authority_master am
JOIN provinces p ON p.province_code = am.province_code;

COMMIT;
