INSERT INTO community_units VALUES(1,'Community Development Unit','COM-DEV-TOW',TRUE,1,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(2,'Library and Archiving Services Unit','LIB-ARC-TOW',TRUE,1,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(3,'Housing Unit','HOUS-TOW',2,TRUE,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(4,'Bus Stations Unit','BUS-TOW',2,TRUE,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(5,'Markets Unit','MKT-TOW',2,TRUE,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(6,'Community Development Unit','COM-DEV-MUN',3,2,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(7,'Library and Archiving Services Unit','LIB-ARC-MUN',3,2,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(8,'Housing Unit','HOUS-MUN',4,2,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(9,'Bus Stations Unit','BUS-MUN',4,2,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(10,'Markets Unit','MKT-MUN',4,2,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(11,'Community Development Unit','COM-DEV-CIT',5,3,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(12,'Library and Archiving Services Unit','LIB-ARC-CIT',5,3,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(13,'Housing Unit','HOUS-CIT',6,3,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(14,'Bus Stations Unit','BUS-CIT',6,3,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(15,'Markets Unit','MKT-CIT',6,3,NULL,FALSE,NULL);
INSERT INTO community_units VALUES(16,'Vocational Training Unit','VOC-CIT',7,3,NULL,TRUE,5);
