INSERT INTO eng_leave_approval_chain VALUES(1,'COUNCIL-SEC',TRUE,'Supervisor',NULL);
INSERT INTO eng_leave_approval_chain VALUES(2,'COUNCIL-SEC',2,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(3,'COUNCIL-SEC',3,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(4,'ENG-DIR-TC',TRUE,'Supervisor','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(5,'ENG-DIR-TC',2,'Head of Department','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(6,'ENG-DIR-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(7,'ENG-ASST-DIR-TC',TRUE,'Supervisor','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(8,'ENG-ASST-DIR-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(9,'ENG-ASST-DIR-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(10,'ENG-ELEC-CHIEF-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(11,'ENG-ELEC-CHIEF-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(12,'ENG-ELEC-CHIEF-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(13,'ENG-ELEC-HEAD-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(14,'ENG-ELEC-HEAD-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(15,'ENG-ELEC-HEAD-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(16,'ENG-ELEC-ASST-TC',TRUE,'Supervisor','ENG-ELEC-HEAD-TC');
INSERT INTO eng_leave_approval_chain VALUES(17,'ENG-ELEC-ASST-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(18,'ENG-ELEC-ASST-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(19,'ENG-ELEC-TECH-TC',TRUE,'Supervisor','ENG-ELEC-HEAD-TC');
INSERT INTO eng_leave_approval_chain VALUES(20,'ENG-ELEC-TECH-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(21,'ENG-ELEC-TECH-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(22,'ENG-MAINT-SUP-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(23,'ENG-MAINT-SUP-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(24,'ENG-MAINT-SUP-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(25,'ENG-PLUM-TC',TRUE,'Supervisor','ENG-MAINT-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(26,'ENG-PLUM-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(27,'ENG-PLUM-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(28,'ENG-BRICK-TC',TRUE,'Supervisor','ENG-MAINT-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(29,'ENG-BRICK-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(30,'ENG-BRICK-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(31,'ENG-CARP-TC',TRUE,'Supervisor','ENG-MAINT-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(32,'ENG-CARP-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(33,'ENG-CARP-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(34,'ENG-PAINT-TC',TRUE,'Supervisor','ENG-MAINT-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(35,'ENG-PAINT-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(36,'ENG-PAINT-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(37,'ENG-GENWORK-TC',TRUE,'Supervisor','ENG-MAINT-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(38,'ENG-GENWORK-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(39,'ENG-GENWORK-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(40,'ENG-QSURV-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(41,'ENG-QSURV-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(42,'ENG-QSURV-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(43,'ENG-QSURV-ASST-TC',TRUE,'Supervisor','ENG-QSURV-TC');
INSERT INTO eng_leave_approval_chain VALUES(44,'ENG-QSURV-ASST-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(45,'ENG-QSURV-ASST-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(46,'ENG-ARCH-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(47,'ENG-ARCH-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(48,'ENG-ARCH-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(49,'ENG-ARCH-ASST-TC',TRUE,'Supervisor','ENG-ARCH-TC');
INSERT INTO eng_leave_approval_chain VALUES(50,'ENG-ARCH-ASST-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(51,'ENG-ARCH-ASST-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(52,'ENG-CLERK-TC',TRUE,'Supervisor','ENG-ARCH-TC');
INSERT INTO eng_leave_approval_chain VALUES(53,'ENG-CLERK-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(54,'ENG-CLERK-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(55,'ENG-DRAFT-TC',TRUE,'Supervisor','ENG-ARCH-TC');
INSERT INTO eng_leave_approval_chain VALUES(56,'ENG-DRAFT-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(57,'ENG-DRAFT-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(58,'ENG-PARK-MGR-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(59,'ENG-PARK-MGR-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(60,'ENG-PARK-MGR-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(61,'ENG-PARK-SUP-TC',TRUE,'Supervisor','ENG-PARK-MGR-TC');
INSERT INTO eng_leave_approval_chain VALUES(62,'ENG-PARK-SUP-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(63,'ENG-PARK-SUP-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(64,'ENG-PARK-WORK-TC',TRUE,'Supervisor','ENG-PARK-SUP-TC');
INSERT INTO eng_leave_approval_chain VALUES(65,'ENG-PARK-WORK-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(66,'ENG-PARK-WORK-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(67,'ENG-CIVIL-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(68,'ENG-CIVIL-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(69,'ENG-CIVIL-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(70,'ENG-CIVIL-ASST-TC',TRUE,'Supervisor','ENG-CIVIL-TC');
INSERT INTO eng_leave_approval_chain VALUES(71,'ENG-CIVIL-ASST-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(72,'ENG-CIVIL-ASST-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(73,'ENG-CIVIL-TECH-TC',TRUE,'Supervisor','ENG-CIVIL-TC');
INSERT INTO eng_leave_approval_chain VALUES(74,'ENG-CIVIL-TECH-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(75,'ENG-CIVIL-TECH-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(76,'ENG-MECH-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(77,'ENG-MECH-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(78,'ENG-MECH-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(79,'ENG-MECH-ASST-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(80,'ENG-MECH-ASST-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(81,'ENG-MECH-ASST-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(82,'ENG-MOTOR-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(83,'ENG-MOTOR-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(84,'ENG-MOTOR-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(85,'ENG-AUTO-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(86,'ENG-AUTO-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(87,'ENG-AUTO-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(88,'ENG-MECH-TECH-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(89,'ENG-MECH-TECH-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(90,'ENG-MECH-TECH-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(91,'ENG-EXCAV-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(92,'ENG-EXCAV-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(93,'ENG-EXCAV-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(94,'ENG-SCALER-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(95,'ENG-SCALER-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(96,'ENG-SCALER-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(97,'ENG-HANDY-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(98,'ENG-HANDY-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(99,'ENG-HANDY-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(100,'ENG-WELDER-TC',TRUE,'Supervisor','ENG-MECH-TC');
INSERT INTO eng_leave_approval_chain VALUES(101,'ENG-WELDER-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(102,'ENG-WELDER-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(103,'ENG-FIRE-DIV-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(104,'ENG-FIRE-DIV-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(105,'ENG-FIRE-DIV-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(106,'ENG-FIRE-STN-TC',TRUE,'Supervisor','ENG-FIRE-DIV-TC');
INSERT INTO eng_leave_approval_chain VALUES(107,'ENG-FIRE-STN-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(108,'ENG-FIRE-STN-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(109,'ENG-FIRE-SUB-TC',TRUE,'Supervisor','ENG-FIRE-STN-TC');
INSERT INTO eng_leave_approval_chain VALUES(110,'ENG-FIRE-SUB-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(111,'ENG-FIRE-SUB-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(112,'ENG-FIRE-LEAD-TC',TRUE,'Supervisor','ENG-FIRE-STN-TC');
INSERT INTO eng_leave_approval_chain VALUES(113,'ENG-FIRE-LEAD-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(114,'ENG-FIRE-LEAD-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(115,'ENG-FIRE-TC',TRUE,'Supervisor','ENG-FIRE-LEAD-TC');
INSERT INTO eng_leave_approval_chain VALUES(116,'ENG-FIRE-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(117,'ENG-FIRE-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(118,'ENG-FIRE-DRV-TC',TRUE,'Supervisor','ENG-FIRE-LEAD-TC');
INSERT INTO eng_leave_approval_chain VALUES(119,'ENG-FIRE-DRV-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(120,'ENG-FIRE-DRV-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(121,'ENG-WATSAN-TC',TRUE,'Supervisor','ENG-ASST-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(122,'ENG-WATSAN-TC',2,'Head of Department','ENG-DIR-TC');
INSERT INTO eng_leave_approval_chain VALUES(123,'ENG-WATSAN-TC',3,'Head of Council','COUNCIL-SEC');
INSERT INTO eng_leave_approval_chain VALUES(124,'TOWN-CLERK-MC',TRUE,'Supervisor',NULL);
INSERT INTO eng_leave_approval_chain VALUES(125,'TOWN-CLERK-MC',2,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(126,'TOWN-CLERK-MC',3,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(127,'ENG-DIR-MC',TRUE,'Supervisor','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(128,'ENG-DIR-MC',2,'Head of Department','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(129,'ENG-DIR-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(130,'ENG-CONSTR-ASSTDIR-MC',TRUE,'Supervisor','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(131,'ENG-CONSTR-ASSTDIR-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(132,'ENG-CONSTR-ASSTDIR-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(133,'ENG-ROADS-ASSTDIR-MC',TRUE,'Supervisor','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(134,'ENG-ROADS-ASSTDIR-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(135,'ENG-ROADS-ASSTDIR-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(136,'ENG-ELEC-CHIEF-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(137,'ENG-ELEC-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(138,'ENG-ELEC-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(139,'ENG-ELEC-ENG07-MC',TRUE,'Supervisor','ENG-ELEC-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(140,'ENG-ELEC-ENG07-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(141,'ENG-ELEC-ENG07-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(142,'ENG-ELEC-ASST-MC',TRUE,'Supervisor','ENG-ELEC-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(143,'ENG-ELEC-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(144,'ENG-ELEC-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(145,'ENG-ELEC-SUPT-MC',TRUE,'Supervisor','ENG-ELEC-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(146,'ENG-ELEC-SUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(147,'ENG-ELEC-SUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(148,'ENG-ELEC-ASSTSUPT-MC',TRUE,'Supervisor','ENG-ELEC-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(149,'ENG-ELEC-ASSTSUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(150,'ENG-ELEC-ASSTSUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(151,'ENG-ELEC-SENASSIST-MC',TRUE,'Supervisor','ENG-ELEC-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(152,'ENG-ELEC-SENASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(153,'ENG-ELEC-SENASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(154,'ENG-ELEC-WORKSUP-MC',TRUE,'Supervisor','ENG-ELEC-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(155,'ENG-ELEC-WORKSUP-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(156,'ENG-ELEC-WORKSUP-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(157,'ENG-ELEC-TECH-MC',TRUE,'Supervisor','ENG-ELEC-WORKSUP-MC');
INSERT INTO eng_leave_approval_chain VALUES(158,'ENG-ELEC-TECH-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(159,'ENG-ELEC-TECH-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(160,'ENG-ELEC-FOREMAN-MC',TRUE,'Supervisor','ENG-ELEC-WORKSUP-MC');
INSERT INTO eng_leave_approval_chain VALUES(161,'ENG-ELEC-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(162,'ENG-ELEC-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(163,'ENG-ELEC-ASSTFORE-MC',TRUE,'Supervisor','ENG-ELEC-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(164,'ENG-ELEC-ASSTFORE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(165,'ENG-ELEC-ASSTFORE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(166,'ENG-QSURV-CHIEF-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(167,'ENG-QSURV-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(168,'ENG-QSURV-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(169,'ENG-QSURV07-MC',TRUE,'Supervisor','ENG-QSURV-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(170,'ENG-QSURV07-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(171,'ENG-QSURV07-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(172,'ENG-QSURV-ASST-MC',TRUE,'Supervisor','ENG-QSURV07-MC');
INSERT INTO eng_leave_approval_chain VALUES(173,'ENG-QSURV-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(174,'ENG-QSURV-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(175,'ENG-QSURV-SENASSIST-MC',TRUE,'Supervisor','ENG-QSURV-ASST-MC');
INSERT INTO eng_leave_approval_chain VALUES(176,'ENG-QSURV-SENASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(177,'ENG-QSURV-SENASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(178,'ENG-QSURV-ASSIST-MC',TRUE,'Supervisor','ENG-QSURV-ASST-MC');
INSERT INTO eng_leave_approval_chain VALUES(179,'ENG-QSURV-ASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(180,'ENG-QSURV-ASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(181,'ENG-ARCH-CHIEF-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(182,'ENG-ARCH-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(183,'ENG-ARCH-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(184,'ENG-ARCH07-MC',TRUE,'Supervisor','ENG-ARCH-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(185,'ENG-ARCH07-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(186,'ENG-ARCH07-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(187,'ENG-ARCH-ASST-MC',TRUE,'Supervisor','ENG-ARCH07-MC');
INSERT INTO eng_leave_approval_chain VALUES(188,'ENG-ARCH-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(189,'ENG-ARCH-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(190,'ENG-ARCH-ASSIST-MC',TRUE,'Supervisor','ENG-ARCH-ASST-MC');
INSERT INTO eng_leave_approval_chain VALUES(191,'ENG-ARCH-ASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(192,'ENG-ARCH-ASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(193,'ENG-ARCH-FOREMAN-MC',TRUE,'Supervisor','ENG-ARCH-ASST-MC');
INSERT INTO eng_leave_approval_chain VALUES(194,'ENG-ARCH-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(195,'ENG-ARCH-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(196,'ENG-ARCH-ASSTFORE-MC',TRUE,'Supervisor','ENG-ARCH-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(197,'ENG-ARCH-ASSTFORE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(198,'ENG-ARCH-ASSTFORE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(199,'ENG-ARCH-SENCLERK-MC',TRUE,'Supervisor','ENG-ARCH07-MC');
INSERT INTO eng_leave_approval_chain VALUES(200,'ENG-ARCH-SENCLERK-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(201,'ENG-ARCH-SENCLERK-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(202,'ENG-ARCH-CLERK-MC',TRUE,'Supervisor','ENG-ARCH-SENCLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(203,'ENG-ARCH-CLERK-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(204,'ENG-ARCH-CLERK-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(205,'ENG-ARCH-DRAFT-MC',TRUE,'Supervisor','ENG-ARCH07-MC');
INSERT INTO eng_leave_approval_chain VALUES(206,'ENG-ARCH-DRAFT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(207,'ENG-ARCH-DRAFT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(208,'ENG-MAINT-SUPT-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(209,'ENG-MAINT-SUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(210,'ENG-MAINT-SUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(211,'ENG-MAINT-ASSTSUPT-MC',TRUE,'Supervisor','ENG-MAINT-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(212,'ENG-MAINT-ASSTSUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(213,'ENG-MAINT-ASSTSUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(214,'ENG-MAINT-FOREMAN-MC',TRUE,'Supervisor','ENG-MAINT-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(215,'ENG-MAINT-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(216,'ENG-MAINT-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(217,'ENG-MAINT-PLUM-MC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(218,'ENG-MAINT-PLUM-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(219,'ENG-MAINT-PLUM-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(220,'ENG-MAINT-BRICK-MC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(221,'ENG-MAINT-BRICK-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(222,'ENG-MAINT-BRICK-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(223,'ENG-MAINT-CARP-MC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(224,'ENG-MAINT-CARP-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(225,'ENG-MAINT-CARP-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(226,'ENG-MAINT-PAINT-MC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(227,'ENG-MAINT-PAINT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(228,'ENG-MAINT-PAINT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(229,'ENG-MAINT-GENWORK-MC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(230,'ENG-MAINT-GENWORK-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(231,'ENG-MAINT-GENWORK-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(232,'ENG-PARK-MGR-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(233,'ENG-PARK-MGR-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(234,'ENG-PARK-MGR-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(235,'ENG-PARK-SUPT-MC',TRUE,'Supervisor','ENG-PARK-MGR-MC');
INSERT INTO eng_leave_approval_chain VALUES(236,'ENG-PARK-SUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(237,'ENG-PARK-SUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(238,'ENG-PARK-ASSTSUPT-MC',TRUE,'Supervisor','ENG-PARK-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(239,'ENG-PARK-ASSTSUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(240,'ENG-PARK-ASSTSUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(241,'ENG-PARK-FOREMAN-MC',TRUE,'Supervisor','ENG-PARK-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(242,'ENG-PARK-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(243,'ENG-PARK-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(244,'ENG-PARK-SUP-MC',TRUE,'Supervisor','ENG-PARK-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(245,'ENG-PARK-SUP-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(246,'ENG-PARK-SUP-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(247,'ENG-PARK-ASSTFORE-MC',TRUE,'Supervisor','ENG-PARK-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(248,'ENG-PARK-ASSTFORE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(249,'ENG-PARK-ASSTFORE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(250,'ENG-PARK-WORK-MC',TRUE,'Supervisor','ENG-PARK-SUP-MC');
INSERT INTO eng_leave_approval_chain VALUES(251,'ENG-PARK-WORK-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(252,'ENG-PARK-WORK-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(253,'ENG-MECH-CHIEF-MC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(254,'ENG-MECH-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(255,'ENG-MECH-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(256,'ENG-MECH07-MC',TRUE,'Supervisor','ENG-MECH-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(257,'ENG-MECH07-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(258,'ENG-MECH07-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(259,'ENG-MECH-ASST-MC',TRUE,'Supervisor','ENG-MECH07-MC');
INSERT INTO eng_leave_approval_chain VALUES(260,'ENG-MECH-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(261,'ENG-MECH-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(262,'ENG-MECH-SUPT-MC',TRUE,'Supervisor','ENG-MECH07-MC');
INSERT INTO eng_leave_approval_chain VALUES(263,'ENG-MECH-SUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(264,'ENG-MECH-SUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(265,'ENG-MECH-ASSTSUPT-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(266,'ENG-MECH-ASSTSUPT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(267,'ENG-MECH-ASSTSUPT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(268,'ENG-MECH-ASSIST-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(269,'ENG-MECH-ASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(270,'ENG-MECH-ASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(271,'ENG-MECH-AUTO-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(272,'ENG-MECH-AUTO-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(273,'ENG-MECH-AUTO-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(274,'ENG-MECH-TECH-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(275,'ENG-MECH-TECH-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(276,'ENG-MECH-TECH-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(277,'ENG-MECH-FOREMAN-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(278,'ENG-MECH-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(279,'ENG-MECH-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(280,'ENG-MECH-ASSTFORE-MC',TRUE,'Supervisor','ENG-MECH-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(281,'ENG-MECH-ASSTFORE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(282,'ENG-MECH-ASSTFORE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(283,'ENG-MECH-PLANT-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(284,'ENG-MECH-PLANT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(285,'ENG-MECH-PLANT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(286,'ENG-MECH-HANDY-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(287,'ENG-MECH-HANDY-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(288,'ENG-MECH-HANDY-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(289,'ENG-MECH-WELDER-MC',TRUE,'Supervisor','ENG-MECH-SUPT-MC');
INSERT INTO eng_leave_approval_chain VALUES(290,'ENG-MECH-WELDER-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(291,'ENG-MECH-WELDER-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(292,'ENG-CIVIL-CHIEF-MC',TRUE,'Supervisor','ENG-ROADS-ASSTDIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(293,'ENG-CIVIL-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(294,'ENG-CIVIL-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(295,'ENG-CIVIL07-MC',TRUE,'Supervisor','ENG-CIVIL-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(296,'ENG-CIVIL07-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(297,'ENG-CIVIL07-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(298,'ENG-CIVIL-ASST-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(299,'ENG-CIVIL-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(300,'ENG-CIVIL-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(301,'ENG-CIVIL-HIGHWAY-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(302,'ENG-CIVIL-HIGHWAY-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(303,'ENG-CIVIL-HIGHWAY-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(304,'ENG-CIVIL-SENASSIST-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(305,'ENG-CIVIL-SENASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(306,'ENG-CIVIL-SENASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(307,'ENG-CIVIL-ASSIST-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(308,'ENG-CIVIL-ASSIST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(309,'ENG-CIVIL-ASSIST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(310,'ENG-CIVIL-FOREMAN-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(311,'ENG-CIVIL-FOREMAN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(312,'ENG-CIVIL-FOREMAN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(313,'ENG-CIVIL-DRAFT-MC',TRUE,'Supervisor','ENG-CIVIL07-MC');
INSERT INTO eng_leave_approval_chain VALUES(314,'ENG-CIVIL-DRAFT-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(315,'ENG-CIVIL-DRAFT-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(316,'ENG-CIVIL-ASSTFORE-MC',TRUE,'Supervisor','ENG-CIVIL-FOREMAN-MC');
INSERT INTO eng_leave_approval_chain VALUES(317,'ENG-CIVIL-ASSTFORE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(318,'ENG-CIVIL-ASSTFORE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(319,'ENG-FIRE-CHIEF-MC',TRUE,'Supervisor','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(320,'ENG-FIRE-CHIEF-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(321,'ENG-FIRE-CHIEF-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(322,'ENG-FIRE-DEPUTY-MC',TRUE,'Supervisor','ENG-FIRE-CHIEF-MC');
INSERT INTO eng_leave_approval_chain VALUES(323,'ENG-FIRE-DEPUTY-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(324,'ENG-FIRE-DEPUTY-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(325,'ENG-FIRE-DIV-MC',TRUE,'Supervisor','ENG-FIRE-DEPUTY-MC');
INSERT INTO eng_leave_approval_chain VALUES(326,'ENG-FIRE-DIV-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(327,'ENG-FIRE-DIV-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(328,'ENG-FIRE-ASSTDIV-MC',TRUE,'Supervisor','ENG-FIRE-DIV-MC');
INSERT INTO eng_leave_approval_chain VALUES(329,'ENG-FIRE-ASSTDIV-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(330,'ENG-FIRE-ASSTDIV-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(331,'ENG-FIRE-STN-MC',TRUE,'Supervisor','ENG-FIRE-DIV-MC');
INSERT INTO eng_leave_approval_chain VALUES(332,'ENG-FIRE-STN-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(333,'ENG-FIRE-STN-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(334,'ENG-FIRE-SUB-MC',TRUE,'Supervisor','ENG-FIRE-STN-MC');
INSERT INTO eng_leave_approval_chain VALUES(335,'ENG-FIRE-SUB-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(336,'ENG-FIRE-SUB-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(337,'ENG-FIRE-LEAD-MC',TRUE,'Supervisor','ENG-FIRE-SUB-MC');
INSERT INTO eng_leave_approval_chain VALUES(338,'ENG-FIRE-LEAD-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(339,'ENG-FIRE-LEAD-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(340,'ENG-FIRE-MC',TRUE,'Supervisor','ENG-FIRE-LEAD-MC');
INSERT INTO eng_leave_approval_chain VALUES(341,'ENG-FIRE-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(342,'ENG-FIRE-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(343,'ENG-FIRE-DRV-MC',TRUE,'Supervisor','ENG-FIRE-LEAD-MC');
INSERT INTO eng_leave_approval_chain VALUES(344,'ENG-FIRE-DRV-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(345,'ENG-FIRE-DRV-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(346,'ENG-WATSAN-COORD-MC',TRUE,'Supervisor','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(347,'ENG-WATSAN-COORD-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(348,'ENG-WATSAN-COORD-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(349,'ENG-WATSAN-ASST-MC',TRUE,'Supervisor','ENG-WATSAN-COORD-MC');
INSERT INTO eng_leave_approval_chain VALUES(350,'ENG-WATSAN-ASST-MC',2,'Head of Department','ENG-DIR-MC');
INSERT INTO eng_leave_approval_chain VALUES(351,'ENG-WATSAN-ASST-MC',3,'Head of Council','TOWN-CLERK-MC');
INSERT INTO eng_leave_approval_chain VALUES(352,'CITY-CLERK-CC',TRUE,'Supervisor',NULL);
INSERT INTO eng_leave_approval_chain VALUES(353,'CITY-CLERK-CC',2,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(354,'CITY-CLERK-CC',3,'Head of Council',NULL);
INSERT INTO eng_leave_approval_chain VALUES(355,'ENG-DIR-CC',TRUE,'Supervisor','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(356,'ENG-DIR-CC',2,'Head of Department','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(357,'ENG-DIR-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(358,'ENG-CONSTR-ASSTDIR-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(359,'ENG-CONSTR-ASSTDIR-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(360,'ENG-CONSTR-ASSTDIR-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(361,'ENG-ROADS-ASSTDIR-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(362,'ENG-ROADS-ASSTDIR-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(363,'ENG-ROADS-ASSTDIR-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(364,'ENG-ELEC-CHIEF-CC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(365,'ENG-ELEC-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(366,'ENG-ELEC-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(367,'ENG-ELEC-ENG07-CC',TRUE,'Supervisor','ENG-ELEC-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(368,'ENG-ELEC-ENG07-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(369,'ENG-ELEC-ENG07-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(370,'ENG-ELEC-ASST-CC',TRUE,'Supervisor','ENG-ELEC-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(371,'ENG-ELEC-ASST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(372,'ENG-ELEC-ASST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(373,'ENG-ELEC-SEN-SUPT-CC',TRUE,'Supervisor','ENG-ELEC-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(374,'ENG-ELEC-SEN-SUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(375,'ENG-ELEC-SEN-SUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(376,'ENG-ELEC-SUPT-CC',TRUE,'Supervisor','ENG-ELEC-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(377,'ENG-ELEC-SUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(378,'ENG-ELEC-SUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(379,'ENG-ELEC-ASSTSUPT-CC',TRUE,'Supervisor','ENG-ELEC-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(380,'ENG-ELEC-ASSTSUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(381,'ENG-ELEC-ASSTSUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(382,'ENG-ELEC-SENASSIST-CC',TRUE,'Supervisor','ENG-ELEC-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(383,'ENG-ELEC-SENASSIST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(384,'ENG-ELEC-SENASSIST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(385,'ENG-ELEC-WORKSUP-CC',TRUE,'Supervisor','ENG-ELEC-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(386,'ENG-ELEC-WORKSUP-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(387,'ENG-ELEC-WORKSUP-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(388,'ENG-ELEC-TECH-CC',TRUE,'Supervisor','ENG-ELEC-WORKSUP-CC');
INSERT INTO eng_leave_approval_chain VALUES(389,'ENG-ELEC-TECH-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(390,'ENG-ELEC-TECH-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(391,'ENG-ELEC-FOREMAN-CC',TRUE,'Supervisor','ENG-ELEC-WORKSUP-CC');
INSERT INTO eng_leave_approval_chain VALUES(392,'ENG-ELEC-FOREMAN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(393,'ENG-ELEC-FOREMAN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(394,'ENG-ELEC-ASSTFORE-CC',TRUE,'Supervisor','ENG-ELEC-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(395,'ENG-ELEC-ASSTFORE-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(396,'ENG-ELEC-ASSTFORE-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(397,'ENG-QSURV-CHIEF-CC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(398,'ENG-QSURV-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(399,'ENG-QSURV-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(400,'ENG-QSURV07-CC',TRUE,'Supervisor','ENG-QSURV-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(401,'ENG-QSURV07-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(402,'ENG-QSURV07-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(403,'ENG-QSURV-ASST-CC',TRUE,'Supervisor','ENG-QSURV07-CC');
INSERT INTO eng_leave_approval_chain VALUES(404,'ENG-QSURV-ASST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(405,'ENG-QSURV-ASST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(406,'ENG-ARCH-CHIEF-CC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(407,'ENG-ARCH-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(408,'ENG-ARCH-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(409,'ENG-ARCH07-CC',TRUE,'Supervisor','ENG-ARCH-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(410,'ENG-ARCH07-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(411,'ENG-ARCH07-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(412,'ENG-ARCH-ASST-CC',TRUE,'Supervisor','ENG-ARCH07-CC');
INSERT INTO eng_leave_approval_chain VALUES(413,'ENG-ARCH-ASST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(414,'ENG-ARCH-ASST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(415,'ENG-ARCH-DRAFT-CC',TRUE,'Supervisor','ENG-ARCH07-CC');
INSERT INTO eng_leave_approval_chain VALUES(416,'ENG-ARCH-DRAFT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(417,'ENG-ARCH-DRAFT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(418,'ENG-MAINT-SUPT-CC',TRUE,'Supervisor','ENG-CONSTR-ASSTDIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(419,'ENG-MAINT-SUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(420,'ENG-MAINT-SUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(421,'ENG-MAINT-ASSTSUPT-CC',TRUE,'Supervisor','ENG-MAINT-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(422,'ENG-MAINT-ASSTSUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(423,'ENG-MAINT-ASSTSUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(424,'ENG-MAINT-ASSTSUPT2-CC',TRUE,'Supervisor','ENG-MAINT-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(425,'ENG-MAINT-ASSTSUPT2-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(426,'ENG-MAINT-ASSTSUPT2-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(427,'ENG-MAINT-FOREMAN-CC',TRUE,'Supervisor','ENG-MAINT-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(428,'ENG-MAINT-FOREMAN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(429,'ENG-MAINT-FOREMAN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(430,'ENG-MAINT-PLUM-CC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(431,'ENG-MAINT-PLUM-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(432,'ENG-MAINT-PLUM-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(433,'ENG-MAINT-BRICK-CC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(434,'ENG-MAINT-BRICK-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(435,'ENG-MAINT-BRICK-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(436,'ENG-MAINT-CARP-CC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(437,'ENG-MAINT-CARP-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(438,'ENG-MAINT-CARP-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(439,'ENG-MAINT-PAINT-CC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(440,'ENG-MAINT-PAINT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(441,'ENG-MAINT-PAINT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(442,'ENG-MAINT-GENWORK-CC',TRUE,'Supervisor','ENG-MAINT-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(443,'ENG-MAINT-GENWORK-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(444,'ENG-MAINT-GENWORK-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(445,'ENG-PARK-MGR-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(446,'ENG-PARK-MGR-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(447,'ENG-PARK-MGR-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(448,'ENG-PARK-SUPT-CC',TRUE,'Supervisor','ENG-PARK-MGR-CC');
INSERT INTO eng_leave_approval_chain VALUES(449,'ENG-PARK-SUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(450,'ENG-PARK-SUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(451,'ENG-PARK-ASSTSUPT-CC',TRUE,'Supervisor','ENG-PARK-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(452,'ENG-PARK-ASSTSUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(453,'ENG-PARK-ASSTSUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(454,'ENG-PARK-FOREMAN-CC',TRUE,'Supervisor','ENG-PARK-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(455,'ENG-PARK-FOREMAN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(456,'ENG-PARK-FOREMAN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(457,'ENG-PARK-SUP-CC',TRUE,'Supervisor','ENG-PARK-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(458,'ENG-PARK-SUP-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(459,'ENG-PARK-SUP-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(460,'ENG-PARK-ASSTFORE-CC',TRUE,'Supervisor','ENG-PARK-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(461,'ENG-PARK-ASSTFORE-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(462,'ENG-PARK-ASSTFORE-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(463,'ENG-PARK-WORK-CC',TRUE,'Supervisor','ENG-PARK-SUP-CC');
INSERT INTO eng_leave_approval_chain VALUES(464,'ENG-PARK-WORK-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(465,'ENG-PARK-WORK-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(466,'ENG-MECH-CHIEF-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(467,'ENG-MECH-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(468,'ENG-MECH-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(469,'ENG-MECH07-CC',TRUE,'Supervisor','ENG-MECH-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(470,'ENG-MECH07-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(471,'ENG-MECH07-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(472,'ENG-MECH-ASST-CC',TRUE,'Supervisor','ENG-MECH07-CC');
INSERT INTO eng_leave_approval_chain VALUES(473,'ENG-MECH-ASST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(474,'ENG-MECH-ASST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(475,'ENG-MECH-SUPT-CC',TRUE,'Supervisor','ENG-MECH07-CC');
INSERT INTO eng_leave_approval_chain VALUES(476,'ENG-MECH-SUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(477,'ENG-MECH-SUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(478,'ENG-MECH-ASSTSUPT-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(479,'ENG-MECH-ASSTSUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(480,'ENG-MECH-ASSTSUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(481,'ENG-MECH-ASSIST-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(482,'ENG-MECH-ASSIST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(483,'ENG-MECH-ASSIST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(484,'ENG-MECH-AUTO-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(485,'ENG-MECH-AUTO-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(486,'ENG-MECH-AUTO-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(487,'ENG-MECH-TECH-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(488,'ENG-MECH-TECH-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(489,'ENG-MECH-TECH-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(490,'ENG-MECH-FOREMAN-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(491,'ENG-MECH-FOREMAN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(492,'ENG-MECH-FOREMAN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(493,'ENG-MECH-ASSTFORE-CC',TRUE,'Supervisor','ENG-MECH-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(494,'ENG-MECH-ASSTFORE-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(495,'ENG-MECH-ASSTFORE-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(496,'ENG-MECH-PLANT-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(497,'ENG-MECH-PLANT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(498,'ENG-MECH-PLANT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(499,'ENG-MECH-HANDY-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(500,'ENG-MECH-HANDY-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(501,'ENG-MECH-HANDY-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(502,'ENG-MECH-WELDER-CC',TRUE,'Supervisor','ENG-MECH-SUPT-CC');
INSERT INTO eng_leave_approval_chain VALUES(503,'ENG-MECH-WELDER-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(504,'ENG-MECH-WELDER-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(505,'ENG-CIVIL-CHIEF-CC',TRUE,'Supervisor','ENG-ROADS-ASSTDIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(506,'ENG-CIVIL-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(507,'ENG-CIVIL-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(508,'ENG-CIVIL06-CC',TRUE,'Supervisor','ENG-CIVIL-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(509,'ENG-CIVIL06-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(510,'ENG-CIVIL06-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(511,'ENG-CIVIL07-CC',TRUE,'Supervisor','ENG-CIVIL-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(512,'ENG-CIVIL07-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(513,'ENG-CIVIL07-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(514,'ENG-CIVIL-ASST-CC',TRUE,'Supervisor','ENG-CIVIL06-CC');
INSERT INTO eng_leave_approval_chain VALUES(515,'ENG-CIVIL-ASST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(516,'ENG-CIVIL-ASST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(517,'ENG-CIVIL-HIGHWAY-CC',TRUE,'Supervisor','ENG-CIVIL06-CC');
INSERT INTO eng_leave_approval_chain VALUES(518,'ENG-CIVIL-HIGHWAY-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(519,'ENG-CIVIL-HIGHWAY-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(520,'ENG-CIVIL-SENASSIST-CC',TRUE,'Supervisor','ENG-CIVIL06-CC');
INSERT INTO eng_leave_approval_chain VALUES(521,'ENG-CIVIL-SENASSIST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(522,'ENG-CIVIL-SENASSIST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(523,'ENG-CIVIL-ASSTSUPT-CC',TRUE,'Supervisor','ENG-CIVIL-HIGHWAY-CC');
INSERT INTO eng_leave_approval_chain VALUES(524,'ENG-CIVIL-ASSTSUPT-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(525,'ENG-CIVIL-ASSTSUPT-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(526,'ENG-CIVIL-ASSIST-CC',TRUE,'Supervisor','ENG-CIVIL06-CC');
INSERT INTO eng_leave_approval_chain VALUES(527,'ENG-CIVIL-ASSIST-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(528,'ENG-CIVIL-ASSIST-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(529,'ENG-CIVIL-FOREMAN-CC',TRUE,'Supervisor','ENG-CIVIL06-CC');
INSERT INTO eng_leave_approval_chain VALUES(530,'ENG-CIVIL-FOREMAN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(531,'ENG-CIVIL-FOREMAN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(532,'ENG-CIVIL-ASSTFORE-CC',TRUE,'Supervisor','ENG-CIVIL-FOREMAN-CC');
INSERT INTO eng_leave_approval_chain VALUES(533,'ENG-CIVIL-ASSTFORE-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(534,'ENG-CIVIL-ASSTFORE-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(535,'ENG-FIRE-CHIEF-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(536,'ENG-FIRE-CHIEF-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(537,'ENG-FIRE-CHIEF-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(538,'ENG-FIRE-DEPUTY-CC',TRUE,'Supervisor','ENG-FIRE-CHIEF-CC');
INSERT INTO eng_leave_approval_chain VALUES(539,'ENG-FIRE-DEPUTY-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(540,'ENG-FIRE-DEPUTY-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(541,'ENG-FIRE-DIV-CC',TRUE,'Supervisor','ENG-FIRE-DEPUTY-CC');
INSERT INTO eng_leave_approval_chain VALUES(542,'ENG-FIRE-DIV-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(543,'ENG-FIRE-DIV-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(544,'ENG-FIRE-ASSTDIV-CC',TRUE,'Supervisor','ENG-FIRE-DIV-CC');
INSERT INTO eng_leave_approval_chain VALUES(545,'ENG-FIRE-ASSTDIV-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(546,'ENG-FIRE-ASSTDIV-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(547,'ENG-FIRE-STN-CC',TRUE,'Supervisor','ENG-FIRE-DIV-CC');
INSERT INTO eng_leave_approval_chain VALUES(548,'ENG-FIRE-STN-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(549,'ENG-FIRE-STN-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(550,'ENG-FIRE-SUB-CC',TRUE,'Supervisor','ENG-FIRE-STN-CC');
INSERT INTO eng_leave_approval_chain VALUES(551,'ENG-FIRE-SUB-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(552,'ENG-FIRE-SUB-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(553,'ENG-FIRE-LEAD-CC',TRUE,'Supervisor','ENG-FIRE-SUB-CC');
INSERT INTO eng_leave_approval_chain VALUES(554,'ENG-FIRE-LEAD-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(555,'ENG-FIRE-LEAD-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(556,'ENG-FIRE-CC',TRUE,'Supervisor','ENG-FIRE-LEAD-CC');
INSERT INTO eng_leave_approval_chain VALUES(557,'ENG-FIRE-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(558,'ENG-FIRE-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(559,'ENG-FIRE-DRV-CC',TRUE,'Supervisor','ENG-FIRE-LEAD-CC');
INSERT INTO eng_leave_approval_chain VALUES(560,'ENG-FIRE-DRV-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(561,'ENG-FIRE-DRV-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(562,'ENG-WATSAN-COORD-CC',TRUE,'Supervisor','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(563,'ENG-WATSAN-COORD-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(564,'ENG-WATSAN-COORD-CC',3,'Head of Council','CITY-CLERK-CC');
INSERT INTO eng_leave_approval_chain VALUES(565,'ENG-WATSAN-ENG-CC',TRUE,'Supervisor','ENG-WATSAN-COORD-CC');
INSERT INTO eng_leave_approval_chain VALUES(566,'ENG-WATSAN-ENG-CC',2,'Head of Department','ENG-DIR-CC');
INSERT INTO eng_leave_approval_chain VALUES(567,'ENG-WATSAN-ENG-CC',3,'Head of Council','CITY-CLERK-CC');
