INSERT INTO eng_units VALUES(1,'Council Administration','TC-ADMIN',NULL,TRUE);
INSERT INTO eng_units VALUES(2,'Engineering Section','TC-ENG',NULL,TRUE);
INSERT INTO eng_units VALUES(3,'Electrical Unit','TC-ELEC',NULL,TRUE);
INSERT INTO eng_units VALUES(4,'Maintenance Unit','TC-MAINT',NULL,TRUE);
INSERT INTO eng_units VALUES(5,'Quantity Surveying Unit','TC-QS',NULL,TRUE);
INSERT INTO eng_units VALUES(6,'Architecture Unit','TC-ARCH',NULL,TRUE);
INSERT INTO eng_units VALUES(7,'Parks and Gardens Unit','TC-PARK',NULL,TRUE);
INSERT INTO eng_units VALUES(8,'Roads and Drainages Unit','TC-ROADS',NULL,TRUE);
INSERT INTO eng_units VALUES(9,'Mechanical Services Unit','TC-MECH',NULL,TRUE);
INSERT INTO eng_units VALUES(10,'Vehicle Maintenance Services Sub-Unit','TC-VMS',NULL,TRUE);
INSERT INTO eng_units VALUES(11,'Fire and Rescue Services Unit','TC-FIRE',NULL,TRUE);
INSERT INTO eng_units VALUES(12,'Rural Water and Sanitation Unit','TC-WATSAN',NULL,TRUE);
INSERT INTO eng_units VALUES(13,'Council Administration','MC-ADMIN',NULL,2);
INSERT INTO eng_units VALUES(14,'Engineering Department','MC-ENG-DEPT',NULL,2);
INSERT INTO eng_units VALUES(15,'Construction & Maintenance Section','MC-CONSTR',NULL,2);
INSERT INTO eng_units VALUES(16,'Electrical Engineering Unit','MC-ELEC',NULL,2);
INSERT INTO eng_units VALUES(17,'Quantity Surveying Unit','MC-QS',NULL,2);
INSERT INTO eng_units VALUES(18,'Architecture Unit','MC-ARCH',NULL,2);
INSERT INTO eng_units VALUES(19,'Maintenance Unit','MC-MAINT',NULL,2);
INSERT INTO eng_units VALUES(20,'Parks & Gardens Unit','MC-PARK',NULL,2);
INSERT INTO eng_units VALUES(21,'Mechanical Services Unit','MC-MECH',NULL,2);
INSERT INTO eng_units VALUES(22,'Roads & Drainages Section','MC-ROADS',NULL,2);
INSERT INTO eng_units VALUES(23,'Fire & Rescue Services Unit','MC-FIRE',NULL,2);
INSERT INTO eng_units VALUES(24,'Rural Water & Sanitation Unit','MC-WATSAN',NULL,2);
INSERT INTO eng_units VALUES(25,'Council Administration','CC-ADMIN',NULL,3);
INSERT INTO eng_units VALUES(26,'Engineering Department','CC-ENG-DEPT',NULL,3);
INSERT INTO eng_units VALUES(27,'Construction & Maintenance Section','CC-CONSTR',NULL,3);
INSERT INTO eng_units VALUES(28,'Electrical Engineering Unit','CC-ELEC',NULL,3);
INSERT INTO eng_units VALUES(29,'Quantity Surveying Unit','CC-QS',NULL,3);
INSERT INTO eng_units VALUES(30,'Architecture Unit','CC-ARCH',NULL,3);
INSERT INTO eng_units VALUES(31,'Maintenance Unit','CC-MAINT',NULL,3);
INSERT INTO eng_units VALUES(32,'Parks & Gardens Unit','CC-PARK',NULL,3);
INSERT INTO eng_units VALUES(33,'Mechanical Services Unit','CC-MECH',NULL,3);
INSERT INTO eng_units VALUES(34,'Roads & Drainages Section','CC-ROADS',NULL,3);
INSERT INTO eng_units VALUES(35,'Fire & Rescue Services Unit','CC-FIRE',NULL,3);
INSERT INTO eng_units VALUES(36,'Rural Water & Sanitation Unit','CC-WATSAN',NULL,3);
