INSERT INTO finance_leave_approval_chain VALUES(1,'COUNCIL-SEC-TOWN',TRUE,'Supervisor',NULL);
INSERT INTO finance_leave_approval_chain VALUES(2,'COUNCIL-SEC-TOWN',2,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(3,'COUNCIL-SEC-TOWN',3,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(4,'FIN-DIR-TOWN',TRUE,'Supervisor','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(5,'FIN-DIR-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(6,'FIN-DIR-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(7,'FIN-CHACC-TOWN',TRUE,'Supervisor','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(8,'FIN-CHACC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(9,'FIN-CHACC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(10,'FIN-ACC-TOWN',TRUE,'Supervisor','FIN-CHACC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(11,'FIN-ACC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(12,'FIN-ACC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(13,'FIN-ASSTACC-TOWN',TRUE,'Supervisor','FIN-ACC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(14,'FIN-ASSTACC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(15,'FIN-ASSTACC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(16,'FIN-STORE-TOWN',TRUE,'Supervisor','FIN-CHACC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(17,'FIN-STORE-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(18,'FIN-STORE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(19,'FIN-CHLIC-TOWN',TRUE,'Supervisor','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(20,'FIN-CHLIC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(21,'FIN-CHLIC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(22,'FIN-LIC-TOWN',TRUE,'Supervisor','FIN-CHLIC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(23,'FIN-LIC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(24,'FIN-LIC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(25,'FIN-CASH-TOWN',TRUE,'Supervisor','FIN-LIC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(26,'FIN-CASH-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(27,'FIN-CASH-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(28,'FIN-REV-TOWN',TRUE,'Supervisor','FIN-CASH-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(29,'FIN-REV-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(30,'FIN-REV-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(31,'FIN-HLTH-ASSTACC-TOWN',TRUE,'Supervisor','FIN-ACC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(32,'FIN-HLTH-ASSTACC-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(33,'FIN-HLTH-ASSTACC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(34,'FIN-HLTH-ACCS-TOWN',TRUE,'Supervisor','FIN-HLTH-ASSTACC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(35,'FIN-HLTH-ACCS-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(36,'FIN-HLTH-ACCS-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(37,'FIN-HLTH-STORE-TOWN',TRUE,'Supervisor','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(38,'FIN-HLTH-STORE-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(39,'FIN-HLTH-STORE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(40,'FIN-HLTH-ASSTSTORE-TOWN',TRUE,'Supervisor','FIN-HLTH-STORE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(41,'FIN-HLTH-ASSTSTORE-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(42,'FIN-HLTH-ASSTSTORE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(43,'FIN-COMM-MGR-TOWN',TRUE,'Supervisor','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(44,'FIN-COMM-MGR-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(45,'FIN-COMM-MGR-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(46,'FIN-COMM-ASSTMGR-TOWN',TRUE,'Supervisor','FIN-COMM-MGR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(47,'FIN-COMM-ASSTMGR-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(48,'FIN-COMM-ASSTMGR-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(49,'FIN-COMM-HOUSE-TOWN',TRUE,'Supervisor','FIN-COMM-ASSTMGR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(50,'FIN-COMM-HOUSE-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(51,'FIN-COMM-HOUSE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(52,'FIN-COMM-RECEPT-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(53,'FIN-COMM-RECEPT-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(54,'FIN-COMM-RECEPT-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(55,'FIN-COMM-BARMAN-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(56,'FIN-COMM-BARMAN-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(57,'FIN-COMM-BARMAN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(58,'FIN-COMM-WAITER-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(59,'FIN-COMM-WAITER-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(60,'FIN-COMM-WAITER-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(61,'FIN-COMM-COOK-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(62,'FIN-COMM-COOK-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(63,'FIN-COMM-COOK-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(64,'FIN-COMM-CHEF-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(65,'FIN-COMM-CHEF-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(66,'FIN-COMM-CHEF-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(67,'FIN-COMM-LAUNDRY-TOWN',TRUE,'Supervisor','FIN-COMM-HOUSE-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(68,'FIN-COMM-LAUNDRY-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(69,'FIN-COMM-LAUNDRY-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(70,'FIN-STORE-OFF-TOWN',TRUE,'Supervisor','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(71,'FIN-STORE-OFF-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(72,'FIN-STORE-OFF-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(73,'FIN-STORE-ASST-TOWN',TRUE,'Supervisor','FIN-STORE-OFF-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(74,'FIN-STORE-ASST-TOWN',2,'Head of Department','FIN-DIR-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(75,'FIN-STORE-ASST-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO finance_leave_approval_chain VALUES(76,'TOWN-CLERK-MUN',TRUE,'Supervisor',NULL);
INSERT INTO finance_leave_approval_chain VALUES(77,'TOWN-CLERK-MUN',2,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(78,'TOWN-CLERK-MUN',3,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(79,'FIN-DIR-MUN',TRUE,'Supervisor','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(80,'FIN-DIR-MUN',2,'Head of Department','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(81,'FIN-DIR-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(82,'FIN-CHACC-MUN',TRUE,'Supervisor','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(83,'FIN-CHACC-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(84,'FIN-CHACC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(85,'FIN-SNRACC-MUN',TRUE,'Supervisor','FIN-CHACC-MUN');
INSERT INTO finance_leave_approval_chain VALUES(86,'FIN-SNRACC-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(87,'FIN-SNRACC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(88,'FIN-ACC-MUN',TRUE,'Supervisor','FIN-SNRACC-MUN');
INSERT INTO finance_leave_approval_chain VALUES(89,'FIN-ACC-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(90,'FIN-ACC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(91,'FIN-ASSTACC-MUN',TRUE,'Supervisor','FIN-ACC-MUN');
INSERT INTO finance_leave_approval_chain VALUES(92,'FIN-ASSTACC-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(93,'FIN-ASSTACC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(94,'FIN-ACCS-MUN',TRUE,'Supervisor','FIN-ASSTACC-MUN');
INSERT INTO finance_leave_approval_chain VALUES(95,'FIN-ACCS-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(96,'FIN-ACCS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(97,'FIN-REV-MUN',TRUE,'Supervisor','FIN-ACCS-MUN');
INSERT INTO finance_leave_approval_chain VALUES(98,'FIN-REV-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(99,'FIN-REV-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(100,'FIN-STORE-CTRL-MUN',TRUE,'Supervisor','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(101,'FIN-STORE-CTRL-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(102,'FIN-STORE-CTRL-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(103,'FIN-STORE-OFF-MUN',TRUE,'Supervisor','FIN-STORE-CTRL-MUN');
INSERT INTO finance_leave_approval_chain VALUES(104,'FIN-STORE-OFF-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(105,'FIN-STORE-OFF-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(106,'FIN-STORE-ASST-MUN',TRUE,'Supervisor','FIN-STORE-OFF-MUN');
INSERT INTO finance_leave_approval_chain VALUES(107,'FIN-STORE-ASST-MUN',2,'Head of Department','FIN-DIR-MUN');
INSERT INTO finance_leave_approval_chain VALUES(108,'FIN-STORE-ASST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO finance_leave_approval_chain VALUES(109,'TOWN-CLERK-CITY',TRUE,'Supervisor',NULL);
INSERT INTO finance_leave_approval_chain VALUES(110,'TOWN-CLERK-CITY',2,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(111,'TOWN-CLERK-CITY',3,'Head of Council',NULL);
INSERT INTO finance_leave_approval_chain VALUES(112,'FIN-DIR-CITY',TRUE,'Supervisor','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(113,'FIN-DIR-CITY',2,'Head of Department','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(114,'FIN-DIR-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(115,'FIN-ADIR-REV-CITY',TRUE,'Supervisor','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(116,'FIN-ADIR-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(117,'FIN-ADIR-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(118,'FIN-CHACC-REV-CITY',TRUE,'Supervisor','FIN-ADIR-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(119,'FIN-CHACC-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(120,'FIN-CHACC-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(121,'FIN-SNRACC-REV-CITY',TRUE,'Supervisor','FIN-CHACC-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(122,'FIN-SNRACC-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(123,'FIN-SNRACC-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(124,'FIN-ACC-REV-CITY',TRUE,'Supervisor','FIN-SNRACC-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(125,'FIN-ACC-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(126,'FIN-ACC-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(127,'FIN-ASSTACC-REV-CITY',TRUE,'Supervisor','FIN-ACC-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(128,'FIN-ASSTACC-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(129,'FIN-ASSTACC-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(130,'FIN-ACCS-REV-CITY',TRUE,'Supervisor','FIN-ASSTACC-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(131,'FIN-ACCS-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(132,'FIN-ACCS-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(133,'FIN-REV-CITY',TRUE,'Supervisor','FIN-ACCS-REV-CITY');
INSERT INTO finance_leave_approval_chain VALUES(134,'FIN-REV-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(135,'FIN-REV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(136,'FIN-ADIR-EXP-CITY',TRUE,'Supervisor','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(137,'FIN-ADIR-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(138,'FIN-ADIR-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(139,'FIN-CHACC-EXP-CITY',TRUE,'Supervisor','FIN-ADIR-EXP-CITY');
INSERT INTO finance_leave_approval_chain VALUES(140,'FIN-CHACC-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(141,'FIN-CHACC-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(142,'FIN-SNRACC-EXP-CITY',TRUE,'Supervisor','FIN-CHACC-EXP-CITY');
INSERT INTO finance_leave_approval_chain VALUES(143,'FIN-SNRACC-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(144,'FIN-SNRACC-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(145,'FIN-ACC-EXP-CITY',TRUE,'Supervisor','FIN-SNRACC-EXP-CITY');
INSERT INTO finance_leave_approval_chain VALUES(146,'FIN-ACC-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(147,'FIN-ACC-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(148,'FIN-ASSTACC-EXP-CITY',TRUE,'Supervisor','FIN-ACC-EXP-CITY');
INSERT INTO finance_leave_approval_chain VALUES(149,'FIN-ASSTACC-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(150,'FIN-ASSTACC-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(151,'FIN-ACCS-EXP-CITY',TRUE,'Supervisor','FIN-ASSTACC-EXP-CITY');
INSERT INTO finance_leave_approval_chain VALUES(152,'FIN-ACCS-EXP-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(153,'FIN-ACCS-EXP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(154,'FIN-STORE-CTRL-CITY',TRUE,'Supervisor','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(155,'FIN-STORE-CTRL-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(156,'FIN-STORE-CTRL-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO finance_leave_approval_chain VALUES(157,'FIN-STORE-OFF-CITY',TRUE,'Supervisor','FIN-STORE-CTRL-CITY');
INSERT INTO finance_leave_approval_chain VALUES(158,'FIN-STORE-OFF-CITY',2,'Head of Department','FIN-DIR-CITY');
INSERT INTO finance_leave_approval_chain VALUES(159,'FIN-STORE-OFF-CITY',3,'Head of Council','TOWN-CLERK-CITY');
