INSERT INTO health_leave_approval_chain VALUES(1,'COUNCIL-SEC-TOWN',TRUE,'Supervisor',NULL);
INSERT INTO health_leave_approval_chain VALUES(2,'COUNCIL-SEC-TOWN',2,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(3,'COUNCIL-SEC-TOWN',3,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(4,'HLTH-ADIR-TOWN',TRUE,'Supervisor','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(5,'HLTH-ADIR-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(6,'HLTH-ADIR-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(7,'HLTH-ENV-TECH-TOWN',TRUE,'Supervisor','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(8,'HLTH-ENV-TECH-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(9,'HLTH-ENV-TECH-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(10,'HLTH-SNR-HIO-TOWN',TRUE,'Supervisor','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(11,'HLTH-SNR-HIO-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(12,'HLTH-SNR-HIO-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(13,'HLTH-HI-TOWN',TRUE,'Supervisor','HLTH-SNR-HIO-TOWN');
INSERT INTO health_leave_approval_chain VALUES(14,'HLTH-HI-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(15,'HLTH-HI-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(16,'HLTH-FUN-SUP-TOWN',TRUE,'Supervisor','HLTH-SNR-HIO-TOWN');
INSERT INTO health_leave_approval_chain VALUES(17,'HLTH-FUN-SUP-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(18,'HLTH-FUN-SUP-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(19,'HLTH-GENWORK-TOWN',TRUE,'Supervisor','HLTH-FUN-SUP-TOWN');
INSERT INTO health_leave_approval_chain VALUES(20,'HLTH-GENWORK-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(21,'HLTH-GENWORK-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(22,'HLTH-HEALTH-EDU-TOWN',TRUE,'Supervisor','HLTH-SNR-HIO-TOWN');
INSERT INTO health_leave_approval_chain VALUES(23,'HLTH-HEALTH-EDU-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(24,'HLTH-HEALTH-EDU-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(25,'HLTH-CLEAN-SUP-TOWN',TRUE,'Supervisor','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(26,'HLTH-CLEAN-SUP-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(27,'HLTH-CLEAN-SUP-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(28,'HLTH-ASST-CLEAN-TOWN',TRUE,'Supervisor','HLTH-CLEAN-SUP-TOWN');
INSERT INTO health_leave_approval_chain VALUES(29,'HLTH-ASST-CLEAN-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(30,'HLTH-ASST-CLEAN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(31,'HLTH-DRIVER-WASTE-TOWN',TRUE,'Supervisor','HLTH-ASST-CLEAN-TOWN');
INSERT INTO health_leave_approval_chain VALUES(32,'HLTH-DRIVER-WASTE-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(33,'HLTH-DRIVER-WASTE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(34,'HLTH-FUN-SUP-SVC-TOWN',TRUE,'Supervisor','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(35,'HLTH-FUN-SUP-SVC-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(36,'HLTH-FUN-SUP-SVC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(37,'HLTH-ASST-FUN-TOWN',TRUE,'Supervisor','HLTH-FUN-SUP-SVC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(38,'HLTH-ASST-FUN-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(39,'HLTH-ASST-FUN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(40,'HLTH-SANITARY-TOWN',TRUE,'Supervisor','HLTH-ASST-FUN-TOWN');
INSERT INTO health_leave_approval_chain VALUES(41,'HLTH-SANITARY-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(42,'HLTH-SANITARY-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(43,'HLTH-GRAVE-TOWN',TRUE,'Supervisor','HLTH-ASST-FUN-TOWN');
INSERT INTO health_leave_approval_chain VALUES(44,'HLTH-GRAVE-TOWN',2,'Head of Department','HLTH-ADIR-TOWN');
INSERT INTO health_leave_approval_chain VALUES(45,'HLTH-GRAVE-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO health_leave_approval_chain VALUES(46,'TOWN-CLERK-MUN',TRUE,'Supervisor',NULL);
INSERT INTO health_leave_approval_chain VALUES(47,'TOWN-CLERK-MUN',2,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(48,'TOWN-CLERK-MUN',3,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(49,'HLTH-ADIR-MUN',TRUE,'Supervisor','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(50,'HLTH-ADIR-MUN',2,'Head of Department','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(51,'HLTH-ADIR-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(52,'HLTH-CHIEF-HIO-MUN',TRUE,'Supervisor','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(53,'HLTH-CHIEF-HIO-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(54,'HLTH-CHIEF-HIO-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(55,'HLTH-SNR-HIO-MUN',TRUE,'Supervisor','HLTH-CHIEF-HIO-MUN');
INSERT INTO health_leave_approval_chain VALUES(56,'HLTH-SNR-HIO-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(57,'HLTH-SNR-HIO-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(58,'HLTH-HI-MUN',TRUE,'Supervisor','HLTH-SNR-HIO-MUN');
INSERT INTO health_leave_approval_chain VALUES(59,'HLTH-HI-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(60,'HLTH-HI-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(61,'HLTH-FIELD-DRIVER-MUN',TRUE,'Supervisor','HLTH-HI-MUN');
INSERT INTO health_leave_approval_chain VALUES(62,'HLTH-FIELD-DRIVER-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(63,'HLTH-FIELD-DRIVER-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(64,'HLTH-SNR-HPO-MUN',TRUE,'Supervisor','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(65,'HLTH-SNR-HPO-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(66,'HLTH-SNR-HPO-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(67,'HLTH-HPO-MUN',TRUE,'Supervisor','HLTH-SNR-HPO-MUN');
INSERT INTO health_leave_approval_chain VALUES(68,'HLTH-HPO-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(69,'HLTH-HPO-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(70,'HLTH-ASST-HPO-MUN',TRUE,'Supervisor','HLTH-HPO-MUN');
INSERT INTO health_leave_approval_chain VALUES(71,'HLTH-ASST-HPO-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(72,'HLTH-ASST-HPO-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(73,'HLTH-HEALTH-EDU-ASST-MUN',TRUE,'Supervisor','HLTH-ASST-HPO-MUN');
INSERT INTO health_leave_approval_chain VALUES(74,'HLTH-HEALTH-EDU-ASST-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(75,'HLTH-HEALTH-EDU-ASST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(76,'HLTH-CLEAN-MGR-MUN',TRUE,'Supervisor','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(77,'HLTH-CLEAN-MGR-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(78,'HLTH-CLEAN-MGR-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(79,'HLTH-CLEAN-SUP-MUN',TRUE,'Supervisor','HLTH-CLEAN-MGR-MUN');
INSERT INTO health_leave_approval_chain VALUES(80,'HLTH-CLEAN-SUP-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(81,'HLTH-CLEAN-SUP-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(82,'HLTH-ASST-CLEAN-MUN',TRUE,'Supervisor','HLTH-CLEAN-SUP-MUN');
INSERT INTO health_leave_approval_chain VALUES(83,'HLTH-ASST-CLEAN-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(84,'HLTH-ASST-CLEAN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(85,'HLTH-PEST-SUP-MUN',TRUE,'Supervisor','HLTH-CLEAN-MGR-MUN');
INSERT INTO health_leave_approval_chain VALUES(86,'HLTH-PEST-SUP-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(87,'HLTH-PEST-SUP-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(88,'HLTH-ASST-PEST-MUN',TRUE,'Supervisor','HLTH-PEST-SUP-MUN');
INSERT INTO health_leave_approval_chain VALUES(89,'HLTH-ASST-PEST-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(90,'HLTH-ASST-PEST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(91,'HLTH-CLEAN-FORE-MUN',TRUE,'Supervisor','HLTH-CLEAN-MGR-MUN');
INSERT INTO health_leave_approval_chain VALUES(92,'HLTH-CLEAN-FORE-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(93,'HLTH-CLEAN-FORE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(94,'HLTH-WASTE-DRIVER-MUN',TRUE,'Supervisor','HLTH-CLEAN-FORE-MUN');
INSERT INTO health_leave_approval_chain VALUES(95,'HLTH-WASTE-DRIVER-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(96,'HLTH-WASTE-DRIVER-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(97,'HLTH-FUN-SUP-MUN',TRUE,'Supervisor','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(98,'HLTH-FUN-SUP-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(99,'HLTH-FUN-SUP-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(100,'HLTH-ASST-FUN-MUN',TRUE,'Supervisor','HLTH-FUN-SUP-MUN');
INSERT INTO health_leave_approval_chain VALUES(101,'HLTH-ASST-FUN-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(102,'HLTH-ASST-FUN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(103,'HLTH-SANITARY-MUN',TRUE,'Supervisor','HLTH-ASST-FUN-MUN');
INSERT INTO health_leave_approval_chain VALUES(104,'HLTH-SANITARY-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(105,'HLTH-SANITARY-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(106,'HLTH-GRAVE-MUN',TRUE,'Supervisor','HLTH-ASST-FUN-MUN');
INSERT INTO health_leave_approval_chain VALUES(107,'HLTH-GRAVE-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(108,'HLTH-GRAVE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(109,'HLTH-HIS-MUN',TRUE,'Supervisor','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(110,'HLTH-HIS-MUN',2,'Head of Department','HLTH-ADIR-MUN');
INSERT INTO health_leave_approval_chain VALUES(111,'HLTH-HIS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO health_leave_approval_chain VALUES(112,'TOWN-CLERK-CITY',TRUE,'Supervisor',NULL);
INSERT INTO health_leave_approval_chain VALUES(113,'TOWN-CLERK-CITY',2,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(114,'TOWN-CLERK-CITY',3,'Head of Council',NULL);
INSERT INTO health_leave_approval_chain VALUES(115,'HLTH-ADIR-CITY',TRUE,'Supervisor','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(116,'HLTH-ADIR-CITY',2,'Head of Department','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(117,'HLTH-ADIR-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(118,'HLTH-SNR-EHO-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(119,'HLTH-SNR-EHO-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(120,'HLTH-SNR-EHO-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(121,'HLTH-SNR-TECH-CITY',TRUE,'Supervisor','HLTH-SNR-EHO-CITY');
INSERT INTO health_leave_approval_chain VALUES(122,'HLTH-SNR-TECH-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(123,'HLTH-SNR-TECH-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(124,'HLTH-TECH-CITY',TRUE,'Supervisor','HLTH-SNR-TECH-CITY');
INSERT INTO health_leave_approval_chain VALUES(125,'HLTH-TECH-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(126,'HLTH-TECH-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(127,'HLTH-CHIEF-HIO-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(128,'HLTH-CHIEF-HIO-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(129,'HLTH-CHIEF-HIO-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(130,'HLTH-SNR-HIO-CITY',TRUE,'Supervisor','HLTH-CHIEF-HIO-CITY');
INSERT INTO health_leave_approval_chain VALUES(131,'HLTH-SNR-HIO-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(132,'HLTH-SNR-HIO-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(133,'HLTH-HI-CITY',TRUE,'Supervisor','HLTH-SNR-HIO-CITY');
INSERT INTO health_leave_approval_chain VALUES(134,'HLTH-HI-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(135,'HLTH-HI-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(136,'HLTH-FIELD-DRIVER-CITY',TRUE,'Supervisor','HLTH-HI-CITY');
INSERT INTO health_leave_approval_chain VALUES(137,'HLTH-FIELD-DRIVER-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(138,'HLTH-FIELD-DRIVER-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(139,'HLTH-SNR-HPO-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(140,'HLTH-SNR-HPO-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(141,'HLTH-SNR-HPO-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(142,'HLTH-HPO-CITY',TRUE,'Supervisor','HLTH-SNR-HPO-CITY');
INSERT INTO health_leave_approval_chain VALUES(143,'HLTH-HPO-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(144,'HLTH-HPO-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(145,'HLTH-HEALTH-EDU-ASST-CITY',TRUE,'Supervisor','HLTH-HPO-CITY');
INSERT INTO health_leave_approval_chain VALUES(146,'HLTH-HEALTH-EDU-ASST-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(147,'HLTH-HEALTH-EDU-ASST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(148,'HLTH-CLEAN-MGR-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(149,'HLTH-CLEAN-MGR-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(150,'HLTH-CLEAN-MGR-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(151,'HLTH-CLEAN-SUP-CITY',TRUE,'Supervisor','HLTH-CLEAN-MGR-CITY');
INSERT INTO health_leave_approval_chain VALUES(152,'HLTH-CLEAN-SUP-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(153,'HLTH-CLEAN-SUP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(154,'HLTH-ASST-CLEAN-CITY',TRUE,'Supervisor','HLTH-CLEAN-SUP-CITY');
INSERT INTO health_leave_approval_chain VALUES(155,'HLTH-ASST-CLEAN-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(156,'HLTH-ASST-CLEAN-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(157,'HLTH-PEST-SUP-CITY',TRUE,'Supervisor','HLTH-CLEAN-MGR-CITY');
INSERT INTO health_leave_approval_chain VALUES(158,'HLTH-PEST-SUP-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(159,'HLTH-PEST-SUP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(160,'HLTH-ASST-PEST-CITY',TRUE,'Supervisor','HLTH-PEST-SUP-CITY');
INSERT INTO health_leave_approval_chain VALUES(161,'HLTH-ASST-PEST-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(162,'HLTH-ASST-PEST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(163,'HLTH-WASTE-DRIVER-CITY',TRUE,'Supervisor','HLTH-CLEAN-SUP-CITY');
INSERT INTO health_leave_approval_chain VALUES(164,'HLTH-WASTE-DRIVER-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(165,'HLTH-WASTE-DRIVER-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(166,'HLTH-FUN-SUP-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(167,'HLTH-FUN-SUP-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(168,'HLTH-FUN-SUP-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(169,'HLTH-SANITARY-CITY',TRUE,'Supervisor','HLTH-FUN-SUP-CITY');
INSERT INTO health_leave_approval_chain VALUES(170,'HLTH-SANITARY-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(171,'HLTH-SANITARY-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(172,'HLTH-GRAVE-CITY',TRUE,'Supervisor','HLTH-FUN-SUP-CITY');
INSERT INTO health_leave_approval_chain VALUES(173,'HLTH-GRAVE-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(174,'HLTH-GRAVE-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO health_leave_approval_chain VALUES(175,'HLTH-HIS-CITY',TRUE,'Supervisor','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(176,'HLTH-HIS-CITY',2,'Head of Department','HLTH-ADIR-CITY');
INSERT INTO health_leave_approval_chain VALUES(177,'HLTH-HIS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
