INSERT INTO ict_positions VALUES(1,'Head - ICT','LGSS/05',TRUE,'EXEC-CLK-MUN-01',TRUE,2,TRUE,'ICT-HEAD-MUN-01');
INSERT INTO ict_positions VALUES(2,'Senior System Analyst','LGSS/07',TRUE,'ICT-HEAD-MUN-01',TRUE,2,FALSE,'ICT-SSA-MUN-01');
INSERT INTO ict_positions VALUES(3,'Programmer','LGSS/10',3,'ICT-SSA-MUN-01',TRUE,2,FALSE,'ICT-PROG-MUN-01');
INSERT INTO ict_positions VALUES(4,'Data Entry Operator','LGSS/13',2,'ICT-PROG-MUN-01',TRUE,2,FALSE,'ICT-DEO-MUN-01');
