INSERT INTO leave_approval_chain VALUES(1,'HRA-DIR-MUN',TRUE,'Supervisor',NULL);
INSERT INTO leave_approval_chain VALUES(2,'HRA-DIR-MUN',2,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(3,'HRA-DIR-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(4,'HRA-DIR-MUN',4,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(5,'HRA-CHRO-MUN',TRUE,'Supervisor','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(6,'HRA-CHRO-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(7,'HRA-CHRO-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(8,'HRA-SNR-HRO-MUN',TRUE,'Supervisor','HRA-CHRO-MUN');
INSERT INTO leave_approval_chain VALUES(9,'HRA-SNR-HRO-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(10,'HRA-SNR-HRO-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(11,'HRA-HRO-MUN',TRUE,'Supervisor','HRA-SNR-HRO-MUN');
INSERT INTO leave_approval_chain VALUES(12,'HRA-HRO-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(13,'HRA-HRO-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(14,'HRA-CH-ADMIN-MUN',TRUE,'Supervisor','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(15,'HRA-CH-ADMIN-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(16,'HRA-CH-ADMIN-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(17,'HRA-SNR-ADMIN-MUN',TRUE,'Supervisor','HRA-CH-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(18,'HRA-SNR-ADMIN-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(19,'HRA-SNR-ADMIN-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(20,'HRA-ADMIN-MUN',TRUE,'Supervisor','HRA-SNR-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(21,'HRA-ADMIN-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(22,'HRA-ADMIN-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(23,'HRA-DRIVER-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(24,'HRA-HEAD-DRIVER-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(25,'HRA-ORDERLY-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(26,'HRA-REG-SUP-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(27,'HRA-SEC-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(28,'HRA-STENO-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(29,'HRA-TYPIST-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(30,'HRA-WATCHMAN-MUN',TRUE,'Supervisor','HRA-ADMIN-MUN');
INSERT INTO leave_approval_chain VALUES(31,'HRA-DRIVER-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(32,'HRA-HEAD-DRIVER-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(33,'HRA-ORDERLY-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(34,'HRA-REG-SUP-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(35,'HRA-SEC-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(36,'HRA-STENO-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(37,'HRA-TYPIST-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(38,'HRA-WATCHMAN-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(39,'HRA-DRIVER-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(40,'HRA-HEAD-DRIVER-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(41,'HRA-ORDERLY-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(42,'HRA-REG-SUP-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(43,'HRA-SEC-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(44,'HRA-STENO-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(45,'HRA-TYPIST-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(46,'HRA-WATCHMAN-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(47,'HRA-REG-CLERK-MUN',TRUE,'Supervisor','HRA-REG-SUP-MUN');
INSERT INTO leave_approval_chain VALUES(48,'HRA-REG-CLERK-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(49,'HRA-REG-CLERK-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(50,'HRA-CH-COMM-MUN',TRUE,'Supervisor','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(51,'HRA-CH-COMM-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(52,'HRA-CH-COMM-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(53,'HRA-SNR-COMM-MUN',TRUE,'Supervisor','HRA-CH-COMM-MUN');
INSERT INTO leave_approval_chain VALUES(54,'HRA-SNR-COMM-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(55,'HRA-SNR-COMM-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(56,'HRA-COMM-CLERK-MUN',TRUE,'Supervisor','HRA-SNR-COMM-MUN');
INSERT INTO leave_approval_chain VALUES(57,'HRA-COMM-CLERK-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(58,'HRA-COMM-CLERK-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(59,'HRA-ASST-COMM-MUN',TRUE,'Supervisor','HRA-COMM-CLERK-MUN');
INSERT INTO leave_approval_chain VALUES(60,'HRA-ASST-COMM-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(61,'HRA-ASST-COMM-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(62,'HRA-CH-SEC-MUN',TRUE,'Supervisor','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(63,'HRA-CH-SEC-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(64,'HRA-CH-SEC-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(65,'HRA-SNR-SEC-MUN',TRUE,'Supervisor','HRA-CH-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(66,'HRA-SNR-SEC-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(67,'HRA-SNR-SEC-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(68,'HRA-INSPECTOR-MUN',TRUE,'Supervisor','HRA-SNR-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(69,'HRA-POLICE-MUN',TRUE,'Supervisor','HRA-SNR-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(70,'HRA-SEC-OFFICER-MUN',TRUE,'Supervisor','HRA-SNR-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(71,'HRA-SERGEANT-MUN',TRUE,'Supervisor','HRA-SNR-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(72,'HRA-SUB-INSPECTOR-MUN',TRUE,'Supervisor','HRA-SNR-SEC-MUN');
INSERT INTO leave_approval_chain VALUES(73,'HRA-INSPECTOR-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(74,'HRA-POLICE-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(75,'HRA-SEC-OFFICER-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(76,'HRA-SERGEANT-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(77,'HRA-SUB-INSPECTOR-MUN',2,'HoD','HRA-DIR-MUN');
INSERT INTO leave_approval_chain VALUES(78,'HRA-INSPECTOR-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(79,'HRA-POLICE-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(80,'HRA-SEC-OFFICER-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(81,'HRA-SERGEANT-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(82,'HRA-SUB-INSPECTOR-MUN',3,'Municipal Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(83,'HRA-DIR-CITY',TRUE,'Supervisor',NULL);
INSERT INTO leave_approval_chain VALUES(84,'HRA-DIR-CITY',2,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(85,'HRA-DIR-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(86,'HRA-DIR-CITY',4,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(87,'HRA-ADIR-HRMDEV-CITY',TRUE,'Supervisor','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(88,'HRA-ADIR-HRMDEV-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(89,'HRA-ADIR-HRMDEV-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(90,'HRA-ADIR-ADMIN-CITY',TRUE,'Supervisor','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(91,'HRA-ADIR-ADMIN-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(92,'HRA-ADIR-ADMIN-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(93,'HRA-CHRO-CITY',TRUE,'Supervisor','HRA-ADIR-HRMDEV-CITY');
INSERT INTO leave_approval_chain VALUES(94,'HRA-CHRO-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(95,'HRA-CHRO-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(96,'HRA-SNR-HRO-CITY',TRUE,'Supervisor','HRA-CHRO-CITY');
INSERT INTO leave_approval_chain VALUES(97,'HRA-SNR-HRO-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(98,'HRA-SNR-HRO-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(99,'HRA-HRO-CITY',TRUE,'Supervisor','HRA-SNR-HRO-CITY');
INSERT INTO leave_approval_chain VALUES(100,'HRA-HRO-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(101,'HRA-HRO-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(102,'HRA-CH-ADMIN-CITY',TRUE,'Supervisor','HRA-ADIR-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(103,'HRA-CH-ADMIN-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(104,'HRA-CH-ADMIN-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(105,'HRA-SNR-ADMIN-CITY',TRUE,'Supervisor','HRA-CH-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(106,'HRA-SNR-ADMIN-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(107,'HRA-SNR-ADMIN-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(108,'HRA-ADMIN-CITY',TRUE,'Supervisor','HRA-SNR-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(109,'HRA-ADMIN-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(110,'HRA-ADMIN-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(111,'HRA-SNR-PRINT-CITY',TRUE,'Supervisor','HRA-CH-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(112,'HRA-SNR-PRINT-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(113,'HRA-SNR-PRINT-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(114,'HRA-PRINT-CITY',TRUE,'Supervisor','HRA-SNR-PRINT-CITY');
INSERT INTO leave_approval_chain VALUES(115,'HRA-PRINT-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(116,'HRA-PRINT-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(117,'HRA-DRIVER-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(118,'HRA-GW-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(119,'HRA-HEAD-DRIVER-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(120,'HRA-ORDERLY-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(121,'HRA-REG-SUP-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(122,'HRA-SEC-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(123,'HRA-STENO-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(124,'HRA-TYPIST-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(125,'HRA-WATCHMAN-CITY',TRUE,'Supervisor','HRA-ADMIN-CITY');
INSERT INTO leave_approval_chain VALUES(126,'HRA-DRIVER-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(127,'HRA-GW-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(128,'HRA-HEAD-DRIVER-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(129,'HRA-ORDERLY-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(130,'HRA-REG-SUP-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(131,'HRA-SEC-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(132,'HRA-STENO-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(133,'HRA-TYPIST-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(134,'HRA-WATCHMAN-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(135,'HRA-DRIVER-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(136,'HRA-GW-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(137,'HRA-HEAD-DRIVER-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(138,'HRA-ORDERLY-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(139,'HRA-REG-SUP-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(140,'HRA-SEC-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(141,'HRA-STENO-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(142,'HRA-TYPIST-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(143,'HRA-WATCHMAN-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(144,'HRA-REG-CLERK-CITY',TRUE,'Supervisor','HRA-REG-SUP-CITY');
INSERT INTO leave_approval_chain VALUES(145,'HRA-REG-CLERK-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(146,'HRA-REG-CLERK-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(147,'HRA-CH-COMM-CITY',TRUE,'Supervisor','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(148,'HRA-CH-COMM-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(149,'HRA-CH-COMM-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(150,'HRA-SNR-COMM-CITY',TRUE,'Supervisor','HRA-CH-COMM-CITY');
INSERT INTO leave_approval_chain VALUES(151,'HRA-SNR-COMM-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(152,'HRA-SNR-COMM-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(153,'HRA-COMM-CLERK-CITY',TRUE,'Supervisor','HRA-SNR-COMM-CITY');
INSERT INTO leave_approval_chain VALUES(154,'HRA-COMM-CLERK-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(155,'HRA-COMM-CLERK-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(156,'HRA-ASST-COMM-CITY',TRUE,'Supervisor','HRA-COMM-CLERK-CITY');
INSERT INTO leave_approval_chain VALUES(157,'HRA-ASST-COMM-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(158,'HRA-ASST-COMM-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(159,'HRA-CH-SEC-CITY',TRUE,'Supervisor','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(160,'HRA-CH-SEC-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(161,'HRA-CH-SEC-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(162,'HRA-SNR-SEC-CITY',TRUE,'Supervisor','HRA-CH-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(163,'HRA-SNR-SEC-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(164,'HRA-SNR-SEC-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(165,'HRA-INSPECTOR-CITY',TRUE,'Supervisor','HRA-SNR-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(166,'HRA-POLICE-CITY',TRUE,'Supervisor','HRA-SNR-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(167,'HRA-SEC-OFFICER-CITY',TRUE,'Supervisor','HRA-SNR-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(168,'HRA-SERGEANT-CITY',TRUE,'Supervisor','HRA-SNR-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(169,'HRA-SUB-INSPECTOR-CITY',TRUE,'Supervisor','HRA-SNR-SEC-CITY');
INSERT INTO leave_approval_chain VALUES(170,'HRA-INSPECTOR-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(171,'HRA-POLICE-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(172,'HRA-SEC-OFFICER-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(173,'HRA-SERGEANT-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(174,'HRA-SUB-INSPECTOR-CITY',2,'HoD','HRA-DIR-CITY');
INSERT INTO leave_approval_chain VALUES(175,'HRA-INSPECTOR-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(176,'HRA-POLICE-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(177,'HRA-SEC-OFFICER-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(178,'HRA-SERGEANT-CITY',3,'Town Clerk',NULL);
INSERT INTO leave_approval_chain VALUES(179,'HRA-SUB-INSPECTOR-CITY',3,'Town Clerk',NULL);
