INSERT INTO legal_leave_approval_chain VALUES(1,'COUNCIL-SEC-TOWN',TRUE,'Supervisor',NULL);
INSERT INTO legal_leave_approval_chain VALUES(2,'COUNCIL-SEC-TOWN',2,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(3,'COUNCIL-SEC-TOWN',3,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(4,'LEG-ADV-TOWN',TRUE,'Supervisor','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(5,'LEG-ADV-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(6,'LEG-ADV-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(7,'LEG-SRASST-TOWN',TRUE,'Supervisor','LEG-ADV-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(8,'LEG-SRASST-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(9,'LEG-SRASST-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(10,'LEG-REG-TOWN',TRUE,'Supervisor','LEG-SRASST-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(11,'LEG-REG-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(12,'LEG-REG-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO legal_leave_approval_chain VALUES(13,'TOWN-CLERK-MUN',TRUE,'Supervisor',NULL);
INSERT INTO legal_leave_approval_chain VALUES(14,'TOWN-CLERK-MUN',2,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(15,'TOWN-CLERK-MUN',3,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(16,'LEG-DIR-MUN',TRUE,'Supervisor','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(17,'LEG-DIR-MUN',2,'Head of Department','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(18,'LEG-DIR-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(19,'LEG-ADV-LIT-MUN',TRUE,'Supervisor','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(20,'LEG-ADV-LIT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(21,'LEG-ADV-LIT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(22,'LEG-ADV-EST-MUN',TRUE,'Supervisor','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(23,'LEG-ADV-EST-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(24,'LEG-ADV-EST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(25,'LEG-OFF-LIT-MUN',TRUE,'Supervisor','LEG-ADV-LIT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(26,'LEG-OFF-LIT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(27,'LEG-OFF-LIT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(28,'LEG-OFF-PROSE-MUN',TRUE,'Supervisor','LEG-ADV-LIT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(29,'LEG-OFF-PROSE-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(30,'LEG-OFF-PROSE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(31,'LEG-OFF-CONT-MUN',TRUE,'Supervisor','LEG-ADV-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(32,'LEG-OFF-CONT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(33,'LEG-OFF-CONT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(34,'LEG-OFF-LIC-MUN',TRUE,'Supervisor','LEG-ADV-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(35,'LEG-OFF-LIC-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(36,'LEG-OFF-LIC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(37,'LEG-OFF-EST-MUN',TRUE,'Supervisor','LEG-ADV-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(38,'LEG-OFF-EST-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(39,'LEG-OFF-EST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(40,'LEG-LIC-OFF-MUN',TRUE,'Supervisor','LEG-ADV-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(41,'LEG-LIC-OFF-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(42,'LEG-LIC-OFF-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(43,'LEG-SRASST-LIT-MUN',TRUE,'Supervisor','LEG-OFF-LIT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(44,'LEG-SRASST-LIT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(45,'LEG-SRASST-LIT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(46,'LEG-SRASST-PROSE-MUN',TRUE,'Supervisor','LEG-OFF-PROSE-MUN');
INSERT INTO legal_leave_approval_chain VALUES(47,'LEG-SRASST-PROSE-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(48,'LEG-SRASST-PROSE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(49,'LEG-SRASST-CONT-MUN',TRUE,'Supervisor','LEG-OFF-CONT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(50,'LEG-SRASST-CONT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(51,'LEG-SRASST-CONT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(52,'LEG-SRASST-LIC-MUN',TRUE,'Supervisor','LEG-OFF-LIC-MUN');
INSERT INTO legal_leave_approval_chain VALUES(53,'LEG-SRASST-LIC-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(54,'LEG-SRASST-LIC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(55,'LEG-SRASST-EST-MUN',TRUE,'Supervisor','LEG-OFF-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(56,'LEG-SRASST-EST-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(57,'LEG-SRASST-EST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(58,'LEG-ASST-PROSE-MUN',TRUE,'Supervisor','LEG-SRASST-PROSE-MUN');
INSERT INTO legal_leave_approval_chain VALUES(59,'LEG-ASST-PROSE-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(60,'LEG-ASST-PROSE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(61,'LEG-ASST-CONT-MUN',TRUE,'Supervisor','LEG-SRASST-CONT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(62,'LEG-ASST-CONT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(63,'LEG-ASST-CONT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(64,'LEG-ASST-LIC-MUN',TRUE,'Supervisor','LEG-SRASST-LIC-MUN');
INSERT INTO legal_leave_approval_chain VALUES(65,'LEG-ASST-LIC-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(66,'LEG-ASST-LIC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(67,'LEG-ASST-EST-MUN',TRUE,'Supervisor','LEG-SRASST-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(68,'LEG-ASST-EST-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(69,'LEG-ASST-EST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(70,'LEG-REG-LIT-MUN',TRUE,'Supervisor','LEG-SRASST-LIT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(71,'LEG-REG-LIT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(72,'LEG-REG-LIT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(73,'LEG-REG-DEEDS-MUN',TRUE,'Supervisor','LEG-ADV-LIT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(74,'LEG-REG-DEEDS-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(75,'LEG-REG-DEEDS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(76,'LEG-REG-PROSE-MUN',TRUE,'Supervisor','LEG-ASST-PROSE-MUN');
INSERT INTO legal_leave_approval_chain VALUES(77,'LEG-REG-PROSE-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(78,'LEG-REG-PROSE-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(79,'LEG-REG-CONT-MUN',TRUE,'Supervisor','LEG-ASST-CONT-MUN');
INSERT INTO legal_leave_approval_chain VALUES(80,'LEG-REG-CONT-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(81,'LEG-REG-CONT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(82,'LEG-REG-LIC-MUN',TRUE,'Supervisor','LEG-LIC-OFF-MUN');
INSERT INTO legal_leave_approval_chain VALUES(83,'LEG-REG-LIC-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(84,'LEG-REG-LIC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(85,'LEG-REG-EST-MUN',TRUE,'Supervisor','LEG-ASST-EST-MUN');
INSERT INTO legal_leave_approval_chain VALUES(86,'LEG-REG-EST-MUN',2,'Head of Department','LEG-DIR-MUN');
INSERT INTO legal_leave_approval_chain VALUES(87,'LEG-REG-EST-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO legal_leave_approval_chain VALUES(88,'TOWN-CLERK-CITY',TRUE,'Supervisor',NULL);
INSERT INTO legal_leave_approval_chain VALUES(89,'TOWN-CLERK-CITY',2,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(90,'TOWN-CLERK-CITY',3,'Head of Council',NULL);
INSERT INTO legal_leave_approval_chain VALUES(91,'LEG-DIR-CITY',TRUE,'Supervisor','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(92,'LEG-DIR-CITY',2,'Head of Department','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(93,'LEG-DIR-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(94,'LEG-ADV-LIT-CITY',TRUE,'Supervisor','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(95,'LEG-ADV-LIT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(96,'LEG-ADV-LIT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(97,'LEG-ADV-EST-CITY',TRUE,'Supervisor','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(98,'LEG-ADV-EST-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(99,'LEG-ADV-EST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(100,'LEG-OFF-LIT-CITY',TRUE,'Supervisor','LEG-ADV-LIT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(101,'LEG-OFF-LIT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(102,'LEG-OFF-LIT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(103,'LEG-OFF-DEEDS-CITY',TRUE,'Supervisor','LEG-ADV-LIT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(104,'LEG-OFF-DEEDS-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(105,'LEG-OFF-DEEDS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(106,'LEG-OFF-CONT-CITY',TRUE,'Supervisor','LEG-ADV-EST-CITY');
INSERT INTO legal_leave_approval_chain VALUES(107,'LEG-OFF-CONT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(108,'LEG-OFF-CONT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(109,'LEG-OFF-EST-CITY',TRUE,'Supervisor','LEG-ADV-EST-CITY');
INSERT INTO legal_leave_approval_chain VALUES(110,'LEG-OFF-EST-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(111,'LEG-OFF-EST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(112,'LEG-LIC-CITY',TRUE,'Supervisor','LEG-OFF-CONT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(113,'LEG-LIC-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(114,'LEG-LIC-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(115,'LEG-SRASST-LIT-CITY',TRUE,'Supervisor','LEG-OFF-LIT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(116,'LEG-SRASST-LIT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(117,'LEG-SRASST-LIT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(118,'LEG-SRASST-DEEDS-CITY',TRUE,'Supervisor','LEG-OFF-DEEDS-CITY');
INSERT INTO legal_leave_approval_chain VALUES(119,'LEG-SRASST-DEEDS-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(120,'LEG-SRASST-DEEDS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(121,'LEG-SRASST-CONT-CITY',TRUE,'Supervisor','LEG-OFF-CONT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(122,'LEG-SRASST-CONT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(123,'LEG-SRASST-CONT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(124,'LEG-SRASST-EST-CITY',TRUE,'Supervisor','LEG-OFF-EST-CITY');
INSERT INTO legal_leave_approval_chain VALUES(125,'LEG-SRASST-EST-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(126,'LEG-SRASST-EST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(127,'LEG-ASST-LIT-CITY',TRUE,'Supervisor','LEG-SRASST-LIT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(128,'LEG-ASST-LIT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(129,'LEG-ASST-LIT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(130,'LEG-ASST-DEEDS-CITY',TRUE,'Supervisor','LEG-SRASST-DEEDS-CITY');
INSERT INTO legal_leave_approval_chain VALUES(131,'LEG-ASST-DEEDS-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(132,'LEG-ASST-DEEDS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(133,'LEG-ASST-CONT-CITY',TRUE,'Supervisor','LEG-SRASST-CONT-CITY');
INSERT INTO legal_leave_approval_chain VALUES(134,'LEG-ASST-CONT-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(135,'LEG-ASST-CONT-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO legal_leave_approval_chain VALUES(136,'LEG-ASST-EST-CITY',TRUE,'Supervisor','LEG-SRASST-EST-CITY');
INSERT INTO legal_leave_approval_chain VALUES(137,'LEG-ASST-EST-CITY',2,'Head of Department','LEG-DIR-CITY');
INSERT INTO legal_leave_approval_chain VALUES(138,'LEG-ASST-EST-CITY',3,'Head of Council','TOWN-CLERK-CITY');
