INSERT INTO planning_leave_approval_chain VALUES(19,'COUNCIL-SEC-TOWN',TRUE,'Supervisor',NULL);
INSERT INTO planning_leave_approval_chain VALUES(20,'COUNCIL-SEC-TOWN',2,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(21,'COUNCIL-SEC-TOWN',3,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(22,'PLAN-DIR-TOWN',TRUE,'Supervisor','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(23,'PLAN-DIR-TOWN',2,'Head of Department','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(24,'PLAN-DIR-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(25,'PLAN-CH-PHY-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(26,'PLAN-CH-PHY-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(27,'PLAN-CH-PHY-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(28,'PLAN-TOWN-TOWN',TRUE,'Supervisor','PLAN-CH-PHY-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(29,'PLAN-TOWN-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(30,'PLAN-TOWN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(31,'PLAN-ASST-TOWN-TOWN',TRUE,'Supervisor','PLAN-TOWN-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(32,'PLAN-ASST-TOWN-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(33,'PLAN-ASST-TOWN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(34,'PLAN-BI-TOWN',TRUE,'Supervisor','PLAN-CH-PHY-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(35,'PLAN-BI-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(36,'PLAN-BI-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(37,'PLAN-ASST-BI-TOWN',TRUE,'Supervisor','PLAN-BI-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(38,'PLAN-ASST-BI-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(39,'PLAN-ASST-BI-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(40,'PLAN-LS-TOWN',TRUE,'Supervisor','PLAN-CH-PHY-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(41,'PLAN-LS-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(42,'PLAN-LS-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(43,'PLAN-ASST-LS-TOWN',TRUE,'Supervisor','PLAN-LS-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(44,'PLAN-ASST-LS-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(45,'PLAN-ASST-LS-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(46,'PLAN-CHAIN-TOWN',TRUE,'Supervisor','PLAN-ASST-LS-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(47,'PLAN-CHAIN-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(48,'PLAN-CHAIN-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(49,'PLAN-VAL-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(50,'PLAN-VAL-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(51,'PLAN-VAL-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(52,'PLAN-ASST-VAL-MGMT-TOWN',TRUE,'Supervisor','PLAN-VAL-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(53,'PLAN-ASST-VAL-MGMT-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(54,'PLAN-ASST-VAL-MGMT-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(55,'PLAN-ASST-VAL-TAX-TOWN',TRUE,'Supervisor','PLAN-VAL-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(56,'PLAN-ASST-VAL-TAX-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(57,'PLAN-ASST-VAL-TAX-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(58,'PLAN-DATA-TOWN',TRUE,'Supervisor','PLAN-ASST-VAL-MGMT-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(59,'PLAN-DATA-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(60,'PLAN-DATA-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(61,'PLAN-CH-SOC-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(62,'PLAN-CH-SOC-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(63,'PLAN-CH-SOC-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(64,'PLAN-SOC-COUNCIL-TOWN',TRUE,'Supervisor','PLAN-CH-SOC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(65,'PLAN-SOC-COUNCIL-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(66,'PLAN-SOC-COUNCIL-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(67,'PLAN-SOC-HEALTH-TOWN',TRUE,'Supervisor','PLAN-CH-SOC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(68,'PLAN-SOC-HEALTH-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(69,'PLAN-SOC-HEALTH-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(70,'PLAN-SOC-FISH-TOWN',TRUE,'Supervisor','PLAN-CH-SOC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(71,'PLAN-SOC-FISH-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(72,'PLAN-SOC-FISH-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(73,'PLAN-HINFO-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(74,'PLAN-HINFO-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(75,'PLAN-HINFO-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(76,'PLAN-ENV-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(77,'PLAN-ENV-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(78,'PLAN-ENV-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(79,'PLAN-ME-TOWN',TRUE,'Supervisor','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(80,'PLAN-ME-TOWN',2,'Head of Department','PLAN-DIR-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(81,'PLAN-ME-TOWN',3,'Head of Council','COUNCIL-SEC-TOWN');
INSERT INTO planning_leave_approval_chain VALUES(82,'TOWN-CLERK-MUN',TRUE,'Supervisor',NULL);
INSERT INTO planning_leave_approval_chain VALUES(83,'TOWN-CLERK-MUN',2,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(84,'TOWN-CLERK-MUN',3,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(85,'PLAN-DIR-MUN',TRUE,'Supervisor','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(86,'PLAN-DIR-MUN',2,'Head of Department','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(87,'PLAN-DIR-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(88,'PLAN-ADIR-PHY-MUN',TRUE,'Supervisor','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(89,'PLAN-ADIR-PHY-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(90,'PLAN-ADIR-PHY-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(91,'PLAN-SNR-TOWN-MUN',TRUE,'Supervisor','PLAN-ADIR-PHY-MUN');
INSERT INTO planning_leave_approval_chain VALUES(92,'PLAN-SNR-TOWN-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(93,'PLAN-SNR-TOWN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(94,'PLAN-TOWN-MUN',TRUE,'Supervisor','PLAN-SNR-TOWN-MUN');
INSERT INTO planning_leave_approval_chain VALUES(95,'PLAN-TOWN-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(96,'PLAN-TOWN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(97,'PLAN-ASST-TOWN-MUN',TRUE,'Supervisor','PLAN-TOWN-MUN');
INSERT INTO planning_leave_approval_chain VALUES(98,'PLAN-ASST-TOWN-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(99,'PLAN-ASST-TOWN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(100,'PLAN-SNR-PA-MUN',TRUE,'Supervisor','PLAN-ASST-TOWN-MUN');
INSERT INTO planning_leave_approval_chain VALUES(101,'PLAN-SNR-PA-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(102,'PLAN-SNR-PA-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(103,'PLAN-PA-MUN',TRUE,'Supervisor','PLAN-SNR-PA-MUN');
INSERT INTO planning_leave_approval_chain VALUES(104,'PLAN-PA-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(105,'PLAN-PA-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(106,'PLAN-CH-BI-MUN',TRUE,'Supervisor','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(107,'PLAN-CH-BI-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(108,'PLAN-CH-BI-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(109,'PLAN-SNR-BI-MUN',TRUE,'Supervisor','PLAN-CH-BI-MUN');
INSERT INTO planning_leave_approval_chain VALUES(110,'PLAN-SNR-BI-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(111,'PLAN-SNR-BI-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(112,'PLAN-SUPT-BI-MUN',TRUE,'Supervisor','PLAN-SNR-BI-MUN');
INSERT INTO planning_leave_approval_chain VALUES(113,'PLAN-SUPT-BI-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(114,'PLAN-SUPT-BI-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(115,'PLAN-BI-MUN',TRUE,'Supervisor','PLAN-SUPT-BI-MUN');
INSERT INTO planning_leave_approval_chain VALUES(116,'PLAN-BI-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(117,'PLAN-BI-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(118,'PLAN-SNR-LS-MUN',TRUE,'Supervisor','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(119,'PLAN-SNR-LS-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(120,'PLAN-SNR-LS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(121,'PLAN-LS-MUN',TRUE,'Supervisor','PLAN-SNR-LS-MUN');
INSERT INTO planning_leave_approval_chain VALUES(122,'PLAN-LS-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(123,'PLAN-LS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(124,'PLAN-ASST-LS-MUN',TRUE,'Supervisor','PLAN-LS-MUN');
INSERT INTO planning_leave_approval_chain VALUES(125,'PLAN-ASST-LS-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(126,'PLAN-ASST-LS-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(127,'PLAN-CHAIN-MUN',TRUE,'Supervisor','PLAN-ASST-LS-MUN');
INSERT INTO planning_leave_approval_chain VALUES(128,'PLAN-CHAIN-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(129,'PLAN-CHAIN-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(130,'PLAN-CH-VAL-MUN',TRUE,'Supervisor','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(131,'PLAN-CH-VAL-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(132,'PLAN-CH-VAL-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(133,'PLAN-SNR-VAL-MUN',TRUE,'Supervisor','PLAN-CH-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(134,'PLAN-SNR-VAL-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(135,'PLAN-SNR-VAL-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(136,'PLAN-SNR-VAL-MGMT-MUN',TRUE,'Supervisor','PLAN-CH-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(137,'PLAN-SNR-VAL-MGMT-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(138,'PLAN-SNR-VAL-MGMT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(139,'PLAN-SNR-VAL-TAX-MUN',TRUE,'Supervisor','PLAN-CH-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(140,'PLAN-SNR-VAL-TAX-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(141,'PLAN-SNR-VAL-TAX-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(142,'PLAN-MGMT-MUN',TRUE,'Supervisor','PLAN-SNR-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(143,'PLAN-MGMT-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(144,'PLAN-MGMT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(145,'PLAN-VAL-TAX-MUN',TRUE,'Supervisor','PLAN-SNR-VAL-TAX-MUN');
INSERT INTO planning_leave_approval_chain VALUES(146,'PLAN-VAL-TAX-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(147,'PLAN-VAL-TAX-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(148,'PLAN-ASST-VAL-MGMT-MUN',TRUE,'Supervisor','PLAN-MGMT-MUN');
INSERT INTO planning_leave_approval_chain VALUES(149,'PLAN-ASST-VAL-MGMT-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(150,'PLAN-ASST-VAL-MGMT-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(151,'PLAN-ASST-VAL-TAX-MUN',TRUE,'Supervisor','PLAN-VAL-TAX-MUN');
INSERT INTO planning_leave_approval_chain VALUES(152,'PLAN-ASST-VAL-TAX-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(153,'PLAN-ASST-VAL-TAX-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(154,'PLAN-FIELD-MUN',TRUE,'Supervisor','PLAN-CH-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(155,'PLAN-FIELD-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(156,'PLAN-FIELD-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(157,'PLAN-DATA-MUN',TRUE,'Supervisor','PLAN-ASST-VAL-MGMT-MUN');
INSERT INTO planning_leave_approval_chain VALUES(158,'PLAN-DATA-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(159,'PLAN-DATA-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(160,'PLAN-REV-MUN',TRUE,'Supervisor','PLAN-CH-VAL-MUN');
INSERT INTO planning_leave_approval_chain VALUES(161,'PLAN-REV-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(162,'PLAN-REV-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(163,'PLAN-CH-SOC-MUN',TRUE,'Supervisor','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(164,'PLAN-CH-SOC-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(165,'PLAN-CH-SOC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(166,'PLAN-SNR-SOC-MUN',TRUE,'Supervisor','PLAN-CH-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(167,'PLAN-SNR-SOC-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(168,'PLAN-SNR-SOC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(169,'PLAN-SOC-MUN',TRUE,'Supervisor','PLAN-SNR-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(170,'PLAN-SOC-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(171,'PLAN-SOC-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(172,'PLAN-SNR-ENV-MUN',TRUE,'Supervisor','PLAN-CH-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(173,'PLAN-SNR-ENV-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(174,'PLAN-SNR-ENV-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(175,'PLAN-ENV-MUN',TRUE,'Supervisor','PLAN-SNR-ENV-MUN');
INSERT INTO planning_leave_approval_chain VALUES(176,'PLAN-ENV-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(177,'PLAN-ENV-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(178,'PLAN-SOC-HEALTH-MUN',TRUE,'Supervisor','PLAN-SNR-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(179,'PLAN-SOC-HEALTH-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(180,'PLAN-SOC-HEALTH-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(181,'PLAN-SOC-FISH-MUN',TRUE,'Supervisor','PLAN-SNR-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(182,'PLAN-SOC-FISH-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(183,'PLAN-SOC-FISH-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(184,'PLAN-SNR-ME-MUN',TRUE,'Supervisor','PLAN-CH-SOC-MUN');
INSERT INTO planning_leave_approval_chain VALUES(185,'PLAN-SNR-ME-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(186,'PLAN-SNR-ME-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(187,'PLAN-ME-MUN',TRUE,'Supervisor','PLAN-SNR-ME-MUN');
INSERT INTO planning_leave_approval_chain VALUES(188,'PLAN-ME-MUN',2,'Head of Department','PLAN-DIR-MUN');
INSERT INTO planning_leave_approval_chain VALUES(189,'PLAN-ME-MUN',3,'Head of Council','TOWN-CLERK-MUN');
INSERT INTO planning_leave_approval_chain VALUES(190,'TOWN-CLERK-CITY',TRUE,'Supervisor',NULL);
INSERT INTO planning_leave_approval_chain VALUES(191,'TOWN-CLERK-CITY',2,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(192,'TOWN-CLERK-CITY',3,'Head of Council',NULL);
INSERT INTO planning_leave_approval_chain VALUES(193,'PLAN-DIR-CITY',TRUE,'Supervisor','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(194,'PLAN-DIR-CITY',2,'Head of Department','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(195,'PLAN-DIR-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(196,'PLAN-ADIR-PHY-CITY',TRUE,'Supervisor','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(197,'PLAN-ADIR-PHY-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(198,'PLAN-ADIR-PHY-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(199,'PLAN-SNR-TOWN-CITY',TRUE,'Supervisor','PLAN-ADIR-PHY-CITY');
INSERT INTO planning_leave_approval_chain VALUES(200,'PLAN-SNR-TOWN-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(201,'PLAN-SNR-TOWN-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(202,'PLAN-TOWN-CITY',TRUE,'Supervisor','PLAN-SNR-TOWN-CITY');
INSERT INTO planning_leave_approval_chain VALUES(203,'PLAN-TOWN-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(204,'PLAN-TOWN-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(205,'PLAN-ASST-TOWN-CITY',TRUE,'Supervisor','PLAN-TOWN-CITY');
INSERT INTO planning_leave_approval_chain VALUES(206,'PLAN-ASST-TOWN-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(207,'PLAN-ASST-TOWN-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(208,'PLAN-CH-BI-CITY',TRUE,'Supervisor','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(209,'PLAN-CH-BI-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(210,'PLAN-CH-BI-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(211,'PLAN-SNR-BI-CITY',TRUE,'Supervisor','PLAN-CH-BI-CITY');
INSERT INTO planning_leave_approval_chain VALUES(212,'PLAN-SNR-BI-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(213,'PLAN-SNR-BI-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(214,'PLAN-SUPT-BI-CITY',TRUE,'Supervisor','PLAN-SNR-BI-CITY');
INSERT INTO planning_leave_approval_chain VALUES(215,'PLAN-SUPT-BI-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(216,'PLAN-SUPT-BI-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(217,'PLAN-BI-CITY',TRUE,'Supervisor','PLAN-SUPT-BI-CITY');
INSERT INTO planning_leave_approval_chain VALUES(218,'PLAN-BI-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(219,'PLAN-BI-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(220,'PLAN-SNR-LS-CITY',TRUE,'Supervisor','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(221,'PLAN-SNR-LS-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(222,'PLAN-SNR-LS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(223,'PLAN-LS-CITY',TRUE,'Supervisor','PLAN-SNR-LS-CITY');
INSERT INTO planning_leave_approval_chain VALUES(224,'PLAN-LS-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(225,'PLAN-LS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(226,'PLAN-ASST-LS-CITY',TRUE,'Supervisor','PLAN-LS-CITY');
INSERT INTO planning_leave_approval_chain VALUES(227,'PLAN-ASST-LS-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(228,'PLAN-ASST-LS-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(229,'PLAN-CHAIN-CITY',TRUE,'Supervisor','PLAN-ASST-LS-CITY');
INSERT INTO planning_leave_approval_chain VALUES(230,'PLAN-CHAIN-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(231,'PLAN-CHAIN-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(232,'PLAN-CH-SOC-CITY',TRUE,'Supervisor','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(233,'PLAN-CH-SOC-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(234,'PLAN-CH-SOC-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(235,'PLAN-SNR-SOC-CITY',TRUE,'Supervisor','PLAN-CH-SOC-CITY');
INSERT INTO planning_leave_approval_chain VALUES(236,'PLAN-SNR-SOC-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(237,'PLAN-SNR-SOC-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(238,'PLAN-SOC-CITY',TRUE,'Supervisor','PLAN-SNR-SOC-CITY');
INSERT INTO planning_leave_approval_chain VALUES(239,'PLAN-SOC-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(240,'PLAN-SOC-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(241,'PLAN-SNR-ENV-CITY',TRUE,'Supervisor','PLAN-CH-SOC-CITY');
INSERT INTO planning_leave_approval_chain VALUES(242,'PLAN-SNR-ENV-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(243,'PLAN-SNR-ENV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(244,'PLAN-ENV-CITY',TRUE,'Supervisor','PLAN-SNR-ENV-CITY');
INSERT INTO planning_leave_approval_chain VALUES(245,'PLAN-ENV-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(246,'PLAN-ENV-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(247,'PLAN-SNR-ME-CITY',TRUE,'Supervisor','PLAN-CH-SOC-CITY');
INSERT INTO planning_leave_approval_chain VALUES(248,'PLAN-SNR-ME-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(249,'PLAN-SNR-ME-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(250,'PLAN-ME-CITY',TRUE,'Supervisor','PLAN-SNR-ME-CITY');
INSERT INTO planning_leave_approval_chain VALUES(251,'PLAN-ME-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(252,'PLAN-ME-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(253,'PLAN-DATA-CITY',TRUE,'Supervisor','PLAN-ME-CITY');
INSERT INTO planning_leave_approval_chain VALUES(254,'PLAN-DATA-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(255,'PLAN-DATA-CITY',3,'Head of Council','TOWN-CLERK-CITY');
INSERT INTO planning_leave_approval_chain VALUES(256,'PLAN-GENDER-CITY',TRUE,'Supervisor','PLAN-CH-SOC-CITY');
INSERT INTO planning_leave_approval_chain VALUES(257,'PLAN-GENDER-CITY',2,'Head of Department','PLAN-DIR-CITY');
INSERT INTO planning_leave_approval_chain VALUES(258,'PLAN-GENDER-CITY',3,'Head of Council','TOWN-CLERK-CITY');
