INSERT INTO position_attributes VALUES('ENG-DIR','Town','Director of Engineering','LGSS/05',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-DIR','Municipal','Director of Engineering','LGSS/04',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-DIR','City','Director of Engineering','LGSS/03',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-HEAD','Town','Electrical Engineer','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-HEAD','Municipal','Chief Electrical Engineer','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-HEAD','City','Electrical Engineering Unit Head','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-ASST','Town','Assistant Electrical Engineer','LGSS/10',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-ASST','Municipal','Electrical Engineer – Design','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-ASST','City','Electrical Engineer – Design','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-WRK','Town','Electrician','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-WRK','Municipal','Electrician','LGSS/14',5,NULL);
INSERT INTO position_attributes VALUES('ENG-ELEC-WRK','City','Electrician','LGSS/14',5,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-HEAD','Town','Divisional Fire Officer','LGSS/08',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-HEAD','Municipal','Chief Fire Officer','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-HEAD','City','Chief Fire Officer','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-FF','Town','Firefighter','LGSS/14',4,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-FF','Municipal','Firefighter','LGSS/14',6,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-FF','City','Firefighter','LGSS/14',8,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-DRV','Town','Firefighter Driver','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-DRV','Municipal','Firefighter Driver','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('ENG-FIRE-DRV','City','Firefighter Driver','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('ENG-MECHNIC','Town','Mechanic','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('ENG-MECHNIC','Municipal','Mechanic','LGSS/14',3,NULL);
INSERT INTO position_attributes VALUES('ENG-MECHNIC','City','Mechanic','LGSS/14',3,NULL);
INSERT INTO position_attributes VALUES('ENG-OPER','Town','Operator (Excavator, Roller, Grader, TLB)','LGSS/14',8,NULL);
INSERT INTO position_attributes VALUES('ENG-OPER','Municipal','Ferry/Pontoon Operator','LGSS/14',4,NULL);
INSERT INTO position_attributes VALUES('ENG-OPER','City','Ferry Operator','LGSS/14',4,NULL);
INSERT INTO position_attributes VALUES('ENG-WATSAN-HEAD','Town','Water & Sanitation Engineer','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-WATSAN-HEAD','Municipal','Rural Water & Sanitation Coordinator','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('ENG-WATSAN-HEAD','City','Rural Water & Sanitation Coordinator','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-DIR-TOWN','Town','Director of Human Resource & Administration','LGSS/05',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-CHRO-TOWN','Town','Chief Human Resources Officer','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-SNR-HRO-TOWN','Town','Senior Human Resource Officer','LGSS/07',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-HRO-TOWN','Town','Human Resources Officer','LGSS/08',3,NULL);
INSERT INTO position_attributes VALUES('HR-HRM-HEALTH-TOWN','Town','Human Resource Management Officer','LGSS/08',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-HRM-FISH-TOWN','Town','Human Resource Management Officer','LGSS/08',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-CH-ADMIN-TOWN','Town','Chief Administrative & Committee Officer','LGSS/06',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-ADMIN-TOWN','Town','Administrative Officer','LGSS/10',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-SEC-TOWN','Town','Personal Secretary','LGSS/10',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-STENO-TOWN','Town','Stenographer','LGSS/12',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-TYPIST-TOWN','Town','Typist','LGSS/14',2,NULL);
INSERT INTO position_attributes VALUES('HR-ORDERLY-TOWN','Town','Office Orderly','G3',6,NULL);
INSERT INTO position_attributes VALUES('HR-DRIVER-TOWN','Town','Driver','G1',4,NULL);
INSERT INTO position_attributes VALUES('HR-COMM-CLERK-TOWN','Town','Committee Clerk','LGSS/10',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-ASST-COMM-TOWN','Town','Assistant Committee Clerk','LGSS/12',2,NULL);
INSERT INTO position_attributes VALUES('HR-REG-SUP-TOWN','Town','Registry Supervisor','LGSS/14',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-REG-CLERK-TOWN','Town','Registry Clerk','LGSS/17',5,NULL);
INSERT INTO position_attributes VALUES('HR-SNR-SEC-TOWN','Town','Senior Security Officer','LGSS/08',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-SEC-OFFICER-TOWN','Town','Security Officer','LGSS/10',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-SERGEANT-TOWN','Town','Town Sergeant','LGSS/12',TRUE,NULL);
INSERT INTO position_attributes VALUES('HR-SUB-INSPECTOR-TOWN','Town','Sub-Inspector','LGSS/16',4,NULL);
INSERT INTO position_attributes VALUES('HR-POLICE-TOWN','Town','Police Constable','G3',10,NULL);
