INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH07','Architect','City','ARC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH07','Architect','Municipal','ARC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH','Architect','Town','ARC','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-ASSIST','Architectural Assistant','Municipal','ARC','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-ASST','Assistant Architect','City','ARC','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-ASST','Assistant Architect','Municipal','ARC','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-ASST','Assistant Architect','Town','ARC','ASST','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASST','Assistant Civil Engineer','City','GEN','ASSTENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASST','Assistant Civil Engineer','Municipal','GEN','ASSTENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASST','Assistant Civil Engineer','Town','GEN','ASSTENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CONSTR-ASSTDIR','Assistant Director - Construction & Maintenance','City','MTN','ADIR','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CONSTR-ASSTDIR','Assistant Director - Construction & Maintenance','Municipal','MTN','ADIR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ASST-DIR','Assistant Director - Engineering','Town','GEN','ADIR','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ROADS-ASSTDIR','Assistant Director - Roads & Drainages','City','GEN','ADIR','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ROADS-ASSTDIR','Assistant Director - Roads & Drainages','Municipal','GEN','ADIR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-ASSTDIV','Assistant Divisional Fire Officer','City','FRS','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-ASSTDIV','Assistant Divisional Fire Officer','Municipal','FRS','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASST','Assistant Electrical Engineer','City','ELE','ASSTENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASST','Assistant Electrical Engineer','Municipal','ELE','ASSTENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASST','Assistant Electrical Engineer','Town','ELE','ASSTENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASSTFORE','Assistant Foreman','City','GEN','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASSTFORE','Assistant Foreman','City','ELE','ASST','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSTFORE','Assistant Foreman','City','MEC','ASST','CIT',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-ASSTFORE','Assistant Foreman','Municipal','ARC','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASSTFORE','Assistant Foreman','Municipal','GEN','ASST','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASSTFORE','Assistant Foreman','Municipal','ELE','ASST','MUN',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSTFORE','Assistant Foreman','Municipal','MEC','ASST','MUN',4);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASST','Assistant Mechanical Engineer','City','MEC','ASSTENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASST','Assistant Mechanical Engineer','Municipal','MEC','ASSTENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASST','Assistant Mechanical Engineer','Town','MTN','ASSTENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-ASSTFORE','Assistant Parks Foreman','City','GEN','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-ASSTFORE','Assistant Parks Foreman','Municipal','GEN','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-ASST','Assistant Quantity Surveyor','City','SUR','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-ASST','Assistant Quantity Surveyor','Municipal','SUR','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-ASST','Assistant Quantity Surveyor','Town','SUR','ASST','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASSTSUPT','Assistant Superintendent','City','ELE','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-ASSTSUPT','Assistant Superintendent','City','MTN','ASST','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-ASSTSUPT2','Assistant Superintendent','City','MTN','ASST','CIT',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSTSUPT','Assistant Superintendent','City','MEC','ASST','CIT',4);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-ASSTSUPT','Assistant Superintendent','City','GEN','ASST','CIT',5);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ASSTSUPT','Assistant Superintendent','Municipal','ELE','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-ASSTSUPT','Assistant Superintendent','Municipal','MTN','ASST','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSTSUPT','Assistant Superintendent','Municipal','MEC','ASST','MUN',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-ASSTSUPT','Assistant Superintendent','Municipal','GEN','ASST','MUN',4);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASSTSUPT','Assistant Superintendent - Highway','City','GEN','ASST','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WATSAN-ASST','Assistant Water and Sanitation Engineer','Municipal','GEN','ASSTENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-AUTO','Auto Electrician','City','MEC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-AUTO','Auto Electrician','Municipal','MEC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-AUTO','Auto Electrician','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-BRICK','Bricklayer','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-BRICK','Bricklayer','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-BRICK','Bricklayer','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-CARP','Carpenter','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-CARP','Carpenter','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CARP','Carpenter','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-CHIEF','Chief Architect','City','ARC','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-CHIEF','Chief Architect','Municipal','ARC','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-CHIEF','Chief Civil Engineer','City','GEN','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-CHIEF','Chief Civil Engineer','Municipal','GEN','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-CHIEF','Chief Electrical Engineer','City','ELE','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-CHIEF','Chief Electrical Engineer','Municipal','ELE','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-CHIEF','Chief Electrical Engineer','Town','ELE','CHIEF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-CHIEF','Chief Fire Officer','City','FRS','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-CHIEF','Chief Fire Officer','Municipal','FRS','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-CHIEF','Chief Mechanical Engineer','City','MEC','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-CHIEF','Chief Mechanical Engineer - Buildings Construction & Maintenance','Municipal','MEC','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-CHIEF','Chief Quantity Surveyor','City','SUR','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-CHIEF','Chief Quantity Surveyor','Municipal','SUR','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL06','Civil Engineer','City','GEN','ENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL07','Civil Engineer','City','GEN','ENG','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL07','Civil Engineer','Municipal','GEN','ENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL','Civil Engineer','Town','GEN','ENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-CLERK','Clerk of Works','Municipal','ARC','CLK','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','COUNCIL-SEC','Council Secretary','Town','ADM','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DEPUTY','Deputy Chief Fire Officer','City','FRS','CHIEF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DEPUTY','Deputy Chief Fire Officer','Municipal','FRS','CHIEF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-DIR','Director - Engineering','City','GEN','DIR','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-DIR','Director - Engineering','Municipal','GEN','DIR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-DIR','Director - Engineering','Town','GEN','DIR','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DIV','Divisional Fire Officer','City','FRS','OFF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DIV','Divisional Fire Officer','Municipal','FRS','OFF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DIV','Divisional Fire Officer','Town','FRS','OFF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-DRAFT','Draughtsman','City','ARC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-DRAFT','Draughtsman','Municipal','ARC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-DRAFT','Draughtsman','Municipal','GEN','GEN','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-DRAFT','Draughtsman','Town','ARC','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ENG07','Electrical Engineer','City','ELE','ENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-ENG07','Electrical Engineer','Municipal','ELE','ENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-HEAD','Electrical Engineer','Town','ELE','ENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-TECH','Electrician','City','ELE','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-TECH','Electrician','Municipal','ELE','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-TECH','Electrician','Town','ELE','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSIST','Engineering Assistant','City','MEC','ASSTENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASSIST','Engineering Assistant','Municipal','GEN','ASSTENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-ASSIST','Engineering Assistant','Municipal','MEC','ASSTENG','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-TECH','Engineering Assistant','Town','GEN','ASSTENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-ASSIST','Engineering Assistant - Roads','City','GEN','ASSTENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-EXCAV','Excavator Operator','Town','MTN','OP','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE','Firefighter','City','FRS','FF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE','Firefighter','Municipal','FRS','FF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE','Firefighter','Town','FRS','FF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DRV','Firefighter Driver','City','FRS','FFDRV','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DRV','Firefighter Driver','Municipal','FRS','FFDRV','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-DRV','Firefighter Driver','Town','FRS','FFDRV','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-FOREMAN','Foreman','City','GEN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-FOREMAN','Foreman','City','ELE','GEN','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-FOREMAN','Foreman','City','MTN','GEN','CIT',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-FOREMAN','Foreman','City','MEC','GEN','CIT',4);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-FOREMAN','Foreman','Municipal','ARC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-FOREMAN','Foreman','Municipal','GEN','GEN','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-FOREMAN','Foreman','Municipal','ELE','GEN','MUN',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-FOREMAN','Foreman','Municipal','MTN','GEN','MUN',4);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-FOREMAN','Foreman','Municipal','MEC','GEN','MUN',5);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-GENWORK','General Worker','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-WORK','General Worker','City','GEN','GEN','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-GENWORK','General Worker','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-WORK','General Worker','Municipal','GEN','GEN','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-GENWORK','General Worker','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-WORK','General Worker','Town','GEN','GEN','TOW',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-LEAD','Leading Firefighter','City','FRS','FF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-LEAD','Leading Firefighter','Municipal','FRS','FF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-LEAD','Leading Firefighter','Town','FRS','FF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-SUPT','Maintenance Superintendent','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-SUPT','Maintenance Superintendent','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-SUP','Maintenance Superintendent','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-TECH','Mechanic','City','MEC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-TECH','Mechanic','Municipal','MEC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-TECH','Mechanic','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH07','Mechanical Engineer','City','MEC','ENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH','Mechanical Engineer','Town','MEC','ENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH07','Mechanical Engineer - Buildings Construction & Maintenance','Municipal','MEC','ENG','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-HANDY','Mechanical Handyman','City','MEC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-HANDY','Mechanical Handyman','Municipal','MEC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-HANDY','Mechanical Handyman','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MOTOR','Motor Vehicle Examiner','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-PAINT','Painter','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-PAINT','Painter','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PAINT','Painter','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-MGR','Parks & Gardens Manager','City','GEN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-FOREMAN','Parks Foreman','City','GEN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-FOREMAN','Parks Foreman','Municipal','GEN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-MGR','Parks Manager','Municipal','GEN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-MGR','Parks Manager','Town','GEN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-SUP','Parks Supervisor','City','GEN','SUP','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-SUP','Parks Supervisor','Municipal','GEN','SUP','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-SUP','Parks Supervisor','Town','GEN','SUP','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-PLANT','Plant Operator','City','MEC','OP','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-PLANT','Plant Operator','Municipal','MEC','OP','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-PLUM','Plumber','City','MTN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MAINT-PLUM','Plumber','Municipal','MTN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PLUM','Plumber','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-ASSIST','Quantity Surveying Assistant','Municipal','SUR','ASST','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV07','Quantity Surveyor','City','SUR','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV07','Quantity Surveyor','Municipal','SUR','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV','Quantity Surveyor','Town','SUR','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WATSAN-COORD','Rural Water and Sanitation Coordinator','City','GEN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WATSAN-COORD','Rural Water and Sanitation Coordinator','Municipal','GEN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WATSAN-ENG','Rural Water and Sanitation Engineer','City','GEN','ENG','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-SCALER','Scaler Operator','Town','MTN','OP','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ARCH-SENCLERK','Senior Clerk of Works','Municipal','ARC','SNR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CLERK','Senior Clerk of Works','Town','ARC','SNR','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-SEN-SUPT','Senior Electrical Superintendent','City','ELE','SNR','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-SENASSIST','Senior Engineering Assistant','City','GEN','SNR','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-SENASSIST','Senior Engineering Assistant','City','ELE','SNR','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-SENASSIST','Senior Engineering Assistant','Municipal','GEN','SNR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-SENASSIST','Senior Engineering Assistant','Municipal','ELE','SNR','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-QSURV-SENASSIST','Senior Quantity Surveying Assistant','Municipal','SUR','SNR','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-STN','Station Fire Officer','City','FRS','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-STN','Station Fire Officer','Municipal','FRS','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-STN','Station Officer','Town','FRS','STNOFF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-SUB','Sub-Officer','City','FRS','OFF','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-SUB','Sub-Officer','Municipal','FRS','OFF','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-FIRE-SUB','Sub-Officer','Town','FRS','OFF','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-SUPT','Superintendent','City','ELE','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-SUPT','Superintendent','City','MEC','GEN','CIT',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-SUPT','Superintendent','City','GEN','GEN','CIT',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-SUPT','Superintendent','Municipal','ELE','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-SUPT','Superintendent','Municipal','MEC','GEN','MUN',2);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-PARK-SUPT','Superintendent','Municipal','GEN','GEN','MUN',3);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-HIGHWAY','Superintendent – Highway','City','GEN','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-CIVIL-HIGHWAY','Superintendent – Highway','Municipal','GEN','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','CITY-CLERK','Town Clerk','City','ADM','CLK','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','TOWN-CLERK','Town Clerk','Municipal','ADM','CLK','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WATSAN','Water and Sanitation Engineer','Town','GEN','ENG','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-WELDER','Welder','City','MEC','GEN','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-MECH-WELDER','Welder','Municipal','MEC','GEN','MUN',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-WELDER','Welder','Town','MTN','GEN','TOW',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-WORKSUP','Works Supervisor','City','ELE','SUP','CIT',TRUE);
INSERT INTO position_standard_id_map VALUES('ENG','ENG-ELEC-WORKSUP','Works Supervisor','Municipal','ELE','SUP','MUN',TRUE);
