INSERT INTO position_role_codes VALUES('Council Secretary','COUNCSEC','Leadership');
INSERT INTO position_role_codes VALUES('Town Clerk','TOWNCLRK','Leadership');
INSERT INTO position_role_codes VALUES('Director - Engineering','DIRENG','Leadership');
INSERT INTO position_role_codes VALUES('Assistant Director - Engineering','ADIRENG','Leadership');
INSERT INTO position_role_codes VALUES('Assistant Director - Construction & Maintenance','ADIRCONST','Leadership');
INSERT INTO position_role_codes VALUES('Assistant Director - Roads & Drainages','ADIRROADS','Leadership');
INSERT INTO position_role_codes VALUES('Architect','ARCH','Architecture');
INSERT INTO position_role_codes VALUES('Assistant Architect','ASSTARCH','Architecture');
INSERT INTO position_role_codes VALUES('Chief Architect','CHIEFARCH','Architecture');
INSERT INTO position_role_codes VALUES('Architectural Assistant','ARCHASST','Architecture');
INSERT INTO position_role_codes VALUES('Draughtsman','DRAFT','Architecture');
INSERT INTO position_role_codes VALUES('Senior Clerk of Works','SNRCLRKWRK','Architecture');
INSERT INTO position_role_codes VALUES('Clerk of Works','CLRKWRK','Architecture');
INSERT INTO position_role_codes VALUES('Civil Engineer','CIVENG','Civil');
INSERT INTO position_role_codes VALUES('Chief Civil Engineer','CHIEFCIV','Civil');
INSERT INTO position_role_codes VALUES('Assistant Civil Engineer','ASSTCIV','Civil');
INSERT INTO position_role_codes VALUES('Engineering Assistant','ENGASST','Civil');
INSERT INTO position_role_codes VALUES('Engineering Assistant - Roads','ENGASSTRD','Civil');
INSERT INTO position_role_codes VALUES('Senior Engineering Assistant','SNRENGASST','Civil');
INSERT INTO position_role_codes VALUES('Superintendent – Highway','SUPTHWY','Civil');
INSERT INTO position_role_codes VALUES('Assistant Superintendent - Highway','ASSTSUPTHWY','Civil');
INSERT INTO position_role_codes VALUES('Electrical Engineer','ELECENG','Electrical');
INSERT INTO position_role_codes VALUES('Chief Electrical Engineer','CHIEFELEC','Electrical');
INSERT INTO position_role_codes VALUES('Assistant Electrical Engineer','ASSTELEC','Electrical');
INSERT INTO position_role_codes VALUES('Electrician','ELEC','Electrical');
INSERT INTO position_role_codes VALUES('Senior Electrical Superintendent','SNRELECSUPT','Electrical');
INSERT INTO position_role_codes VALUES('Works Supervisor','WRKSUP','Electrical');
INSERT INTO position_role_codes VALUES('Mechanical Engineer','MECHENG','Mechanical');
INSERT INTO position_role_codes VALUES('Mechanical Engineer - Buildings Construction & Maintenance','MECHENGBLD','Mechanical');
INSERT INTO position_role_codes VALUES('Chief Mechanical Engineer','CHIEFMECH','Mechanical');
INSERT INTO position_role_codes VALUES('Chief Mechanical Engineer - Buildings Construction & Maintenance','CHIEFMECHBLD','Mechanical');
INSERT INTO position_role_codes VALUES('Assistant Mechanical Engineer','ASSTMECH','Mechanical');
INSERT INTO position_role_codes VALUES('Mechanic','MECH','Mechanical');
INSERT INTO position_role_codes VALUES('Mechanical Handyman','MECHHAND','Mechanical');
INSERT INTO position_role_codes VALUES('Auto Electrician','AUTOELEC','Mechanical');
INSERT INTO position_role_codes VALUES('Motor Vehicle Examiner','MVE','Mechanical');
INSERT INTO position_role_codes VALUES('Plant Operator','PLANTOP','Mechanical');
INSERT INTO position_role_codes VALUES('Welder','WELD','Mechanical');
INSERT INTO position_role_codes VALUES('Excavator Operator','EXCAV','Mechanical');
INSERT INTO position_role_codes VALUES('Scaler Operator','SCALER','Mechanical');
INSERT INTO position_role_codes VALUES('Chief Fire Officer','CHIEFFIRE','Fire');
INSERT INTO position_role_codes VALUES('Deputy Chief Fire Officer','DEPCHIEFFIRE','Fire');
INSERT INTO position_role_codes VALUES('Divisional Fire Officer','DIVFIRE','Fire');
INSERT INTO position_role_codes VALUES('Assistant Divisional Fire Officer','ASSTDIVFIRE','Fire');
INSERT INTO position_role_codes VALUES('Station Officer','STNOFF','Fire');
INSERT INTO position_role_codes VALUES('Station Fire Officer','STNFIRE','Fire');
INSERT INTO position_role_codes VALUES('Sub-Officer','SUBOFF','Fire');
INSERT INTO position_role_codes VALUES('Leading Firefighter','LDFF','Fire');
INSERT INTO position_role_codes VALUES('Firefighter','FF','Fire');
INSERT INTO position_role_codes VALUES('Firefighter Driver','FFDRV','Fire');
INSERT INTO position_role_codes VALUES('Quantity Surveyor','QS','Quantity Surveying');
INSERT INTO position_role_codes VALUES('Chief Quantity Surveyor','CHIEFQS','Quantity Surveying');
INSERT INTO position_role_codes VALUES('Assistant Quantity Surveyor','ASSTQS','Quantity Surveying');
INSERT INTO position_role_codes VALUES('Quantity Surveying Assistant','QSASST','Quantity Surveying');
INSERT INTO position_role_codes VALUES('Senior Quantity Surveying Assistant','SNRQSASST','Quantity Surveying');
INSERT INTO position_role_codes VALUES('Maintenance Superintendent','MAINTSUPT','Maintenance');
INSERT INTO position_role_codes VALUES('Plumber','PLUMB','Maintenance');
INSERT INTO position_role_codes VALUES('Bricklayer','BRICK','Maintenance');
INSERT INTO position_role_codes VALUES('Carpenter','CARP','Maintenance');
INSERT INTO position_role_codes VALUES('Painter','PAINT','Maintenance');
INSERT INTO position_role_codes VALUES('General Worker','GENWK','Maintenance');
INSERT INTO position_role_codes VALUES('Parks Manager','PARKMGR','Parks');
INSERT INTO position_role_codes VALUES('Parks & Gardens Manager','PARKGMGR','Parks');
INSERT INTO position_role_codes VALUES('Parks Foreman','PARKFORE','Parks');
INSERT INTO position_role_codes VALUES('Assistant Parks Foreman','ASSTPARKFORE','Parks');
INSERT INTO position_role_codes VALUES('Parks Supervisor','PARKSUP','Parks');
INSERT INTO position_role_codes VALUES('Water and Sanitation Engineer','WATSANENG','Water');
INSERT INTO position_role_codes VALUES('Rural Water and Sanitation Coordinator','RURALWATCOORD','Water');
INSERT INTO position_role_codes VALUES('Rural Water and Sanitation Engineer','RURALWATENG','Water');
INSERT INTO position_role_codes VALUES('Assistant Water and Sanitation Engineer','ASSTWATENG','Water');
INSERT INTO position_role_codes VALUES('Foreman','FORE','General');
INSERT INTO position_role_codes VALUES('Assistant Foreman','ASSTFORE','General');
INSERT INTO position_role_codes VALUES('Superintendent','SUPT','General');
INSERT INTO position_role_codes VALUES('Assistant Superintendent','ASSTSUPT','General');
