INSERT INTO salary_scales VALUES(1,'LGSS/01','Town Clerk - City Council',TRUE,'City Council');
INSERT INTO salary_scales VALUES(2,'LGSS/02','Town Clerk - Municipal Council',2,'Municipal Council');
INSERT INTO salary_scales VALUES(3,'LGSS/03','Council Secretary - Town Council',3,'Town Council');
INSERT INTO salary_scales VALUES(4,'LGSS/05','Assistant Director - Public Health (Municipal/City)',5,'Municipal/City Council');
INSERT INTO salary_scales VALUES(5,'LGSS/06','Assistant Director - Public Health (Town) / Chief Officer',6,'All');
INSERT INTO salary_scales VALUES(6,'LGSS/07','Senior Officer Level',7,'All');
INSERT INTO salary_scales VALUES(7,'LGSS/08','Officer Level',8,'All');
INSERT INTO salary_scales VALUES(8,'LGSS/09','Superintendent Level',9,'All');
INSERT INTO salary_scales VALUES(9,'LGSS/10','Assistant Superintendent Level',10,'All');
INSERT INTO salary_scales VALUES(10,'LGSS/17','Support Staff Level',17,'All');
INSERT INTO salary_scales VALUES(11,'LGSS','General LGSS Scale',15,'All');
INSERT INTO salary_scales VALUES(12,'G1','General Staff Level 1',20,'All');
INSERT INTO salary_scales VALUES(13,'G3','General Staff Level 3',22,'All');
