INSERT INTO sections VALUES(1,'Leadership','LEAD-MC','Municipal Council Leadership');
INSERT INTO sections VALUES(2,'Human Resource Section','HR-MC','Human Resource Management - Municipal');
INSERT INTO sections VALUES(3,'Administration Section','ADMIN-MC','General Administration - Municipal');
INSERT INTO sections VALUES(4,'Registry Unit','REG-MC','Records Management - Municipal');
INSERT INTO sections VALUES(5,'Committee Section','COMM-MC','Committee Services - Municipal');
INSERT INTO sections VALUES(6,'Security Section','SEC-MC','Security Services - Municipal');
INSERT INTO sections VALUES(7,'Leadership','LEAD-CC','City Council Leadership');
INSERT INTO sections VALUES(8,'HR Management & Development','HRMD-CC','Human Resource Management and Development - City');
INSERT INTO sections VALUES(9,'Administration Section','ADMIN-SEC-CC','Administration Section - City');
INSERT INTO sections VALUES(10,'Administration Unit','ADMIN-UNIT-CC','Administration Unit - City');
INSERT INTO sections VALUES(11,'Registry Unit','REG-CC','Records Management - City');
INSERT INTO sections VALUES(12,'Committee Section','COMM-CC','Committee Services - City');
INSERT INTO sections VALUES(13,'Security Section','SEC-CC','Security Services - City');
