-- V56 -- Create Directorate Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the authoritative registry of organisational directorates.
-- Child organisational structures (sections, units and positions) are
-- introduced in subsequent migrations.

CREATE TABLE IF NOT EXISTS directorate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code  VARCHAR(10) NOT NULL,

    directorate_code VARCHAR(30) NOT NULL,

    name            VARCHAR(150) NOT NULL,

    description     TEXT,

    is_active       BOOLEAN NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_directorate_code_not_blank
        CHECK (BTRIM(directorate_code) <> ''),

    CONSTRAINT chk_directorate_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT chk_directorate_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT uq_directorate_authority_code
        UNIQUE (authority_code, directorate_code)
);

CREATE INDEX IF NOT EXISTS idx_directorate_authority
    ON directorate(authority_code);

CREATE INDEX IF NOT EXISTS idx_directorate_active
    ON directorate(authority_code, is_active);

CREATE INDEX IF NOT EXISTS idx_directorate_name
    ON directorate(authority_code, name);
