-- V57 -- Create Section Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the authoritative registry of organisational sections.
-- Each section belongs to one directorate within the same authority.

CREATE TABLE IF NOT EXISTS section (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code   VARCHAR(10) NOT NULL,

    directorate_id   BIGINT NOT NULL,

    section_code     VARCHAR(30) NOT NULL,

    name             VARCHAR(150) NOT NULL,

    description      TEXT,

    is_active        BOOLEAN NOT NULL DEFAULT TRUE,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_section_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_section_code_not_blank
        CHECK (BTRIM(section_code) <> ''),

    CONSTRAINT chk_section_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT fk_section_directorate
        FOREIGN KEY (directorate_id)
        REFERENCES directorate(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_section_authority_code
        UNIQUE (authority_code, section_code)
);

CREATE INDEX IF NOT EXISTS idx_section_authority
    ON section(authority_code);

CREATE INDEX IF NOT EXISTS idx_section_directorate
    ON section(directorate_id);

CREATE INDEX IF NOT EXISTS idx_section_active
    ON section(authority_code, is_active);

CREATE INDEX IF NOT EXISTS idx_section_name
    ON section(authority_code, name);
