-- V58 -- Create Unit Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the authoritative registry of organisational units.
-- Each unit belongs to one section within the same authority.

CREATE TABLE IF NOT EXISTS unit (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code   VARCHAR(10) NOT NULL,

    section_id       BIGINT NOT NULL,

    unit_code        VARCHAR(30) NOT NULL,

    name             VARCHAR(150) NOT NULL,

    description      TEXT,

    is_active        BOOLEAN NOT NULL DEFAULT TRUE,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_unit_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_unit_code_not_blank
        CHECK (BTRIM(unit_code) <> ''),

    CONSTRAINT chk_unit_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT fk_unit_section
        FOREIGN KEY (section_id)
        REFERENCES section(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_unit_authority_code
        UNIQUE (authority_code, unit_code)
);

CREATE INDEX IF NOT EXISTS idx_unit_authority
    ON unit(authority_code);

CREATE INDEX IF NOT EXISTS idx_unit_section
    ON unit(section_id);

CREATE INDEX IF NOT EXISTS idx_unit_active
    ON unit(authority_code, is_active);

CREATE INDEX IF NOT EXISTS idx_unit_name
    ON unit(authority_code, name);
