-- V59 -- Create Position Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the authoritative registry of organisational positions.
-- A position belongs to one unit within the same authority.
--
-- Positions are structural records and may be:
--   * occupied
--   * vacant
--   * funded
--   * unfunded
--
-- A vacant funded position remains part of the establishment.

CREATE TABLE IF NOT EXISTS position (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    unit_id             BIGINT NOT NULL,

    position_code       VARCHAR(40) NOT NULL,

    title               VARCHAR(200) NOT NULL,

    description         TEXT,

    is_funded           BOOLEAN NOT NULL DEFAULT FALSE,

    funding_year        INTEGER,

    is_occupied         BOOLEAN NOT NULL DEFAULT FALSE,

    is_active           BOOLEAN NOT NULL DEFAULT TRUE,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_position_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_position_code_not_blank
        CHECK (BTRIM(position_code) <> ''),

    CONSTRAINT chk_position_title_not_blank
        CHECK (BTRIM(title) <> ''),

    CONSTRAINT chk_position_funding_year
        CHECK (
            funding_year IS NULL
            OR funding_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT chk_position_funding_consistency
        CHECK (
            is_funded = TRUE
            OR funding_year IS NULL
        ),

    CONSTRAINT fk_position_unit
        FOREIGN KEY (unit_id)
        REFERENCES unit(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_position_authority_code
        UNIQUE (authority_code, position_code)
);

CREATE INDEX IF NOT EXISTS idx_position_authority
    ON position(authority_code);

CREATE INDEX IF NOT EXISTS idx_position_unit
    ON position(unit_id);

CREATE INDEX IF NOT EXISTS idx_position_active
    ON position(authority_code, is_active);

CREATE INDEX IF NOT EXISTS idx_position_funded
    ON position(authority_code, is_funded, funding_year);

CREATE INDEX IF NOT EXISTS idx_position_occupied
    ON position(authority_code, is_occupied);

CREATE INDEX IF NOT EXISTS idx_position_title
    ON position(authority_code, title);
