-- V60 -- Create Position Placement Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the historical relationship between employees and
-- organisational positions.
--
-- A position is an organisational structure.
-- A placement records an employee occupying that position.
--
-- This allows:
--   * historical occupants
--   * current occupants
--   * vacant positions
--   * employee transfers between positions
--   * preservation of organisational history

CREATE TABLE IF NOT EXISTS position_placement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    position_id         BIGINT NOT NULL,

    employee_id         BIGINT NOT NULL,

    placement_start_date DATE NOT NULL,

    placement_end_date   DATE,

    is_current          BOOLEAN NOT NULL DEFAULT TRUE,

    placement_reason    VARCHAR(100),

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_position_placement_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_position_placement_dates
        CHECK (
            placement_end_date IS NULL
            OR placement_end_date >= placement_start_date
        ),

    CONSTRAINT fk_position_placement_position
        FOREIGN KEY (position_id)
        REFERENCES position(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_placement_employee
        FOREIGN KEY (employee_id)
        REFERENCES erp_employee(id)
        ON DELETE RESTRICT
);

-- General authority lookup
CREATE INDEX IF NOT EXISTS idx_position_placement_authority
    ON position_placement(authority_code);

-- Find all placements for a position
CREATE INDEX IF NOT EXISTS idx_position_placement_position
    ON position_placement(position_id);

-- Find all placements for an employee
CREATE INDEX IF NOT EXISTS idx_position_placement_employee
    ON position_placement(employee_id);

-- Find current placements within an authority
CREATE INDEX IF NOT EXISTS idx_position_placement_current
    ON position_placement(authority_code, is_current);

-- Find an employee's placement history
CREATE INDEX IF NOT EXISTS idx_position_placement_employee_dates
    ON position_placement(employee_id, placement_start_date DESC);

-- Find a position's placement history
CREATE INDEX IF NOT EXISTS idx_position_placement_position_dates
    ON position_placement(position_id, placement_start_date DESC);
