-- V61 -- Create Position Establishment & Funding Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes year-specific establishment and funding information
-- for organisational positions.
--
-- A position is a permanent organisational structure.
-- Its establishment/funding status may vary by financial year.
--
-- This allows the system to represent:
--   * funded positions
--   * unfunded positions
--   * vacant funded positions
--   * occupied funded positions
--   * historical establishment records
--
-- A vacant funded position remains part of the establishment.

CREATE TABLE IF NOT EXISTS position_establishment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    position_id         BIGINT NOT NULL,

    establishment_year  INTEGER NOT NULL,

    is_established      BOOLEAN NOT NULL DEFAULT TRUE,

    is_funded           BOOLEAN NOT NULL DEFAULT FALSE,

    funding_source      VARCHAR(100),

    approved_headcount  INTEGER NOT NULL DEFAULT 1,

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_position_establishment_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_position_establishment_year
        CHECK (
            establishment_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT chk_position_establishment_headcount
        CHECK (
            approved_headcount >= 0
        ),

    CONSTRAINT chk_position_establishment_funding
        CHECK (
            is_funded = TRUE
            OR funding_source IS NULL
        ),

    CONSTRAINT fk_position_establishment_position
        FOREIGN KEY (position_id)
        REFERENCES position(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_position_establishment_year
        UNIQUE (authority_code, position_id, establishment_year)
);

CREATE INDEX IF NOT EXISTS idx_position_establishment_authority
    ON position_establishment(authority_code);

CREATE INDEX IF NOT EXISTS idx_position_establishment_position
    ON position_establishment(position_id);

CREATE INDEX IF NOT EXISTS idx_position_establishment_year
    ON position_establishment(authority_code, establishment_year);

CREATE INDEX IF NOT EXISTS idx_position_establishment_funded
    ON position_establishment(
        authority_code,
        establishment_year,
        is_funded
    );

CREATE INDEX IF NOT EXISTS idx_position_establishment_established
    ON position_establishment(
        authority_code,
        establishment_year,
        is_established
    );
