-- V62 -- Create Position Establishment History
-- Organisation Management Architecture (OMAS)
--
-- Preserves the historical establishment and funding state of
-- organisational positions.
--
-- V61 represents the year-specific establishment registry.
-- V62 preserves changes made to those establishment records.
--
-- This allows the system to answer:
--   * When was a position established?
--   * When did its funding status change?
--   * What was the approved headcount at a particular point in time?
--   * Who made the change?
--   * Why was the establishment/funding status changed?

CREATE TABLE IF NOT EXISTS position_establishment_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    position_establishment_id BIGINT NOT NULL,

    position_id         BIGINT NOT NULL,

    establishment_year  INTEGER NOT NULL,

    is_established      BOOLEAN NOT NULL,

    is_funded           BOOLEAN NOT NULL,

    funding_source      VARCHAR(100),

    approved_headcount  INTEGER NOT NULL,

    change_type         VARCHAR(30) NOT NULL,

    change_reason       VARCHAR(255),

    changed_by          VARCHAR(120),

    changed_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    notes               TEXT,

    CONSTRAINT chk_position_est_history_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_position_est_history_year
        CHECK (
            establishment_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT chk_position_est_history_headcount
        CHECK (
            approved_headcount >= 0
        ),

    CONSTRAINT chk_position_est_history_funding
        CHECK (
            is_funded = TRUE
            OR funding_source IS NULL
        ),

    CONSTRAINT chk_position_est_history_change_type
        CHECK (
            BTRIM(change_type) <> ''
        ),

    CONSTRAINT fk_position_est_history_establishment
        FOREIGN KEY (position_establishment_id)
        REFERENCES position_establishment(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_est_history_position
        FOREIGN KEY (position_id)
        REFERENCES position(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_position_est_history_authority
    ON position_establishment_history(authority_code);

CREATE INDEX IF NOT EXISTS idx_position_est_history_establishment
    ON position_establishment_history(position_establishment_id);

CREATE INDEX IF NOT EXISTS idx_position_est_history_position
    ON position_establishment_history(position_id);

CREATE INDEX IF NOT EXISTS idx_position_est_history_year
    ON position_establishment_history(
        authority_code,
        establishment_year
    );

CREATE INDEX IF NOT EXISTS idx_position_est_history_changed
    ON position_establishment_history(
        position_id,
        changed_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_position_est_history_change_type
    ON position_establishment_history(
        authority_code,
        change_type
    );
