-- V63 -- Create Position Placement History
-- Organisation Management Architecture (OMAS)
--
-- Preserves historical changes to employee position placements.
--
-- V60 records the employee's placement relationship.
-- V63 records the history of changes to that relationship.
--
-- This allows the system to preserve:
--   * appointments
--   * transfers
--   * promotions
--   * acting appointments
--   * reassignment
--   * placement termination
--   * historical organisational occupancy

CREATE TABLE IF NOT EXISTS position_placement_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    position_placement_id BIGINT NOT NULL,

    position_id         BIGINT NOT NULL,

    employee_id         BIGINT NOT NULL,

    placement_start_date DATE NOT NULL,

    placement_end_date   DATE,

    is_current          BOOLEAN NOT NULL,

    placement_reason    VARCHAR(100),

    change_type         VARCHAR(30) NOT NULL,

    change_reason       VARCHAR(255),

    changed_by          VARCHAR(120),

    changed_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    notes               TEXT,

    CONSTRAINT chk_position_placement_history_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_position_placement_history_dates
        CHECK (
            placement_end_date IS NULL
            OR placement_end_date >= placement_start_date
        ),

    CONSTRAINT chk_position_placement_history_change_type
        CHECK (
            BTRIM(change_type) <> ''
        ),

    CONSTRAINT fk_position_placement_history_placement
        FOREIGN KEY (position_placement_id)
        REFERENCES position_placement(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_placement_history_position
        FOREIGN KEY (position_id)
        REFERENCES position(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_placement_history_employee
        FOREIGN KEY (employee_id)
        REFERENCES erp_employee(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_position_placement_history_authority
    ON position_placement_history(authority_code);

CREATE INDEX IF NOT EXISTS idx_position_placement_history_placement
    ON position_placement_history(position_placement_id);

CREATE INDEX IF NOT EXISTS idx_position_placement_history_position
    ON position_placement_history(position_id);

CREATE INDEX IF NOT EXISTS idx_position_placement_history_employee
    ON position_placement_history(employee_id);

CREATE INDEX IF NOT EXISTS idx_position_placement_history_changed
    ON position_placement_history(
        position_placement_id,
        changed_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_position_placement_history_employee_dates
    ON position_placement_history(
        employee_id,
        placement_start_date DESC
    );

CREATE INDEX IF NOT EXISTS idx_position_placement_history_change_type
    ON position_placement_history(
        authority_code,
        change_type
    );
