-- V64 -- Create Organisation Structure Audit Log
-- Organisation Management Architecture (OMAS)
--
-- Provides an immutable audit trail for structural changes to:
--   * directorates
--   * sections
--   * units
--   * positions
--
-- This is an audit/event registry and does not replace the
-- authoritative organisational tables.

CREATE TABLE IF NOT EXISTS organisation_structure_audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    entity_type         VARCHAR(30) NOT NULL,

    entity_id           BIGINT NOT NULL,

    action_type         VARCHAR(30) NOT NULL,

    old_value           JSONB,

    new_value           JSONB,

    reason              VARCHAR(255),

    performed_by        VARCHAR(120),

    performed_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    notes               TEXT,

    CONSTRAINT chk_org_structure_audit_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_org_structure_audit_entity_type
        CHECK (
            entity_type IN (
                'DIRECTORATE',
                'SECTION',
                'UNIT',
                'POSITION'
            )
        ),

    CONSTRAINT chk_org_structure_audit_action_type
        CHECK (
            action_type IN (
                'CREATE',
                'UPDATE',
                'ACTIVATE',
                'DEACTIVATE',
                'DELETE',
                'TRANSFER'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_org_structure_audit_authority
    ON organisation_structure_audit_log(authority_code);

CREATE INDEX IF NOT EXISTS idx_org_structure_audit_entity
    ON organisation_structure_audit_log(
        entity_type,
        entity_id
    );

CREATE INDEX IF NOT EXISTS idx_org_structure_audit_action
    ON organisation_structure_audit_log(
        authority_code,
        action_type
    );

CREATE INDEX IF NOT EXISTS idx_org_structure_audit_performed
    ON organisation_structure_audit_log(
        performed_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_org_structure_audit_entity_history
    ON organisation_structure_audit_log(
        entity_type,
        entity_id,
        performed_at DESC
    );
