-- V65 -- Create Organisation Structure Source Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes the authoritative registry of source documents,
-- approvals and import batches used to establish organisational
-- structures.
--
-- This provides provenance for:
--   * directorates
--   * sections
--   * units
--   * positions
--   * establishment records
--
-- The organisational structure itself remains in the OMAS registry
-- tables. This table records where that structure came from.

CREATE TABLE IF NOT EXISTS organisation_structure_source (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    source_reference    VARCHAR(100) NOT NULL,

    source_type         VARCHAR(30) NOT NULL,

    title               VARCHAR(200) NOT NULL,

    description         TEXT,

    source_date         DATE,

    effective_date      DATE,

    reporting_year      INTEGER,

    import_batch        VARCHAR(100),

    approval_status     VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    approved_by         VARCHAR(120),

    approved_at         TIMESTAMPTZ,

    imported_by         VARCHAR(120),

    imported_at         TIMESTAMPTZ,

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_org_source_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_org_source_reference_not_blank
        CHECK (BTRIM(source_reference) <> ''),

    CONSTRAINT chk_org_source_type_not_blank
        CHECK (BTRIM(source_type) <> ''),

    CONSTRAINT chk_org_source_title_not_blank
        CHECK (BTRIM(title) <> ''),

    CONSTRAINT chk_org_source_reporting_year
        CHECK (
            reporting_year IS NULL
            OR reporting_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT chk_org_source_approval_status
        CHECK (
            approval_status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'SUPERSEDED'
            )
        ),

    CONSTRAINT chk_org_source_approval_details
        CHECK (
            approval_status <> 'APPROVED'
            OR approved_by IS NOT NULL
        ),

    CONSTRAINT uq_org_source_authority_reference
        UNIQUE (authority_code, source_reference)
);

CREATE INDEX IF NOT EXISTS idx_org_source_authority
    ON organisation_structure_source(authority_code);

CREATE INDEX IF NOT EXISTS idx_org_source_type
    ON organisation_structure_source(authority_code, source_type);

CREATE INDEX IF NOT EXISTS idx_org_source_status
    ON organisation_structure_source(
        authority_code,
        approval_status
    );

CREATE INDEX IF NOT EXISTS idx_org_source_reporting_year
    ON organisation_structure_source(
        authority_code,
        reporting_year
    );

CREATE INDEX IF NOT EXISTS idx_org_source_import_batch
    ON organisation_structure_source(
        authority_code,
        import_batch
    );

CREATE INDEX IF NOT EXISTS idx_org_source_effective_date
    ON organisation_structure_source(
        authority_code,
        effective_date
    );
