-- V66 -- Create Organisation Structure Source Link Registry
-- Organisation Management Architecture (OMAS)
--
-- Establishes provenance links between organisational structure
-- records and their authoritative source records.
--
-- A structure record may have multiple supporting sources.
-- A source may support multiple organisational structure records.
--
-- Supported OMAS entities:
--   * DIRECTORATE
--   * SECTION
--   * UNIT
--   * POSITION
--
-- This table records provenance without coupling the core
-- organisational tables directly to a single source document.

CREATE TABLE IF NOT EXISTS organisation_structure_source_link (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    source_id           BIGINT NOT NULL,

    entity_type         VARCHAR(30) NOT NULL,

    entity_id           BIGINT NOT NULL,

    relationship_type   VARCHAR(30) NOT NULL DEFAULT 'PRIMARY',

    notes               TEXT,

    created_by          VARCHAR(120),

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_org_source_link_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_org_source_link_entity_type
        CHECK (
            entity_type IN (
                'DIRECTORATE',
                'SECTION',
                'UNIT',
                'POSITION'
            )
        ),

    CONSTRAINT chk_org_source_link_entity_id
        CHECK (entity_id > 0),

    CONSTRAINT chk_org_source_link_relationship
        CHECK (
            relationship_type IN (
                'PRIMARY',
                'SUPPORTING',
                'AMENDMENT',
                'SUPERSEDES'
            )
        ),

    CONSTRAINT fk_org_source_link_source
        FOREIGN KEY (source_id)
        REFERENCES organisation_structure_source(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_org_source_link
        UNIQUE (
            authority_code,
            source_id,
            entity_type,
            entity_id,
            relationship_type
        )
);

-- Authority-level lookup
CREATE INDEX IF NOT EXISTS idx_org_source_link_authority
    ON organisation_structure_source_link(authority_code);

-- Find all organisational records derived from a source
CREATE INDEX IF NOT EXISTS idx_org_source_link_source
    ON organisation_structure_source_link(source_id);

-- Find sources associated with a particular organisational record
CREATE INDEX IF NOT EXISTS idx_org_source_link_entity
    ON organisation_structure_source_link(entity_type, entity_id);

-- Find sources associated with an entity within an authority
CREATE INDEX IF NOT EXISTS idx_org_source_link_authority_entity
    ON organisation_structure_source_link(
        authority_code,
        entity_type,
        entity_id
    );

-- Find primary/supporting source relationships
CREATE INDEX IF NOT EXISTS idx_org_source_link_relationship
    ON organisation_structure_source_link(
        authority_code,
        relationship_type
    );
