-- V67 -- Create Enterprise Data Exchange Framework
-- Organisation Management Architecture (OMAS)
--
-- Provides the reusable enterprise data exchange foundation for
-- receiving, staging, validating, reconciling and publishing
-- externally supplied data.
--
-- Module-specific import behaviour is introduced in later migrations.
-- V68 will build the Organisation Import Engine on this framework.

CREATE TABLE IF NOT EXISTS data_exchange_batch (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    batch_reference     VARCHAR(100) NOT NULL,

    exchange_type       VARCHAR(50) NOT NULL,

    source_system       VARCHAR(100),

    source_reference    VARCHAR(150),

    received_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    received_by         VARCHAR(120),

    status              VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',

    total_records       INTEGER NOT NULL DEFAULT 0,

    valid_records       INTEGER NOT NULL DEFAULT 0,

    invalid_records     INTEGER NOT NULL DEFAULT 0,

    reconciled_records  INTEGER NOT NULL DEFAULT 0,

    committed_records   INTEGER NOT NULL DEFAULT 0,

    rejected_records    INTEGER NOT NULL DEFAULT 0,

    completed_at        TIMESTAMPTZ,

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_data_exchange_batch_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_data_exchange_batch_reference_not_blank
        CHECK (BTRIM(batch_reference) <> ''),

    CONSTRAINT chk_data_exchange_batch_type_not_blank
        CHECK (BTRIM(exchange_type) <> ''),

    CONSTRAINT chk_data_exchange_batch_status
        CHECK (
            status IN (
                'RECEIVED',
                'STAGING',
                'VALIDATING',
                'VALIDATED',
                'RECONCILING',
                'RECONCILED',
                'COMMITTING',
                'COMMITTED',
                'PARTIALLY_COMMITTED',
                'REJECTED',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_data_exchange_batch_counts
        CHECK (
            total_records >= 0
            AND valid_records >= 0
            AND invalid_records >= 0
            AND reconciled_records >= 0
            AND committed_records >= 0
            AND rejected_records >= 0
        ),

    CONSTRAINT uq_data_exchange_batch_reference
        UNIQUE (authority_code, batch_reference)
);

CREATE INDEX IF NOT EXISTS idx_data_exchange_batch_authority
    ON data_exchange_batch(authority_code);

CREATE INDEX IF NOT EXISTS idx_data_exchange_batch_status
    ON data_exchange_batch(authority_code, status);

CREATE INDEX IF NOT EXISTS idx_data_exchange_batch_type
    ON data_exchange_batch(authority_code, exchange_type);

CREATE INDEX IF NOT EXISTS idx_data_exchange_batch_received
    ON data_exchange_batch(authority_code, received_at DESC);


-- ============================================================
-- Exchange Records
-- ============================================================

CREATE TABLE IF NOT EXISTS data_exchange_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    batch_id            BIGINT NOT NULL,

    authority_code      VARCHAR(10) NOT NULL,

    record_number       INTEGER NOT NULL,

    external_key        VARCHAR(150),

    record_type         VARCHAR(50) NOT NULL,

    raw_data            JSONB NOT NULL,

    normalized_data     JSONB,

    processing_status   VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',

    validation_status   VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    reconciliation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    commit_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    error_count         INTEGER NOT NULL DEFAULT 0,

    warning_count       INTEGER NOT NULL DEFAULT 0,

    processed_at        TIMESTAMPTZ,

    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_data_exchange_record_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_data_exchange_record_number
        CHECK (record_number > 0),

    CONSTRAINT chk_data_exchange_record_type_not_blank
        CHECK (BTRIM(record_type) <> ''),

    CONSTRAINT chk_data_exchange_record_processing_status
        CHECK (
            processing_status IN (
                'RECEIVED',
                'STAGED',
                'VALIDATING',
                'VALIDATED',
                'RECONCILING',
                'RECONCILED',
                'COMMITTING',
                'COMMITTED',
                'REJECTED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_data_exchange_record_validation_status
        CHECK (
            validation_status IN (
                'PENDING',
                'VALID',
                'INVALID',
                'WARNING'
            )
        ),

    CONSTRAINT chk_data_exchange_record_reconciliation_status
        CHECK (
            reconciliation_status IN (
                'PENDING',
                'MATCHED',
                'NEW',
                'CONFLICT',
                'RESOLVED',
                'REJECTED'
            )
        ),

    CONSTRAINT chk_data_exchange_record_commit_status
        CHECK (
            commit_status IN (
                'PENDING',
                'READY',
                'COMMITTED',
                'REJECTED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_data_exchange_record_counts
        CHECK (
            error_count >= 0
            AND warning_count >= 0
        ),

    CONSTRAINT fk_data_exchange_record_batch
        FOREIGN KEY (batch_id)
        REFERENCES data_exchange_batch(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_batch
    ON data_exchange_record(batch_id);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_authority
    ON data_exchange_record(authority_code);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_status
    ON data_exchange_record(batch_id, processing_status);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_validation
    ON data_exchange_record(batch_id, validation_status);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_reconciliation
    ON data_exchange_record(batch_id, reconciliation_status);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_commit
    ON data_exchange_record(batch_id, commit_status);

CREATE INDEX IF NOT EXISTS idx_data_exchange_record_external_key
    ON data_exchange_record(authority_code, external_key);


-- ============================================================
-- Exchange Errors
-- ============================================================

CREATE TABLE IF NOT EXISTS data_exchange_error (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    batch_id            BIGINT NOT NULL,

    record_id           BIGINT,

    authority_code      VARCHAR(10) NOT NULL,

    error_stage         VARCHAR(30) NOT NULL,

    error_code          VARCHAR(50) NOT NULL,

    error_message       TEXT NOT NULL,

    field_name          VARCHAR(100),

    severity            VARCHAR(20) NOT NULL DEFAULT 'ERROR',

    resolved             BOOLEAN NOT NULL DEFAULT FALSE,

    resolved_by          VARCHAR(120),

    resolved_at         TIMESTAMPTZ,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_data_exchange_error_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_data_exchange_error_stage
        CHECK (
            error_stage IN (
                'RECEIVE',
                'STAGING',
                'VALIDATION',
                'RECONCILIATION',
                'COMMIT'
            )
        ),

    CONSTRAINT chk_data_exchange_error_code_not_blank
        CHECK (BTRIM(error_code) <> ''),

    CONSTRAINT chk_data_exchange_error_message_not_blank
        CHECK (BTRIM(error_message) <> ''),

    CONSTRAINT chk_data_exchange_error_severity
        CHECK (
            severity IN (
                'INFO',
                'WARNING',
                'ERROR',
                'CRITICAL'
            )
        ),

    CONSTRAINT chk_data_exchange_error_resolution
        CHECK (
            resolved = FALSE
            OR resolved_at IS NOT NULL
        ),

    CONSTRAINT fk_data_exchange_error_batch
        FOREIGN KEY (batch_id)
        REFERENCES data_exchange_batch(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_data_exchange_error_record
        FOREIGN KEY (record_id)
        REFERENCES data_exchange_record(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_batch
    ON data_exchange_error(batch_id);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_record
    ON data_exchange_error(record_id);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_authority
    ON data_exchange_error(authority_code);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_stage
    ON data_exchange_error(batch_id, error_stage);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_unresolved
    ON data_exchange_error(batch_id, resolved);

CREATE INDEX IF NOT EXISTS idx_data_exchange_error_severity
    ON data_exchange_error(batch_id, severity);
