-- V68 -- Create Organisation Structure Import Staging Registry
-- Organisation Management Architecture (OMAS)
--
-- Provides a controlled staging area for organisational structure
-- records received through the Enterprise Data Exchange Framework.
--
-- Incoming data must be validated and reconciled before it can be
-- promoted into the authoritative OMAS registries.
--
-- This table deliberately does NOT replace:
--   directorate
--   section
--   unit
--   position
--
-- It is an intermediate integration layer.

CREATE TABLE IF NOT EXISTS organisation_structure_import_staging (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code      VARCHAR(10) NOT NULL,

    batch_id            BIGINT NOT NULL,

    source_record_reference VARCHAR(150),

    entity_type         VARCHAR(30) NOT NULL,

    parent_source_reference VARCHAR(150),

    entity_code         VARCHAR(40),

    entity_name         VARCHAR(200),

    description         TEXT,

    is_funded           BOOLEAN,

    funding_year        INTEGER,

    is_occupied         BOOLEAN,

    validation_status   VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    validation_message  TEXT,

    resolved_entity_id  BIGINT,

    imported_at         TIMESTAMPTZ,

    imported_by         VARCHAR(120),

    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_org_import_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),

    CONSTRAINT chk_org_import_entity_type
        CHECK (
            entity_type IN (
                'DIRECTORATE',
                'SECTION',
                'UNIT',
                'POSITION'
            )
        ),

    CONSTRAINT chk_org_import_validation_status
        CHECK (
            validation_status IN (
                'PENDING',
                'VALID',
                'INVALID',
                'WARNING',
                'RESOLVED',
                'IMPORTED',
                'REJECTED'
            )
        ),

    CONSTRAINT chk_org_import_entity_code
        CHECK (
            entity_code IS NULL
            OR BTRIM(entity_code) <> ''
        ),

    CONSTRAINT chk_org_import_entity_name
        CHECK (
            entity_name IS NULL
            OR BTRIM(entity_name) <> ''
        ),

    CONSTRAINT chk_org_import_funding_year
        CHECK (
            funding_year IS NULL
            OR funding_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT fk_org_import_batch
        FOREIGN KEY (batch_id)
        REFERENCES data_exchange_batch(id)
        ON DELETE RESTRICT
);

-- Locate all staged records belonging to an exchange batch.
CREATE INDEX IF NOT EXISTS idx_org_import_batch
    ON organisation_structure_import_staging(batch_id);

-- Authority-level lookup.
CREATE INDEX IF NOT EXISTS idx_org_import_authority
    ON organisation_structure_import_staging(authority_code);

-- Validation processing queue.
CREATE INDEX IF NOT EXISTS idx_org_import_validation
    ON organisation_structure_import_staging(
        authority_code,
        validation_status
    );

-- Find staged records by organisational entity type.
CREATE INDEX IF NOT EXISTS idx_org_import_entity_type
    ON organisation_structure_import_staging(
        authority_code,
        entity_type
    );

-- Find records by source reference.
CREATE INDEX IF NOT EXISTS idx_org_import_source_reference
    ON organisation_structure_import_staging(
        batch_id,
        source_record_reference
    );

-- Find records awaiting resolution/import.
CREATE INDEX IF NOT EXISTS idx_org_import_pending
    ON organisation_structure_import_staging(
        authority_code,
        validation_status,
        entity_type
    );

-- Find records by organisational code.
CREATE INDEX IF NOT EXISTS idx_org_import_entity_code
    ON organisation_structure_import_staging(
        authority_code,
        entity_type,
        entity_code
    );
