-- V69 -- Create Organisation Structure Validation & Resolution Registry
-- Organisation Management Architecture (OMAS)
--
-- Records the outcome of validating and reconciling each staged
-- organisational-structure import record.
--
-- V68 = organisation_structure_import_staging
-- V69 = validation / resolution outcome
--
-- This registry provides:
--   * validation status
--   * resolution status
--   * resolved entity references
--   * parent resolution information
--   * validation/reconciliation messages
--   * reviewer / resolver accountability
--   * historical validation decisions
--
-- IMPORTANT:
-- This table does not replace the staging table.
-- Staging preserves the imported source record.
-- This table records what the system determined about that record.

CREATE TABLE IF NOT EXISTS organisation_structure_validation_resolution (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    authority_code              VARCHAR(10) NOT NULL,

    staging_id                  BIGINT NOT NULL,

    batch_id                    BIGINT NOT NULL,

    entity_type                 VARCHAR(30) NOT NULL,

    source_record_reference     VARCHAR(150),

    entity_code                 VARCHAR(40),

    entity_name                 VARCHAR(200),

    validation_status           VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    resolution_status           VARCHAR(30) NOT NULL DEFAULT 'UNRESOLVED',

    resolved_entity_id          BIGINT,

    resolved_parent_entity_id   BIGINT,

    resolution_type             VARCHAR(30),

    validation_message          TEXT,

    resolution_message          TEXT,

    discrepancy_type            VARCHAR(50),

    discrepancy_details         TEXT,

    resolved_by                 VARCHAR(120),

    resolved_at                 TIMESTAMPTZ,

    reviewed_by                 VARCHAR(120),

    reviewed_at                 TIMESTAMPTZ,

    notes                       TEXT,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,


    -- ============================================================
    -- Authority validation
    -- ============================================================

    CONSTRAINT chk_org_validation_authority_not_blank
        CHECK (BTRIM(authority_code) <> ''),


    -- ============================================================
    -- Entity type
    -- ============================================================

    CONSTRAINT chk_org_validation_entity_type
        CHECK (
            entity_type IN (
                'DIRECTORATE',
                'SECTION',
                'UNIT',
                'POSITION'
            )
        ),


    -- ============================================================
    -- Validation status
    -- ============================================================

    CONSTRAINT chk_org_validation_status
        CHECK (
            validation_status IN (
                'PENDING',
                'VALID',
                'INVALID',
                'WARNING',
                'DUPLICATE',
                'RESOLVED',
                'REJECTED'
            )
        ),


    -- ============================================================
    -- Resolution status
    -- ============================================================

    CONSTRAINT chk_org_resolution_status
        CHECK (
            resolution_status IN (
                'UNRESOLVED',
                'MATCHED',
                'CREATED',
                'UPDATED',
                'MERGED',
                'REJECTED',
                'NOT_REQUIRED'
            )
        ),


    -- ============================================================
    -- Resolution type
    -- ============================================================

    CONSTRAINT chk_org_resolution_type
        CHECK (
            resolution_type IS NULL
            OR resolution_type IN (
                'EXACT_MATCH',
                'CODE_MATCH',
                'NAME_MATCH',
                'PARENT_MATCH',
                'MANUAL_MATCH',
                'NEW_ENTITY',
                'MERGE',
                'CORRECTION'
            )
        ),


    -- ============================================================
    -- Entity identifiers must be positive when supplied
    -- ============================================================

    CONSTRAINT chk_org_validation_resolved_entity
        CHECK (
            resolved_entity_id IS NULL
            OR resolved_entity_id > 0
        ),

    CONSTRAINT chk_org_validation_resolved_parent
        CHECK (
            resolved_parent_entity_id IS NULL
            OR resolved_parent_entity_id > 0
        ),


    -- ============================================================
    -- Resolution accountability
    -- ============================================================

    CONSTRAINT chk_org_resolution_details
        CHECK (
            resolved_at IS NULL
            OR resolved_by IS NOT NULL
        ),


    -- ============================================================
    -- Review accountability
    -- ============================================================

    CONSTRAINT chk_org_review_details
        CHECK (
            reviewed_at IS NULL
            OR reviewed_by IS NOT NULL
        ),


    -- ============================================================
    -- Foreign key to staging record
    -- ============================================================

    CONSTRAINT fk_org_validation_staging
        FOREIGN KEY (staging_id)
        REFERENCES organisation_structure_import_staging(id)
        ON DELETE RESTRICT,


    -- ============================================================
    -- Foreign key to exchange batch
    -- ============================================================

    CONSTRAINT fk_org_validation_batch
        FOREIGN KEY (batch_id)
        REFERENCES data_exchange_batch(id)
        ON DELETE RESTRICT,


    -- ============================================================
    -- One validation/resolution record per staging record
    -- ============================================================

    CONSTRAINT uq_org_validation_staging
        UNIQUE (staging_id)
);


-- ================================================================
-- General authority lookup
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_authority
    ON organisation_structure_validation_resolution(authority_code);


-- ================================================================
-- Batch processing
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_batch
    ON organisation_structure_validation_resolution(batch_id);


-- ================================================================
-- Validation status
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_status
    ON organisation_structure_validation_resolution(
        authority_code,
        validation_status
    );


-- ================================================================
-- Resolution status
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_resolution_status
    ON organisation_structure_validation_resolution(
        authority_code,
        resolution_status
    );


-- ================================================================
-- Entity lookup
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_entity
    ON organisation_structure_validation_resolution(
        entity_type,
        resolved_entity_id
    );


-- ================================================================
-- Source-record lookup
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_source_reference
    ON organisation_structure_validation_resolution(
        authority_code,
        source_record_reference
    );


-- ================================================================
-- Entity-code lookup
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_entity_code
    ON organisation_structure_validation_resolution(
        authority_code,
        entity_type,
        entity_code
    );


-- ================================================================
-- Outstanding validation queue
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_pending
    ON organisation_structure_validation_resolution(
        authority_code,
        validation_status,
        resolution_status
    );


-- ================================================================
-- Review / resolution history
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_org_validation_reviewed
    ON organisation_structure_validation_resolution(
        reviewed_at DESC
    );


CREATE INDEX IF NOT EXISTS idx_org_validation_resolved
    ON organisation_structure_validation_resolution(
        resolved_at DESC
    );
