-- H2-compatible initialization of leave_policy table.
-- Runs after Hibernate create-drop creates other tables.

CREATE TABLE IF NOT EXISTS leave_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_type VARCHAR(255),
    division VARCHAR(100),
    accrual_rate DOUBLE PRECISION,
    max_days INTEGER,
    carry_forward INTEGER,
    eligibility VARCHAR(1000),
    fixed_days INTEGER,
    max_accumulation INTEGER,
    max_duration INTEGER,
    advance_notice INTEGER,
    gender_restriction VARCHAR(50) DEFAULT 'ALL',
    day_calculation_mode VARCHAR(50) DEFAULT 'WORKING',
    monthly_limit INTEGER,
    annual_limit INTEGER,
    sick_full_pay_months INTEGER,
    sick_half_pay_months INTEGER,
    sick_full_pay_days_contract INTEGER,
    sick_half_pay_days_contract INTEGER,
    requires_birth_proof BOOLEAN DEFAULT FALSE,
    requires_medical_cert BOOLEAN DEFAULT FALSE,
    advance_notice_days INTEGER DEFAULT 0,
    continuous_leave_limit INTEGER
);

INSERT INTO leave_policy (leave_type, division, accrual_rate, max_accumulation, advance_notice, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert, advance_notice_days, continuous_leave_limit) VALUES
    ('Vacation Leave', 'I', 3.5, 230, 30, 'ALL', 'WORKING', FALSE, FALSE, 30, 120),
    ('Vacation Leave', 'II', 3.0, 205, 30, 'ALL', 'WORKING', FALSE, FALSE, 30, 110),
    ('Vacation Leave', 'III', 2.5, 160, 30, 'ALL', 'WORKING', FALSE, FALSE, 30, 100),
    ('Vacation Leave', 'IV', 2.0, 160, 30, 'ALL', 'WORKING', FALSE, FALSE, 30, 100);

INSERT INTO leave_policy (leave_type, division, accrual_rate, max_days, carry_forward, max_accumulation, max_duration, advance_notice, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert) VALUES
    ('Local Leave', 'I', 2.0, 30, 0, 30, 30, 0, 0, 'ALL', 'WORKING', FALSE, FALSE),
    ('Local Leave', 'II', 2.0, 30, 0, 30, 30, 0, 0, 'ALL', 'WORKING', FALSE, FALSE),
    ('Local Leave', 'III', 2.0, 30, 0, 30, 30, 0, 0, 'ALL', 'WORKING', FALSE, FALSE),
    ('Local Leave', 'IV', 2.0, 30, 0, 30, 30, 0, 0, 'ALL', 'WORKING', FALSE, FALSE);

INSERT INTO leave_policy (leave_type, fixed_days, max_duration, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert) VALUES
    ('Maternity Leave', 98, 98, 0, 'FEMALE', 'CALENDAR', TRUE, FALSE),
    ('Paternity Leave', 10, 10, 0, 'MALE', 'CALENDAR', TRUE, FALSE),
    ('Compassionate Leave', 14, 21, 0, 'ALL', 'WORKING', FALSE, FALSE);

INSERT INTO leave_policy (leave_type, max_duration, annual_limit, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert)
VALUES ('Family Care Leave', 3, 3, 0, 'ALL', 'WORKING', FALSE, FALSE);

INSERT INTO leave_policy (leave_type, fixed_days, max_duration, monthly_limit, annual_limit, carry_forward, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert)
VALUES ('Mother''s Day Leave', 1, 1, 1, 12, 0, 0, 'FEMALE', 'WORKING', FALSE, FALSE);

INSERT INTO leave_policy (leave_type, carry_forward, sick_full_pay_months, sick_half_pay_months, sick_full_pay_days_contract, sick_half_pay_days_contract, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert)
VALUES ('Sick Leave', 0, 3, 3, 26, 26, 0, 'ALL', 'CALENDAR', FALSE, TRUE);

INSERT INTO leave_policy (leave_type, carry_forward, advance_notice, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert)
VALUES ('Study Leave', 0, 30, 30, 'ALL', 'CALENDAR', FALSE, FALSE);

INSERT INTO leave_policy (leave_type, fixed_days, max_duration, max_accumulation, advance_notice, advance_notice_days, gender_restriction, day_calculation_mode, requires_birth_proof, requires_medical_cert)
VALUES ('Unpaid Leave', 365, 365, 365, 30, 30, 'ALL', 'WORKING', FALSE, FALSE);

-- Audit log table (matches V46 production migration)
CREATE TABLE IF NOT EXISTS leave_calculation_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_request_id BIGINT,
    leave_type VARCHAR(100) NOT NULL,
    division VARCHAR(100),
    start_date DATE,
    requested_days INTEGER NOT NULL,
    adjusted_days INTEGER,
    forfeited_days INTEGER,
    reason VARCHAR(255),
    balance_before INTEGER,
    balance_after INTEGER,
    calculation_mode VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    triggered_by VARCHAR(100),
    username VARCHAR(80),
    authority_code VARCHAR(10),
    authority_type VARCHAR(50),
    role VARCHAR(200)
);
